/* NEW DRAFTS · CRM · phone counterparts for every web view (9 Sep 2026). Loads after mod-crm-more.jsx and rebuilds the
   CRM entry on window.NEW_DRAFT_MODULES so phone and web lists sit in the same flow order. Sheet bodies come from
   mod-crm-more.jsx; base screens from mod-crm.jsx take an `over` node (scrim + sheet, or toast + dock). */

/* ── helpers ── */
const pSheet = (T, h, title, body, foot) => <>{scrimF(T)}<Sheet T={T} h={h} title={title} foot={foot}><div style={{ height: '100%', overflow: 'hidden' }}>{body}</div></Sheet></>;
const pFoot = (T, primary, icon, secondary) => <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>{secondary}<span style={{ flex: 1 }} /><T.Btn icon={icon} style={{ height: 44 }}>{primary}</T.Btn></div>;
const PTabs = ({ T, tabs, active }) => <div style={{ display: 'flex', gap: 2, padding: '8px 14px 0', overflow: 'hidden' }}>{tabs.map(([t, n]) => { const on = t === active; return <span key={t} className="press" style={{ flex: 'none', position: 'relative', display: 'inline-flex', alignItems: 'center', gap: 5, padding: '6px 10px 9px', fontFamily: T.fontUI, fontSize: 13, fontWeight: on ? 600 : 400, color: on ? T.ink : T.ink3, whiteSpace: 'nowrap' }}>{t}{n != null && <span style={{ fontSize: 10.5, color: T.ink3 }}>{n}</span>}{on && <span style={{ position: 'absolute', left: 10, right: 10, bottom: 0, height: 2, background: T.accent, borderRadius: 1 }} />}</span>; })}</div>;
const PCard = ({ T, children, style }) => <div style={{ margin: '8px 14px 0', padding: 12, borderRadius: 18, background: T.surface, border: `1px solid ${T.line}`, ...style }}>{children}</div>;

/* ── Follow-ups ── */
const ScreenCrFollowFilter = ({ T }) => <ScreenCrFollow T={T} over={pSheet(T, 720, 'Sort & filter · customers', <CustFilterBody T={T} phone />, pFoot(T, 'Show 12 customers', 'check', <><T.Btn kind="ghost" small>Clear</T.Btn><OutBtn T={T} small icon="bookmark">Save view</OutBtn></>))} />;
const ScreenCrFollowNewList = ({ T }) => <ScreenCrFollow T={T} over={pSheet(T, 640, 'New saved list', <NewListBody T={T} phone />, pFoot(T, 'Save list', 'bookmark', <OutBtn T={T} small icon="eye">Preview 12</OutBtn>))} />;
const ScreenCrFollowStepHist = ({ T }) => <ScreenCrFollow T={T} over={pSheet(T, 760, 'Preeti Fashion Hub · history', <StepWork T={T} c={CRM_C[0]} phone history />)} />;
const ScreenCrFollowSnooze = ({ T }) => <ScreenCrFollow T={T} over={pSheet(T, 470, 'Snooze Preeti', <SnoozeMenu T={T} phone />)} />;
const ScreenCrFollowTemplate = ({ T }) => <ScreenCrFollow T={T} over={pSheet(T, 740, 'Edit message', <TemplateBody T={T} phone />, pFoot(T, 'Use this message', 'check', <OutBtn T={T} small icon="rotate-ccw">Reset</OutBtn>))} />;
const ScreenCrFollowNext = ({ T }) => <ScreenCrFollow T={T} over={<><div style={{ position: 'absolute', left: 14, right: 14, bottom: 98, display: 'flex', alignItems: 'center', gap: 8 }}><Toast T={T} title="Preeti moved to Order" sub="Showcase done · next: Ambika Enterprises" style={{ flex: 1 }} /><OutBtn T={T} small icon="undo-2" style={{ background: T.surface }}>Undo</OutBtn></div>{crDock(T)}</>} />;
function ScreenCrFollowToday({ T }) {
  return frameF(T, <><CrHeader T={T} node="Follow-ups" lists list="Today’s to-do"><PTabs T={T} tabs={[['Journey board'], ['Today', 7], ['History']]} active="Today" /></CrHeader>
    <Body><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 2 }}><Meta T={T}>7 actions · 2 overdue · 1 waking</Meta><span style={{ flex: 1 }} /><T.Chip outline icon="arrow-down-up" style={{ height: 26, fontSize: 11 }}>Oldest first</T.Chip><T.Chip on style={{ height: 26, fontSize: 11 }}>Mine</T.Chip></div><TodayRows T={T} phone /></Body></>, crDock(T));
}
function ScreenCrFollowHistory({ T }) {
  return frameF(T, <><CrHeader T={T} node="Follow-ups" placeholder="Customer, step, outcome"><PTabs T={T} tabs={[['Journey board'], ['Today', 7], ['History']]} active="History" /></CrHeader>
    <Body><div style={{ display: 'flex', gap: 6, marginBottom: 8, overflow: 'hidden' }}>{['All', 'Calls', 'WhatsApp', 'Packets', 'Orders', 'Snoozes'].map((q, i) => <T.Chip key={q} on={i === 0} outline={i !== 0} style={{ height: 26, fontSize: 11 }}>{q}</T.Chip>)}</div><div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, padding: '0 4px' }}><HistoryRows T={T} phone n={8} /></div></Body></>, crDock(T));
}

/* ── Share ── */
const ScreenCrSharePicker = ({ T }) => <ScreenCrShare T={T} over={pSheet(T, 640, 'Customers on this step', <CustomerPickerBody T={T} phone />)} />;
const ScreenCrShareSort = ({ T }) => <ScreenCrShare T={T} over={pSheet(T, 470, 'Sort Recommended', <SortMenu T={T} />)} />;
const ScreenCrShareFilter = ({ T }) => <ScreenCrShare T={T} over={pSheet(T, 760, 'Sort & filter · Recommended', <><div style={{ borderBottom: `1px solid ${T.line}`, padding: '2px 0 10px' }}><Meta T={T} style={{ display: 'block', marginBottom: 6, letterSpacing: '.08em', textTransform: 'uppercase' }}>For this customer</Meta><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>{[['Bought before', false], ['Never bought', true], ['Price match', true], ['Colour match', false], ['State match', false], ['What worked', false]].map(([l, on]) => <T.Chip key={l} on={on} outline={!on} style={{ height: 28 }}>{l}</T.Chip>)}</div></div><SheetBody T={T} /></>, pFoot(T, 'Show 31 designs', 'check', <><T.Btn kind="ghost" small>Clear</T.Btn><OutBtn T={T} small icon="bookmark">Save</OutBtn></>))} />;
function ScreenCrShareViewer({ T }) {
  return frameF(T, <><CrHeader T={T} title="8337" back noSearch right={<Meta T={T}>1 of 12</Meta>} /><Body style={{ padding: '10px 14px 110px' }}><ViewerBody T={T} phone /></Body></>, <><div style={{ position: 'absolute', left: 14, right: 14, bottom: 22, display: 'flex', gap: 8, padding: 8, borderRadius: 24, ...glass(T) }}><OutBtn T={T} icon="chevron-left" style={{ height: 44, width: 44, padding: 0, justifyContent: 'center' }} /><OutBtn T={T} icon="arrow-up-right" style={{ flex: 1, justifyContent: 'center', height: 44 }}>Product</OutBtn><T.Btn icon="check" style={{ flex: 1, height: 44 }}>In packet</T.Btn><OutBtn T={T} icon="chevron-right" style={{ height: 44, width: 44, padding: 0, justifyContent: 'center' }} /></div></>);
}
const ScreenCrShareVerify = ({ T }) => <ScreenCrShare T={T} verify />;
const ScreenCrShareContacts = ({ T }) => <ScreenCrShare T={T} over={pSheet(T, 640, 'Send to', <ContactBody T={T} phone />, pFoot(T, 'Use 2 recipients', 'check'))} />;
const ScreenCrShareExport = ({ T }) => <ScreenCrShare T={T} over={pSheet(T, 700, 'Export · 5 designs', <ExportBody T={T} phone />, pFoot(T, 'Download 3 files', 'download', <Meta T={T}>saved to history</Meta>))} />;
const ScreenCrShareSent = ({ T }) => <ScreenCrShare T={T} over={pSheet(T, 690, 'Sent', <SentBody T={T} phone />, pFoot(T, 'Next · Ambika', 'arrow-right', <OutBtn T={T} small icon="history">History</OutBtn>))} />;
function ScreenCrLogoAll({ T }) {
  return frameF(T, <><CrHeader T={T} title="Place logo · all 6" back noSearch right={<T.Chip on style={{ height: 30 }}>Done</T.Chip>} /><Body style={{ padding: '10px 14px 130px' }}><div style={{ display: 'flex', gap: 4, marginBottom: 10, overflow: 'hidden' }}>{['All', 'Product', 'Photoshoot', 'Video frames'].map((s, i) => <T.Chip key={s} on={i === 0} outline={i !== 0} style={{ height: 26, fontSize: 11 }}>{s}</T.Chip>)}</div><LogoAllBody T={T} phone /></Body></>, <div style={{ position: 'absolute', left: 14, right: 14, bottom: 22, display: 'flex', gap: 8, padding: 8, borderRadius: 24, ...glass(T) }}><OutBtn T={T} icon="eye" style={{ flex: 1, justifyContent: 'center', height: 44 }}>Preview as sent</OutBtn><T.Btn icon="check-check" style={{ flex: 1, height: 44 }}>Apply to all 6</T.Btn></div>);
}

/* ── Payments ── */
const ScreenCrPayFilter = ({ T }) => <ScreenCrPay T={T} over={pSheet(T, 720, 'Sort & filter · bills', <BillFilterBody T={T} phone />, pFoot(T, 'Show 9 bills', 'check', <><T.Btn kind="ghost" small>Clear</T.Btn><OutBtn T={T} small icon="bookmark">Save list</OutBtn></>))} />;
const ScreenCrPaySnooze = ({ T }) => <ScreenCrPay T={T} over={pSheet(T, 470, 'Snooze Ambika · 2 bills', <SnoozeMenu T={T} phone />)} />;
const ScreenCrPayLog = ({ T }) => <ScreenCrPay T={T} over={pSheet(T, 740, 'Log payment · Ambika', <LogPaymentBody T={T} phone />, pFoot(T, 'Log ₹39,955', 'banknote', <Meta T={T}>receipt → Busy</Meta>))} />;
const ScreenCrPayEscalate = ({ T }) => <ScreenCrPay T={T} over={pSheet(T, 720, 'Escalate · Ambika', <EscalateBody T={T} phone />, pFoot(T, 'Escalate to admin', 'arrow-up-right'))} />;
const ScreenCrPayCleared = ({ T }) => <ScreenCrPay T={T} sheet cleared="SI-2240" />;
function ScreenCrPayBills({ T }) {
  const stages = [1, 2, 3, 4, 0];
  return frameF(T, <><CrHeader T={T} node="Payments" placeholder="Bill no, customer, broker"><PTabs T={T} tabs={[['Journey map'], ['Bills', 30], ['Customers', 14], ['Broker / agency']]} active="Bills" /></CrHeader>
    <Body><div style={{ display: 'flex', gap: 6, marginBottom: 6, overflow: 'hidden' }}>{['Due', 'Overdue', 'Issue', 'Escalate', 'RED', 'Snoozed', 'Mine'].map((q, i) => <T.Chip key={q} on={i === 1} outline={i !== 1} style={{ height: 26, fontSize: 11 }}>{q}</T.Chip>)}</div>{stages.map(st => { const bs = CRM_BILLS.filter(b => b.stage === st); return bs.length ? <div key={st}><div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 4px 4px' }}><Pill T={T} small tone={st >= 3 ? 'danger' : st >= 1 ? 'warn' : 'muted'} fill={st === 4}>{PAY_STAGES[st][0]}</Pill><Meta T={T}>{bs.length} · {money(bs.reduce((s, b) => s + b.amt, 0))}</Meta></div><div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, padding: '0 12px' }}>{bs.map((b, i) => <BillRow key={b.no} T={T} b={b} phone first={i === 0} on={b.no === 'SI-2240'} />)}</div></div> : null; })}</Body></>, crDock(T));
}
function ScreenCrPayCustomers({ T }) {
  return frameF(T, <><CrHeader T={T} node="Payments" placeholder="Customer, broker, city"><PTabs T={T} tabs={[['Journey map'], ['Bills', 30], ['Customers', 14], ['Broker / agency']]} active="Customers" /></CrHeader>
    <Body><div style={{ display: 'flex', gap: 6, marginBottom: 8, overflow: 'hidden' }}>{['Worst stage', 'Payment risk', 'Over credit', 'Platinum', 'Mine'].map((q, i) => <T.Chip key={q} on={i === 0} outline={i !== 0} style={{ height: 26, fontSize: 11 }}>{q}</T.Chip>)}</div><PayCustomerRows T={T} phone /><div style={{ display: 'flex', gap: 8, marginTop: 10 }}><T.Kpi small label="Collected this week" value="₹2.4L" sub="6 bills" tone="ok" /><T.Kpi small label="Promised" value="₹1.1L" sub="3 by Friday" /></div></Body></>, crDock(T));
}
function ScreenCrPayBrokers({ T, over }) {
  return frameF(T, <><CrHeader T={T} node="Payments" placeholder="Agency, broker, customer"><PTabs T={T} tabs={[['Journey map'], ['Bills', 30], ['Customers', 14], ['Broker / agency']]} active="Broker / agency" /></CrHeader>
    <Body><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}><Meta T={T}>weekly · Mon 08:00 · 5 agencies</Meta><span style={{ flex: 1 }} /><T.Chip outline icon="calendar-clock" style={{ height: 26, fontSize: 11 }}>Schedule</T.Chip></div>{AGENCIES.map((g, i) => <div key={g.name} className="press" style={{ padding: '10px 12px', borderRadius: 16, background: T.surface, border: `1px solid ${i === 0 ? T.accentLine : T.line}`, marginBottom: 8 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 17, fontWeight: 600, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{g.name}</div><Meta T={T} style={{ display: 'block' }}>{g.brokers.join(' · ')} · {g.customers} customers · sent {g.sent}</Meta></span><Hit T={T} icon="file-text" size={30} iconSize={14} style={{ background: T.chipBg }} /><Hit T={T} icon="phone" size={30} iconSize={14} style={{ background: T.chipBg }} /></div><div style={{ display: 'flex', height: 8, borderRadius: 4, overflow: 'hidden', background: T.chipBg, marginTop: 8 }}><span style={{ width: Math.round(g.due / 300000 * 100) + '%', background: T.ink3 }} /><span style={{ width: Math.round(g.over / 300000 * 100) + '%', background: T.warn }} /><span style={{ width: Math.round(g.issue / 300000 * 100) + '%', background: T.danger }} /></div><div style={{ display: 'flex', gap: 12, marginTop: 5, fontFamily: T.fontUI, fontSize: 11, color: T.ink3 }}><span>due <b style={{ color: T.ink }}>{money(g.due)}</b></span><span>overdue <b style={{ color: g.over ? T.warn : T.ink }}>{money(g.over)}</b></span><span>issue <b style={{ color: g.issue ? T.danger : T.ink }}>{money(g.issue)}</b></span></div></div>)}</Body></>, over || crDock(T));
}
const ScreenCrPayReport = ({ T }) => <ScreenCrPayBrokers T={T} over={pSheet(T, 720, 'Suman Agency · report', <div style={{ fontFamily: T.fontUI }}><Meta T={T} style={{ display: 'block', marginBottom: 6 }}>weekly · WhatsApp to Suman Traders · PDF attached</Meta><ReportBody T={T} a={AGENCIES[0]} /></div>, pFoot(T, 'Send now', 'send', <><OutBtn T={T} small icon="file-text">PDF</OutBtn><OutBtn T={T} small icon="pause">Pause</OutBtn></>))} />;
const ScreenCrPaySchedule = ({ T }) => <ScreenCrPayBrokers T={T} over={pSheet(T, 560, 'Report schedule', <ScheduleBody T={T} phone />, pFoot(T, 'Save schedule', 'check', <Meta T={T}>next Mon 15/09 · 08:00</Meta>))} />;

/* ── Customers ── */
function ScreenCrCustomers({ T, over }) {
  const rows = [CRM_C[0], CRM_C[1], CRM_C[4], CRM_C[2], CRM_C[5], CRM_C[3]];
  return frameF(T, <><CrHeader T={T} node="Customers" placeholder="Name, city, broker, tag" /><div style={{ display: 'flex', gap: 6, padding: '10px 14px 0', overflow: 'hidden' }}>{['Follow-up today', 'Overdue', 'Hot', 'Warm', 'Cold', 'Mine'].map((q, i) => <T.Chip key={q} on={i === 0} outline={i !== 0} style={{ height: 28, fontSize: 11.5 }}>{q}</T.Chip>)}</div>
    <Body style={{ padding: '8px 14px 110px' }}><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}><Meta T={T}>148 · sorted by follow-up due</Meta><span style={{ flex: 1 }} /><Hit T={T} icon="sliders-horizontal" size={28} iconSize={14} style={{ background: T.chipBg, borderRadius: 9 }} /><Hit T={T} icon="columns-3" size={28} iconSize={14} style={{ background: T.chipBg, borderRadius: 9 }} /></div><div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, overflow: 'hidden' }}>{rows.map((r, i) => <div key={r.id + i} className="press" style={{ display: 'flex', alignItems: 'center', gap: 9, padding: '9px 12px', borderTop: i ? `1px solid ${T.line}` : 0, background: i === 0 ? T.accentSoft : 'transparent' }}><span style={{ width: 7, height: 7, borderRadius: 4, background: r.next < 0 ? T.danger : r.next === 0 ? T.accent : 'transparent', border: `1px solid ${r.next > 0 ? T.line2 : 'transparent'}`, flex: 'none' }} /><HeatDot T={T} h={r.heat} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 13.5, fontWeight: 500, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r.name}{r.tags.includes('Direct') && <span style={{ marginLeft: 6 }}><T.Tag tone="muted">Direct</T.Tag></span>}</div><Meta T={T} style={{ display: 'block' }}>{r.city} · {r.tier} · last {r.last} · {money(r.open)} open</Meta></span><Gauge T={T} v={r.score} s={28} /><Hit T={T} icon="phone" size={30} iconSize={14} style={{ background: T.chipBg }} /></div>)}</div></Body></>, over || crDock(T));
}
const ScreenCrCustFilter = ({ T }) => <ScreenCrCustomers T={T} over={pSheet(T, 720, 'Sort & filter · customers', <CustFilterBody T={T} phone />, pFoot(T, 'Show 41 customers', 'check', <><T.Btn kind="ghost" small>Clear</T.Btn><OutBtn T={T} small icon="bookmark">Save view</OutBtn></>))} />;
const ScreenCrCustColumns = ({ T }) => <ScreenCrCustomers T={T} over={pSheet(T, 700, 'Fields on the row', <ColumnsBody T={T} phone />, pFoot(T, 'Apply', 'check', <OutBtn T={T} small icon="rotate-ccw">Default</OutBtn>))} />;
const ScreenCrCustStart = ({ T }) => <ScreenCrCustomers T={T} over={pSheet(T, 640, 'Start a follow-up', <StartFollowBody T={T} phone />, pFoot(T, 'Add to Reach out', 'list-checks'))} />;
const DOSS_TABS = ['Info', 'Packets', 'Orders', 'Invoices', 'Shipments', 'Returns', 'Growth'];
function ScreenCrDossierTab({ T, tab }) {
  const c = CRM_C[0]; const BodyC = tab === 'Packets' ? PacketsPane : tab === 'Orders' ? OrdersPane : tab === 'Invoices' ? DossierInvoices : tab === 'Shipments' ? DossierShipments : tab === 'Returns' ? DossierReturns : DossierGrowth;
  return frameF(T, <><CrHeader T={T} title={c.name} back noSearch right={<Hit T={T} icon="phone" size={40} iconSize={18} />} />
    <Body style={{ padding: '0 0 130px' }}><div style={{ display: 'flex', gap: 4, padding: '10px 14px 0', overflow: 'hidden' }}>{DOSS_TABS.map(t => { const on = t === tab; return <span key={t} style={{ flex: 'none', padding: '6px 10px', fontFamily: T.fontUI, fontSize: 12.5, fontWeight: on ? 600 : 400, color: on ? T.ink : T.ink3, borderBottom: on ? `2px solid ${T.accent}` : '2px solid transparent', whiteSpace: 'nowrap' }}>{t}</span>; })}</div><PCard T={T}><BodyC T={T} phone /></PCard></Body>
    <div style={{ position: 'absolute', left: 14, right: 14, bottom: 98, display: 'flex', gap: 8, padding: 8, borderRadius: 24, ...glass(T) }}><OutBtn T={T} icon="list-checks" style={{ flex: 1, justifyContent: 'center', height: 44 }}>Follow up</OutBtn><T.Btn icon="send" style={{ flex: 1, height: 44 }}>Share</T.Btn></div></>, <T.Island active="CRM" />);
}
const ScreenCrDossPackets = ({ T }) => <ScreenCrDossierTab T={T} tab="Packets" />;
const ScreenCrDossOrders = ({ T }) => <ScreenCrDossierTab T={T} tab="Orders" />;
const ScreenCrDossInvoices = ({ T }) => <ScreenCrDossierTab T={T} tab="Invoices" />;
const ScreenCrDossShipments = ({ T }) => <ScreenCrDossierTab T={T} tab="Shipments" />;
const ScreenCrDossReturns = ({ T }) => <ScreenCrDossierTab T={T} tab="Returns" />;
const ScreenCrDossGrowth = ({ T }) => <ScreenCrDossierTab T={T} tab="Growth" />;

/* ── Journeys: the node map as a vertical flow on the phone ── */
function JFlow({ T, nodes, order, ghostAfter, on }) {
  const byId = Object.fromEntries(nodes.map(n => [n.id, n]));
  const row = (n, k) => { const ic = n.kind === 'trigger' ? 'zap' : n.kind === 'wait' ? 'hourglass' : n.kind === 'branch' ? 'git-fork' : n.kind === 'end' ? 'circle-check' : n.chan; const active = on ? n.id === on : n.on; return <div key={n.id} style={{ display: 'flex', gap: 10, alignItems: 'stretch' }}><div style={{ width: 28, display: 'flex', flexDirection: 'column', alignItems: 'center', flex: 'none' }}><span style={{ width: 26, height: 26, borderRadius: 8, background: n.kind === 'trigger' ? T.accent : n.red ? T.danger : T.chipBg, color: n.kind === 'trigger' || n.red ? '#fff' : T.ink2, display: 'grid', placeItems: 'center', flex: 'none' }}><Ic name={ic} size={12} sw={2} /></span><span style={{ flex: 1, width: 1.5, background: T.line2, minHeight: 10 }} /></div><div className="press" style={{ flex: 1, minWidth: 0, marginBottom: 8, padding: '8px 10px', borderRadius: 14, background: n.kind === 'step' ? T.surface : T.surface2, border: `1px solid ${active ? T.accent : n.red ? T.danger : T.line}`, boxShadow: active ? `0 0 0 3px ${T.accentSoft}` : 'none' }}><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><span style={{ fontFamily: T.fontUI, fontSize: 13, fontWeight: 600, color: T.ink, flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{n.title}</span>{n.kind === 'branch' && <CrTag T={T} tone="accent">yes → Done</CrTag>}{n.kind === 'step' && n.chan === 'message-circle' && <CrTag T={T} tone="accent">auto</CrTag>}<Ic name="chevron-right" size={14} color={T.ink3} /></div><Meta T={T} style={{ display: 'block', marginTop: 2, whiteSpace: 'normal' }}>{n.sub}</Meta></div></div>; };
  const out = []; order.forEach(id => { out.push(row(byId[id])); if (ghostAfter === id) out.push(<div key="ghost" style={{ display: 'flex', gap: 10 }}><div style={{ width: 28, display: 'grid', placeItems: 'center' }}><span style={{ width: 26, height: 26, borderRadius: 8, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center' }}><Ic name="plus" size={13} sw={2.4} /></span></div><div style={{ flex: 1, marginBottom: 8, padding: '8px 10px', borderRadius: 14, border: `1.5px dashed ${T.accent}`, background: T.accentSoft }}><div style={{ fontFamily: T.fontUI, fontSize: 13, fontWeight: 600, color: T.accent }}>New step · Broker nudge</div><Meta T={T} style={{ display: 'block' }}>call · broker of the bill · wait 7 d before</Meta></div></div>); });
  return <div>{out}</div>;
}
const J_ORDER = ['t', 'w1', 's1', 'b1', 's2', 'w2', 's3', 'w3', 's4', 's5'], J_ORDER2 = ['t', 's1', 'w1', 's2', 'b1', 's3', 'w2', 's4', 's5'];
function ScreenCrJourney({ T, over, journey = 'Payments', ghostAfter, on }) {
  const refill = journey === 'Refill';
  return frameF(T, <><CrHeader T={T} node="Journeys" placeholder="Journey, step, template" lists list={journey} /><Body style={{ padding: '10px 14px 130px' }}><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 10 }}><Meta T={T}>{refill ? 'v2 · 32 customers · tier 14 · 21 · 30 d' : 'v3 · 30 bills on it · edited 02/09'}</Meta><span style={{ flex: 1 }} /><T.Chip outline icon="play" style={{ height: 26, fontSize: 11 }}>Test</T.Chip></div><JFlow T={T} nodes={refill ? JN2 : JN} order={refill ? J_ORDER2 : J_ORDER} ghostAfter={ghostAfter} on={on} /></Body>
    <div style={{ position: 'absolute', left: 14, right: 14, bottom: 98, display: 'flex', gap: 8, padding: 8, borderRadius: 24, ...glass(T) }}><OutBtn T={T} icon="plus" style={{ height: 44, width: 44, padding: 0, justifyContent: 'center' }} /><OutBtn T={T} icon="git-branch" style={{ flex: 1, justifyContent: 'center', height: 44 }}>New journey</OutBtn><T.Btn icon="upload" style={{ flex: 1, height: 44 }}>Publish v4</T.Btn></div></>, over || <T.Island active="CRM" />);
}
const ScreenCrJourneyStep = ({ T }) => <ScreenCrJourney T={T} over={pSheet(T, 720, 'Step · Overdue', <div style={{ fontFamily: T.fontUI }}><StepSettings T={T} /></div>, pFoot(T, 'Save step', 'check', <OutBtn T={T} small icon="trash-2">Remove</OutBtn>))} />;
const ScreenCrJourneyRefill = ({ T }) => <ScreenCrJourney T={T} journey="Refill" />;
const ScreenCrJourneyNew = ({ T }) => <ScreenCrJourney T={T} over={pSheet(T, 620, 'New journey', <NewJourneyBody T={T} phone />, pFoot(T, 'Create draft', 'git-branch'))} />;
const ScreenCrJourneyTest = ({ T }) => <ScreenCrJourney T={T} over={pSheet(T, 700, 'Test with Ambika', <TestRunBody T={T} phone />, pFoot(T, 'Re-run', 'rotate-ccw', <Meta T={T}>simulation · nothing is sent</Meta>))} />;
const ScreenCrJourneyAdd = ({ T }) => <ScreenCrJourney T={T} ghostAfter="s2" on="none" />;
const ScreenCrJourneyPublish = ({ T }) => <ScreenCrJourney T={T} over={pSheet(T, 660, 'Publish v4', <PublishBody T={T} phone />, pFoot(T, 'Publish v4', 'upload', <OutBtn T={T} small>Keep draft</OutBtn>))} />;

/* ── registration: rebuild the CRM entry with phone and web in the same flow order ── */
(function () {
  const mods = window.NEW_DRAFT_MODULES || []; const i = mods.findIndex(m => m.module === 'CRM'); if (i < 0) return;
  mods[i] = { module: 'CRM', note: 'follow-up engine (lists × journeys, step strip) · share terminal (customer pane with tabs · purchased, recommended and catalogue picture grids · packet · composer · logo) · payments journey · customers and dossier · journey builder. Every tab, sheet and button state, phone and web (8–9 Sep). ₹ for manager roles', subs: [
    { name: 'Follow-ups', flow: 'board by step → sort & filter → new saved list → step pane → history → snooze → edit message → done, next → Today tab → History tab', phone: [['Follow-ups · today, step strip, cards', ScreenCrFollow], ['Follow-ups · sort & filter sheet', ScreenCrFollowFilter], ['Follow-ups · new saved list', ScreenCrFollowNewList], ['Follow-ups · step sheet', ScreenCrFollowStep], ['Follow-ups · step with history', ScreenCrFollowStepHist], ['Follow-ups · snooze', ScreenCrFollowSnooze], ['Follow-ups · edit message', ScreenCrFollowTemplate], ['Follow-ups · done, next customer', ScreenCrFollowNext], ['Follow-ups · Today tab', ScreenCrFollowToday], ['Follow-ups · History tab', ScreenCrFollowHistory]], web: [['Follow-ups · board by step, step pane', WebCrFollow], ['Follow-ups · sort & filter', WebCrFollowFilter], ['Follow-ups · new saved list', WebCrFollowNewList], ['Follow-ups · step pane with history', WebCrFollowHist], ['Follow-ups · snooze', WebCrFollowSnooze], ['Follow-ups · edit message', WebCrFollowTemplate], ['Follow-ups · done, next customer', WebCrFollowNext], ['Follow-ups · Today tab', WebCrFollowToday], ['Follow-ups · History tab', WebCrFollowHistory]] },
    { name: 'Share', flow: 'terminal (customer pane · Purchased, Recommended, Catalogue grids · packet) → customer picker → Packets and Orders tabs → sort menu → sort & filter → picture viewer → verify against stock → composer → send to → export → sent → place logo → all pictures', phone: [['Share · customer, Recommended grid, selection tray', ScreenCrShare], ['Share · Purchased grid, time frame', ScreenCrSharePurch], ['Share · Catalogue grid', ScreenCrShareCat], ['Share · customer picker', ScreenCrSharePicker], ['Share · sort menu', ScreenCrShareSort], ['Share · sort & filter sheet', ScreenCrShareFilter], ['Share · picture viewer, in packet', ScreenCrShareViewer], ['Share · verified against stock', ScreenCrShareVerify], ['Share · packet sheet (composer)', ScreenCrPacket], ['Share · send to', ScreenCrShareContacts], ['Share · export', ScreenCrShareExport], ['Share · sent', ScreenCrShareSent], ['Share · place logo', ScreenCrLogo], ['Share · logo on all pictures', ScreenCrLogoAll]], web: [['Share · terminal (customer · Purchased, Recommended, Catalogue grids · packet)', WebCrShare], ['Share · customer picker', WebCrSharePicker], ['Share · customer pane · Packets tab', WebCrSharePackets], ['Share · customer pane · Orders tab', WebCrShareOrders], ['Share · sort menu on a grid', WebCrShareSort], ['Share · sort & filter on Recommended', WebCrShareSheet], ['Share · picture viewer, in packet', WebCrShareViewer], ['Share · verified against stock', WebCrShareVerify], ['Share · composer', WebCrComposer], ['Share · send to (contacts)', WebCrShareContacts], ['Share · export', WebCrShareExport], ['Share · sent', WebCrShareSent], ['Share · place logo', WebCrLogo], ['Share · logo on all pictures', WebCrLogoAll]] },
    { name: 'Payments', flow: 'journey map → sort & filter → bill / customer pane → snooze → log payment → escalate → bill cleared → Bills tab → Customers tab → Broker / agency report → schedule', phone: [['Payments · stages, bills', ScreenCrPay], ['Payments · sort & filter sheet', ScreenCrPayFilter], ['Payments · bill sheet', ScreenCrPayBill], ['Payments · snooze', ScreenCrPaySnooze], ['Payments · log payment', ScreenCrPayLog], ['Payments · escalate', ScreenCrPayEscalate], ['Payments · bill cleared, 3 stages', ScreenCrPayCleared], ['Payments · Bills tab', ScreenCrPayBills], ['Payments · Customers tab', ScreenCrPayCustomers], ['Payments · Broker / agency', ScreenCrPayBrokers], ['Payments · report preview', ScreenCrPayReport], ['Payments · report schedule', ScreenCrPaySchedule]], web: [['Payments · journey map, customer pane', WebCrPay], ['Payments · sort & filter', WebCrPayFilter], ['Payments · snooze', WebCrPaySnooze], ['Payments · log payment', WebCrPayLog], ['Payments · escalate', WebCrPayEscalate], ['Payments · bill cleared, customer in 3 stages', WebCrPayCleared], ['Payments · Bills tab', WebCrPayBills], ['Payments · Customers tab', WebCrPayCustomers], ['Payments · broker & agency weekly report', WebCrPayBrokers], ['Payments · report schedule', WebCrPaySchedule]] },
    { name: 'Customers', flow: 'list sorted by follow-up due → sort & filter → columns → dossier Info · Packets · Orders · Invoices & payments · Shipments · Returns · Growth → start a follow-up', phone: [['Customers · list', ScreenCrCustomers], ['Customers · sort & filter', ScreenCrCustFilter], ['Customers · fields on the row', ScreenCrCustColumns], ['Dossier · Info', ScreenCrDossier], ['Dossier · Packets', ScreenCrDossPackets], ['Dossier · Orders', ScreenCrDossOrders], ['Dossier · Invoices & payments', ScreenCrDossInvoices], ['Dossier · Shipments', ScreenCrDossShipments], ['Dossier · Returns & credit notes', ScreenCrDossReturns], ['Dossier · Growth', ScreenCrDossGrowth], ['Customers · start a follow-up', ScreenCrCustStart]], web: [['Customers · list, dossier pane', WebCrCustomers], ['Customers · sort & filter', WebCrCustFilter], ['Customers · column chooser', WebCrCustColumns], ['Dossier · Invoices & payments', WebCrDossierInvoices], ['Dossier · Shipments', WebCrDossierShipments], ['Dossier · Returns & credit notes', WebCrDossierReturns], ['Dossier · Growth', WebCrDossierGrowth], ['Customers · start a follow-up', WebCrCustStart]] },
    { name: 'Journeys', flow: 'payment journey as a node map → step settings → Refill customer journey → new journey → test run → adding a step → publish', phone: [['Journeys · payments flow', ScreenCrJourney], ['Journeys · step settings', ScreenCrJourneyStep], ['Journeys · Refill flow', ScreenCrJourneyRefill], ['Journeys · new journey', ScreenCrJourneyNew], ['Journeys · test run', ScreenCrJourneyTest], ['Journeys · adding a step', ScreenCrJourneyAdd], ['Journeys · publish', ScreenCrJourneyPublish]], web: [['Journey builder · payments, step pane', WebCrJourneys], ['Journey builder · Refill customer journey', WebCrJRefill], ['Journey builder · new journey', WebCrJNew], ['Journey builder · test run', WebCrJTest], ['Journey builder · adding a step', WebCrJAddNode], ['Journey builder · publish v4', WebCrJPublish]] },
  ] };
})();

Object.assign(window, { pSheet, pFoot, PTabs, PCard, ScreenCrFollowFilter, ScreenCrFollowNewList, ScreenCrFollowStepHist, ScreenCrFollowSnooze, ScreenCrFollowTemplate, ScreenCrFollowNext, ScreenCrFollowToday, ScreenCrFollowHistory, ScreenCrSharePicker, ScreenCrShareSort, ScreenCrShareFilter, ScreenCrShareViewer, ScreenCrShareVerify, ScreenCrShareContacts, ScreenCrShareExport, ScreenCrShareSent, ScreenCrLogoAll, ScreenCrPayFilter, ScreenCrPaySnooze, ScreenCrPayLog, ScreenCrPayEscalate, ScreenCrPayCleared, ScreenCrPayBills, ScreenCrPayCustomers, ScreenCrPayBrokers, ScreenCrPayReport, ScreenCrPaySchedule, ScreenCrCustomers, ScreenCrCustFilter, ScreenCrCustColumns, ScreenCrCustStart, DOSS_TABS, ScreenCrDossierTab, ScreenCrDossPackets, ScreenCrDossOrders, ScreenCrDossInvoices, ScreenCrDossShipments, ScreenCrDossReturns, ScreenCrDossGrowth, JFlow, J_ORDER, J_ORDER2, ScreenCrJourney, ScreenCrJourneyStep, ScreenCrJourneyRefill, ScreenCrJourneyNew, ScreenCrJourneyTest, ScreenCrJourneyAdd, ScreenCrJourneyPublish });
