/* NEW DRAFTS · Studio › AI Designer "Stitch" (9 Sep 2026) · shared data, the modular blocks and the phone screens.
   Plan: plans/studio-designer.md (§12 carries the owner's go decisions). Web screens and the board registration live in
   mod-studio-web.jsx. Everything renders through the theme object T (FINAL / FINALD); names are prefixed St… / ST_.
   Reuses from the base files: frameF, scrimF, Hit, Ic, glass, veil, smoke, Orb, AgentMark, PriceF, Meta, Mono, Num, Pill,
   Sect, OutBtn, Sheet, Body, DSearch, Thumb, LineG, Line, ViewTabs, RightPane, WebShell3, SheetBody, SheetFoot, ModeSwitch.

   THE STITCH WINDOW. The owner asked for "deep space black and white contrast" so the designer reads as agentic. Stitch's
   window (chat column + canvas) sits on a cool near-black (SP), white type, hairlines at 8 % white; the ERP chrome around it
   (rail, header, right pane, every other Studio screen) stays sand / espresso. Maroon remains the one accent line inside the
   window (send, active zone, current version). Stitch's personality is kept subtle, like the voice button: no avatar, no
   emoji. Stitch speaks in the display face; a spectral thread (the listening aura's colours) runs beside its words and
   under the stage while it draws; the orb breathes on the window head.

   MODULAR. One block per part, the same block on web and phone: StChat · StCanvas · StStrip · StTray · StPane (set / zone /
   version) · StTuner · StSwipe · StTile · StSwatch · StSeg · StSlider · StToggle. Web docks them; the phone stacks or sheets
   them. The renders on the stage are the owner's own ChatGPT output (assets/studio/), cut into tiles. */

const ST_A = 'assets/studio/';
const SP = { bg: '#0B0B0F', bgD: '#050507', bg2: '#13131A', surface: '#181820', line: 'rgba(255,255,255,.08)', line2: 'rgba(255,255,255,.16)', ink: '#F4F2EE', ink2: '#B9B6B0', ink3: '#7E7B76', chip: 'rgba(255,255,255,.07)', thread: 'linear-gradient(180deg,#E0507A,#6E7BFF 55%,#FFB347)', threadH: 'linear-gradient(90deg,#E0507A,#6E7BFF 55%,#FFB347)' };
const spOf = T => ({ ...SP, bg: T.dark ? SP.bgD : SP.bg });
const STUDIO_NODES = [['sparkles', 'Stitch', null], ['image-plus', 'Moodboard', null], ['history', 'History', null], ['brain', 'Memory', null], ['sliders-horizontal', 'Settings', null], ['camera', 'Photoshoots', 3], ['upload', 'Upload centre', 12]];

/* ── data ── */
const ST_CUTS = ['Scalloped V', 'One shoulder', 'Sweetheart cap', 'Halter collar', 'Boat neck sheer', 'Corset cups', 'Keyhole', 'Off shoulder', 'Wrap V', 'Petal sleeve', 'Strappy V', 'Jacket'].map((name, i) => ({ n: i + 1, name, src: ST_A + `cut-${String(i + 1).padStart(2, '0')}.jpg` }));
const stCut = n => ST_CUTS[n - 1];
const ST_SHEET = Array.from({ length: 10 }, (_, i) => ({ n: i + 1, name: 'Design ' + (i + 1), src: ST_A + `sheet-${String(i + 1).padStart(2, '0')}.jpg` }));
const ST_FLAT = Array.from({ length: 6 }, (_, i) => ({ n: i + 1, name: 'Flat ' + (i + 1), src: ST_A + `flat-${String(i + 1).padStart(2, '0')}.jpg` }));
const ST_MAIN = { code: '8337', name: 'Multicolour floral blouse', cat: 'Blouse', price: 12995, src: ST_A + 'blouse-main.jpg', pos: '50% 62%', score: 87, pcs: 164, band: 'High', colours: ['Rani', 'Peach', 'Bottle'] };
const ST_PRODUCTS = [ST_MAIN,
  { code: '8111', name: 'Red bridal lehenga', cat: 'Lehenga', price: 8995, src: 'assets/crm/8111.jpg', pos: '50% 12%', score: 82, pcs: 121, band: 'High' },
  { code: '8321', name: 'Bridal lehenga', cat: 'Lehenga', price: 11495, src: 'assets/crm/8321.jpg', pos: '50% 12%', score: 74, pcs: 58, band: 'Med-high' },
  { code: '8477', name: 'Sharara set', cat: 'Sharara', price: 5495, src: 'assets/crm/8477.jpg', pos: '50% 14%', score: 66, pcs: 92, band: 'Med' },
  { code: '8190', name: 'Peach gown', cat: 'Gown', price: 9495, src: 'assets/crm/8190.jpg', pos: '50% 10%', score: 71, pcs: 40, band: 'Med-high' },
  { code: '8433', name: 'Wine lehenga', cat: 'Lehenga', price: 10995, src: 'assets/crm/8433.jpg', pos: '50% 12%', score: 79, pcs: 77, band: 'High' },
  { code: '2798', name: 'Plazo set', cat: 'Plazo set', price: 4995, src: XD.byCode['2798'].src, pos: '50% 30%', score: 78, pcs: 360, band: 'High' },
  { code: '6002', name: 'Lilac court', cat: 'Lehenga', price: 4995, src: XD.byCode['6002'].src, pos: '50% 25%', score: 84, pcs: 210, band: 'High' },
  { code: '2006', name: 'Lavender pallu', cat: 'Saree', price: 4995, src: XD.byCode['2006'].src, pos: '50% 30%', score: 61, pcs: 96, band: 'Med' },
  { code: '4566', name: 'Blush cape', cat: 'Lehenga', price: null, src: XD.byCode['4566'].src, pos: '50% 30%', score: 55, pcs: 0, band: 'Med', sample: true },
  { code: '7781', name: 'Corset · gold', cat: 'Blouse', price: 8495, src: ST_A + 'flat-02.jpg', pos: '50% 40%', score: 58, pcs: 31, band: 'Med' },
  { code: '3355', name: 'Corset · tassel', cat: 'Blouse', price: 5495, src: ST_A + 'flat-04.jpg', pos: '50% 40%', score: 49, pcs: 22, band: 'Med-low' },
];
const stP = code => ST_PRODUCTS.find(p => p.code === code) || ST_MAIN;
const ST_MATS = [
  { code: 'M-0412', name: 'Wine velvet', tex: 'velvet', col: '#5B1F2E', work: 'Plain', stock: 'In', last: '02/09' },
  { code: 'M-0388', name: 'Gold sequin net', tex: 'sequin', col: '#C9A45C', work: 'Sequins', stock: 'In', last: '28/08' },
  { code: 'M-0201', name: 'Raw silk ivory', tex: 'silk', col: '#E8DCC5', work: 'Plain', stock: 'In', last: '21/08' },
  { code: 'M-0455', name: 'Mono net', tex: 'net', col: '#D9CFC2', work: 'Plain', stock: 'Low', last: '08/09' },
  { code: 'M-0470', name: 'Emerald velvet', tex: 'velvet', col: '#1F5A46', work: 'Plain', stock: 'In', last: '30/08' },
  { code: 'M-0311', name: 'Zari tissue', tex: 'tissue', col: '#C7B27A', work: 'Zari', stock: 'In', last: '12/08' },
  { code: 'M-0499', name: 'Cutdana lace', tex: 'lace', col: '#B99A6A', work: 'Cutdana', stock: 'Low', last: '05/09' },
  { code: 'M-0223', name: 'Rani satin', tex: 'satin', col: '#C2185B', work: 'Plain', stock: 'In', last: '18/08' },
];
const stM = code => ST_MATS.find(m => m.code === code) || ST_MATS[0];
const ST_SAMPLES = [['S-0412', 'Blouse', 'In designing', ST_A + 'cut-06.jpg'], ['S-0409', 'Lehenga', 'Reading 9/15', 'assets/crm/8321.jpg'], ['S-0411', 'Blouse', 'Activated', ST_A + 'sheet-03.jpg'], ['S-0405', 'Saree', 'Deployed', XD.byCode['2006'].src], ['S-0398', 'Blouse', 'Reading 14/15', ST_A + 'flat-05.jpg'], ['S-0401', 'Choli set', 'In designing', null], ['S-0396', 'Blouse', 'Activated', ST_A + 'cut-09.jpg'], ['S-0388', 'Lehenga', 'Deployed', 'assets/crm/8433.jpg']];
const ST_WIP = [['PO-1187 · Embroidery', '2798 · 40 pcs · Rahul', XD.byCode['2798'].src], ['PO-1192 · Dye', 'Mono net → Lilac · 150 m', null], ['PO-1201 · Stitching', '6002 · 24 pcs', XD.byCode['6002'].src], ['S-0412 · Sampling', 'sketch → karigar', ST_A + 'cut-06.jpg']];
const ST_CTX = [{ k: 'p', code: '8337', main: true }, { k: 'p', code: '8111' }, { k: 'p', code: '7781' }, { k: 'p', code: '3355' }, { k: 'mood', src: ST_A + 'mood-01.jpg' }, { k: 'mood', src: ST_A + 'mood-02.jpg' }, { k: 'm', code: 'M-0470' }];
const ST_TRACKS = [['Blouse', 'shirt', 6, 'today', 'sweetheart over halter · gold on gold sells', ST_A + 'cut-06.jpg'], ['Lehenga', 'layers', 4, 'yesterday', 'kali flare reads better than pleats', 'assets/crm/8321.jpg'], ['Saree', 'scroll', 2, '02/09', 'pallu borders · nothing plain', XD.byCode['2006'].src], ['Choli set', 'shirt', 1, '28/08', 'not enough yet', 'assets/crm/8477.jpg'], ['Dupatta', 'wind', 0, '—', 'not started', null], ['Material', 'palette', 3, '30/08', 'velvet under beads · net for sleeves', ST_A + 'flat-02.jpg']];
const ST_THREADS = [['Multicolour floral · cuts', '8337 + 5 refs', 7, '10 min', 'Open', ST_A + 'cut-06.jpg'], ['Bridal gold corset · sheet', '8111 + 2 refs', 3, 'yesterday', 'Saved · S-0412', ST_A + 'sheet-03.jpg'], ['Flat lay · tassel corsets', '3355 + M-0499', 2, 'Mon', 'Shared', ST_A + 'flat-04.jpg'], ['Colourways · rani floral', '8337', 4, '02/09', 'Open', ST_A + 'cut-11.jpg'], ['Sketch · petal sleeve', 'cut 10', 1, '30/08', 'Archived', ST_A + 'cut-10.jpg']];
const ST_TEMPLATES = [['Cuts 4×3', 'grid-3x3'], ['Design sheet 20', 'layout-grid'], ['Flat lay 6', 'gallery-horizontal'], ['Colourways', 'palette'], ['Sketch', 'pencil'], ['Close-up of work', 'zoom-in'], ['On model', 'user'], ['Material into inspiration', 'shirt']];
const ST_ZONES = { Blouse: [['Neckline', 22, 8, 56, 22], ['Bodice', 26, 30, 48, 42], ['Sleeve L', 2, 26, 22, 34], ['Sleeve R', 76, 26, 22, 34], ['Hem', 20, 74, 60, 18]] }; /* name, left %, top %, width %, height % */
const ST_VERSIONS = [1, 2, 3, 4, 5, 6, 7].map(v => ({ v, src: ST_A + `cut-${String([1, 3, 6, 6, 2, 6, 6][v - 1]).padStart(2, '0')}.jpg`, branch: v === 5 }));
const ST_MSGS = [
  { me: true, text: 'Take 8337 as the main. The other blouses are references. New designs in the same multicolour beadwork with different cuts, a 4 × 3 grid on a clear white board.', ctx: 6 },
  { st: true, text: 'Twelve cuts on the same beadwork. The lotus stays the hero; only necklines and sleeves move. Row three pushes further than your refs.', set: 'cuts' },
  { me: true, text: 'Cell 6, same but sweetheart neck, in emerald velvet.' },
  { st: true, text: 'Cut 6 with a sweetheart line and the velvet under the beads. v7 is on the stage, v6 stays as the ghost.', set: 'v7' },
];
const ST_MOOD_MINE = [['mood-01.jpg', 'upload', '12/08'], ['cut-03.jpg', 'stitch', 'similar to 8337 · 10/09'], ['mood-02.jpg', 'whatsapp', 'from 98152 · 09/09'], ['sheet-05.jpg', 'stitch', 'from track Blouse · 08/09'], ['mood-03.jpg', 'link', 'pinterest · 02/09'], ['flat-01.jpg', 'upload', '30/08'], ['mood-04.jpg', 'link', 'instagram · 28/08'], ['cut-10.jpg', 'stitch', 'kept from v3 · 26/08'], ['mood-05.jpg', 'whatsapp', 'from 98395 · 21/08'], ['flat-06.jpg', 'upload', '18/08'], ['mood-06.jpg', 'link', 'pinterest · 12/08'], ['sheet-08.jpg', 'stitch', 'from track Blouse · 10/08']].map(([f, src, note]) => ({ src: ST_A + f, kind: src, note }));
const ST_MOOD_ST = [['Multicolour floral · cuts', 24, ['cut-01', 'cut-04', 'cut-08', 'cut-11', 'mood-01', 'cut-12']], ['Bridal gold corset · sheet', 18, ['sheet-01', 'sheet-04', 'sheet-07', 'flat-02', 'sheet-09', 'flat-03']], ['Colourways · rani floral', 9, ['cut-02', 'cut-05', 'cut-09', 'mood-02']]];
const ST_HIST = [['Today', [['10:41', 'Multicolour floral · cuts', 'v7 · sweetheart, emerald velvet', 'cut-06', 'Kept'], ['10:22', 'Multicolour floral · cuts', 'Sleeve · 4 variations', 'cut-10', 'Kept 1'], ['10:04', 'Multicolour floral · cuts', 'Cuts 4×3 · 12 tiles', 'cuts-grid', 'Picked 6'], ['09:30', 'Colourways · rani floral', 'Colourways · 6', 'cut-11', 'Shared']]], ['Yesterday', [['17:12', 'Bridal gold corset · sheet', 'Design sheet 20', 'design-sheet', 'Saved · S-0412'], ['16:40', 'Bridal gold corset · sheet', 'Sketch of design 3', 'sheet-03', 'Design content · 8111'], ['11:05', 'Flat lay · tassel corsets', 'Flat lay 6', 'flatlay', 'Shared']]]];
const ST_WORKS = [['cut-06', 'Multicolour floral · cuts', 'S-0412', '—', '0/15', [3, 4, 4, 6, 7, 9], 0, 0, 'Too early'], ['sheet-03', 'Bridal gold corset · sheet', 'S-0411', '28/08', 'complete', [2, 3, 5, 6, 8, 11], 42, 1, 'Working'], ['cut-09', 'Strappy V · rani', 'S-0396', '12/08', 'complete', [4, 4, 3, 3, 2, 2], 9, 3, 'Weak'], ['flat-05', 'Flat lay · tassel corsets', 'S-0398', '—', '14/15', [1, 2, 2, 4, 5, 7], 0, 0, 'Too early'], ['cut-11', 'Colourways · rani floral', 'S-0402', '20/08', 'complete', [3, 5, 6, 7, 9, 12], 31, 0, 'Working']];
const ST_RULES = [['Prefer sweetheart over halter', 'typed by you · 04/09', true], ['Never plain net sleeves', 'typed by you · 02/09', true], ['Gold on gold sells in Delhi', 'proposed by Stitch · track Blouse · 08/09', true], ['Keep the lotus as the hero on multicolour', 'proposed by Stitch · 10/09', false]];
const ST_MODELS = [['Cuts 4×3', 'nano banana', 'image', 128], ['Design sheet 20', 'gpt image 2', 'image', 41], ['Flat lay 6', 'nano banana', 'image', 22], ['Colourways', 'nano banana', 'image', 36], ['Sketch', 'gpt image 2', 'image', 19], ['Close-up of work', 'gpt image 2', 'image', 8], ['On model', 'gpt image 2', 'image', 5], ['Chat and prompts', 'chat model', 'text', 412]];

/* ── primitives ── */
const stImg = (src, pos) => <img src={src} style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: pos || '50% 50%', display: 'block' }} />;
/* the spectral thread: Stitch's mark on anything it did */
const StThread = ({ w = 2, h, style, horizontal }) => <span style={{ display: 'block', width: horizontal ? '100%' : w, height: horizontal ? w : h, borderRadius: w, background: horizontal ? SP.threadH : SP.thread, opacity: .9, flex: 'none', ...style }} />;
/* Stitch's status, cycling like the rail greeting: one quiet line, never a face */
const ST_MOODS = ['drawing', 'looking at 8337', 'weighing the refs', 'placing the beads', 'checking the neckline', 'thinking about sleeves', 'reading your rules', 'comparing v6 and v7'];
const StMood = ({ color = SP.ink3, size = 11, width = 120 }) => <span className="hi" style={{ position: 'relative', display: 'inline-block', height: size + 6, width, lineHeight: 1 }}>{ST_MOODS.map((w, i) => <span key={w} style={{ position: 'absolute', left: 0, top: 2, fontFamily: '"Cormorant Garamond", serif', fontStyle: 'italic', fontWeight: 500, fontSize: size + 3, color, whiteSpace: 'nowrap', animationDelay: (i * 2.2) + 's', animationDuration: (ST_MOODS.length * 2.2) + 's' }}>{w}</span>)}</span>;
/* AI-render mark on every stage and tile */
const StMark = ({ style }) => <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 20, padding: '0 8px', borderRadius: 999, ...veil({ background: 'rgba(8,8,12,.55)' }), fontFamily: '"Jost", sans-serif', fontSize: 9.5, letterSpacing: '.06em', textTransform: 'uppercase', whiteSpace: 'nowrap', ...style }}><span style={{ width: 10, height: 2, borderRadius: 1, background: SP.threadH }} />AI render · not a fit sample</span>;
/* drawn fabric swatch (materials have no photos yet) */
const StSwatch = ({ m, w = 40, h = 48, r = 9, style }) => { const c = m.col; const tex = m.tex === 'velvet' ? `linear-gradient(160deg, rgba(255,255,255,.22), rgba(0,0,0,.25) 60%), ${c}` : m.tex === 'sequin' ? `radial-gradient(circle at 30% 30%, rgba(255,255,255,.7) 0 1.2px, transparent 1.5px) 0 0/6px 6px, radial-gradient(circle at 70% 70%, rgba(255,255,255,.35) 0 1px, transparent 1.4px) 3px 3px/6px 6px, ${c}` : m.tex === 'net' ? `repeating-linear-gradient(45deg, rgba(0,0,0,.14) 0 1px, transparent 1px 4px), repeating-linear-gradient(-45deg, rgba(0,0,0,.14) 0 1px, transparent 1px 4px), ${c}` : m.tex === 'lace' ? `radial-gradient(circle, rgba(255,255,255,.45) 0 1.5px, transparent 2px) 0 0/8px 8px, ${c}` : m.tex === 'tissue' ? `repeating-linear-gradient(0deg, rgba(255,255,255,.35) 0 1px, transparent 1px 3px), ${c}` : m.tex === 'satin' ? `linear-gradient(120deg, rgba(255,255,255,.45), transparent 40%, rgba(0,0,0,.18)), ${c}` : `linear-gradient(180deg, rgba(255,255,255,.12), rgba(0,0,0,.1)), ${c}`; return <span style={{ width: w, height: h, borderRadius: r, flex: 'none', display: 'block', background: tex, boxShadow: 'inset 0 0 0 1px rgba(0,0,0,.12)', ...style }} />; };
/* photo tile with tick + ring selection (the phone gallery idiom); foot line optional; `n` badge for grid cells */
function StTile({ T, src, pos, on, w, h, r = 12, n, foot, meta, mark, dark, style, children }) {
  return <div className="press" style={{ position: 'relative', width: w, height: h || Math.round(w * 1.2), borderRadius: r, overflow: 'hidden', background: dark ? SP.bg2 : T.photoBg, flex: 'none', ...style }}>
    {src ? stImg(src, pos) : <span style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 11, color: dark ? SP.ink3 : T.ink3 }}>No photo yet</span>}
    {(foot || meta) && <div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, height: '42%', background: 'linear-gradient(180deg, rgba(20,18,17,0), rgba(20,18,17,.6))', pointerEvents: 'none' }} />}
    {n != null && <span style={{ position: 'absolute', top: 6, left: 6, minWidth: 20, height: 20, padding: '0 6px', borderRadius: 10, ...veil({ background: 'rgba(8,8,12,.5)' }), fontFamily: T.fontUI, fontSize: 10.5, fontWeight: 600, display: 'grid', placeItems: 'center' }}>{n}</span>}
    {on && <><span style={{ position: 'absolute', inset: 0, boxShadow: `inset 0 0 0 2.5px ${T.accent}`, borderRadius: 'inherit', pointerEvents: 'none' }} /><span style={{ position: 'absolute', top: 6, right: 6, width: 20, height: 20, borderRadius: 10, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center', boxShadow: '0 1px 4px rgba(0,0,0,.35), 0 0 0 1.5px rgba(255,255,255,.85)' }}><Ic name="check" size={12} sw={2.6} /></span></>}
    {mark && <span style={{ position: 'absolute', right: 6, [meta || foot ? 'top' : 'bottom']: 6 }}><StMark /></span>}
    {(foot || meta) && <div style={{ position: 'absolute', left: 8, right: 8, bottom: 6, display: 'flex', alignItems: 'baseline', gap: 6, color: '#fff', textShadow: '0 1px 2px rgba(0,0,0,.5)', whiteSpace: 'nowrap', overflow: 'hidden' }}>{foot && <span style={{ fontFamily: T.fontDisplay, fontSize: 14, fontWeight: 600, letterSpacing: '.01em' }}>{foot}</span>}<span style={{ flex: 1 }} />{meta && <span style={{ fontFamily: T.fontUI, fontSize: 10.5, opacity: .92 }}>{meta}</span>}</div>}
    {children}
  </div>;
}
const StThumb = ({ T, src, pos, w = 44, h, r = 8, ring, x, label, dark }) => <span style={{ position: 'relative', width: w, height: h || Math.round(w * 1.2), borderRadius: r, overflow: 'hidden', background: dark ? SP.bg2 : T.photoBg, flex: 'none', display: 'block', boxShadow: ring ? `0 0 0 2px ${ring}` : 'none' }}>{src ? stImg(src, pos) : <span style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 8.5, color: T.ink3 }}>none</span>}{x && <span className="press" style={{ position: 'absolute', top: 2, right: 2, width: 15, height: 15, borderRadius: 8, background: 'rgba(8,8,12,.65)', color: '#fff', display: 'grid', placeItems: 'center' }}><Ic name="x" size={9} sw={2.4} /></span>}{label && <span style={{ position: 'absolute', left: 4, bottom: 3, fontFamily: T.fontUI, fontSize: 9, fontWeight: 600, color: '#fff', textShadow: '0 1px 2px rgba(0,0,0,.6)' }}>{label}</span>}</span>;
/* controls that must sit in the same place every time (the owner's rule): one segmented, one slider, one toggle */
const StSeg = ({ T, items, on, small, dark, style }) => <span style={{ display: 'inline-flex', padding: 3, borderRadius: 999, background: dark ? SP.chip : T.bg2, flex: 'none', maxWidth: '100%', overflow: 'hidden', ...style }}>{items.map(s => <span key={s} className="press" style={{ height: small ? 24 : 28, padding: small ? '0 9px' : '0 12px', borderRadius: 999, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: small ? 11 : 12, background: s === on ? (dark ? SP.ink : T.surface) : 'transparent', color: s === on ? (dark ? SP.bg : T.ink) : (dark ? SP.ink2 : T.ink3), boxShadow: s === on ? '0 1px 3px rgba(0,0,0,.12)' : 'none', whiteSpace: 'nowrap' }}>{s}</span>)}</span>;
const StSlider = ({ T, label, v, txt, dark, style }) => { const ink = dark ? SP.ink : T.ink, ink3 = dark ? SP.ink3 : T.ink3, track = dark ? SP.chip : T.chipBg; return <div style={{ marginTop: 10, ...style }}><div style={{ display: 'flex', fontFamily: T.fontUI, fontSize: 11, color: ink3 }}><span>{label}</span><span style={{ flex: 1 }} /><b style={{ color: ink, fontWeight: 600 }}>{txt}</b></div><div style={{ position: 'relative', height: 4, borderRadius: 2, background: track, marginTop: 8 }}><span style={{ position: 'absolute', left: 0, width: v + '%', top: 0, bottom: 0, borderRadius: 2, background: T.accent }} /><span style={{ position: 'absolute', left: v + '%', top: '50%', width: 16, height: 16, borderRadius: 8, background: dark ? SP.ink : T.surface, border: `1.5px solid ${ink}`, transform: 'translate(-50%,-50%)', boxShadow: '0 2px 6px rgba(0,0,0,.25)' }} /></div></div>; };
const StToggle = ({ T, on, dark }) => <span className="press" style={{ width: 30, height: 18, borderRadius: 9, background: on ? T.accent : (dark ? SP.line2 : T.line2), position: 'relative', flex: 'none' }}><span style={{ position: 'absolute', top: 2, left: on ? 14 : 2, width: 14, height: 14, borderRadius: 7, background: '#fff', boxShadow: '0 1px 2px rgba(0,0,0,.25)' }} /></span>;
const StToggleRow = ({ T, label, sub, on, dark, right, style }) => <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 0', borderTop: `1px solid ${dark ? SP.line : T.line}`, ...style }}><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5, color: dark ? SP.ink : T.ink }}>{label}</div>{sub && <div style={{ fontFamily: T.fontUI, fontSize: 11, color: dark ? SP.ink3 : T.ink3, marginTop: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{sub}</div>}</span>{right || <StToggle T={T} on={on} dark={dark} />}</div>;
const StCaret = ({ T, icon, children, dark, on, style }) => <span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 28, padding: '0 9px 0 8px', borderRadius: 999, background: on ? (dark ? SP.ink : T.ink) : (dark ? SP.chip : T.chipBg), color: on ? (dark ? SP.bg : T.bg) : (dark ? SP.ink : T.ink), fontFamily: T.fontUI, fontSize: 11.5, whiteSpace: 'nowrap', flex: 'none', ...style }}>{icon && <Ic name={icon} size={12} />}{children}<Ic name="chevron-down" size={11} style={{ opacity: .7 }} /></span>;
const StBtn = ({ T, icon, children, primary, dark, small, style }) => <span className="press" style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6, height: small ? 30 : 36, padding: small ? '0 11px' : '0 14px', borderRadius: 999, border: primary ? 0 : `1px solid ${dark ? SP.line2 : T.line2}`, background: primary ? T.accent : 'transparent', color: primary ? T.onAccent : (dark ? SP.ink : T.ink), fontFamily: T.fontUI, fontSize: small ? 12 : 13, fontWeight: 500, whiteSpace: 'nowrap', flex: 'none', ...style }}>{icon && <Ic name={icon} size={small ? 13 : 15} />}{children}</span>;
/* thumbs up / down: the explicit taste signal on every set and tile */
const StThumbs = ({ T, up, down, dark, size = 26 }) => { const b = on => ({ width: size, height: size, borderRadius: size / 2, display: 'grid', placeItems: 'center', background: on ? T.accent : (dark ? SP.chip : T.chipBg), color: on ? T.onAccent : (dark ? SP.ink2 : T.ink2) }); return <span style={{ display: 'inline-flex', gap: 4, flex: 'none' }}><span className="press" style={b(up)}><Ic name="thumbs-up" size={size * .5} /></span><span className="press" style={b(down)}><Ic name="thumbs-down" size={size * .5} /></span></span>; };
const StHead = ({ T, title, sub, right, dark, style }) => <div style={{ display: 'flex', alignItems: 'center', gap: 8, ...style }}><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 16, fontWeight: 600, color: dark ? SP.ink : T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', lineHeight: 1.15 }}>{title}</div>{sub && <div style={{ fontFamily: T.fontUI, fontSize: 11, color: dark ? SP.ink3 : T.ink3, marginTop: 2, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{sub}</div>}</span>{right}</div>;

/* ── BLOCK · context tray: what Stitch is looking at; one Main ring, the rest refs; the metadata switch ── */
function StTray({ T, items = ST_CTX, dark = true, meta = true, size = 40, stack, style }) {
  const thumbs = <span style={{ display: 'flex', gap: 5, overflow: 'hidden', flex: 1, minWidth: 0 }}>{items.map((it, i) => { const src = it.k === 'p' ? stP(it.code).src : it.src; const pos = it.k === 'p' ? stP(it.code).pos : undefined; return <span key={i} style={{ position: 'relative', flex: 'none' }}>{it.k === 'm' ? <StSwatch m={stM(it.code)} w={size} h={Math.round(size * 1.2)} r={8} style={{ boxShadow: it.main ? `0 0 0 2px ${T.accent}` : 'inset 0 0 0 1px rgba(0,0,0,.12)' }} /> : <StThumb T={T} src={src} pos={pos} w={size} ring={it.main ? T.accent : null} dark={dark} />}{it.main ? <span style={{ position: 'absolute', left: 0, right: 0, bottom: -2, textAlign: 'center', fontFamily: T.fontUI, fontSize: 8.5, letterSpacing: '.06em', textTransform: 'uppercase', color: T.onAccent, background: T.accent, borderRadius: 999, padding: '1px 0', margin: '0 4px' }}>main</span> : null}</span>; })}<span className="press" style={{ width: size, height: Math.round(size * 1.2), borderRadius: 8, border: `1px dashed ${dark ? SP.line2 : T.line2}`, display: 'grid', placeItems: 'center', color: dark ? SP.ink2 : T.ink2, flex: 'none' }}><Ic name="plus" size={14} /></span></span>;
  const sw = meta != null && <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontFamily: T.fontUI, fontSize: 10.5, color: dark ? SP.ink3 : T.ink3, whiteSpace: 'nowrap', flex: 'none' }}>Sales data<StToggle T={T} on={meta} dark={dark} /></span>;
  if (stack) return <div style={style}>{thumbs}<div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 6 }}><span style={{ fontFamily: T.fontUI, fontSize: 10.5, color: dark ? SP.ink3 : T.ink3, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', flex: 1 }}>8337 is the main · 5 refs · 1 material</span>{sw}</div></div>;
  return <div style={{ display: 'flex', alignItems: 'center', gap: 6, ...style }}>{thumbs}{sw}</div>;
}

/* ── BLOCK · chat column: the thread head, the tray, the conversation, the prompt box. Stitch speaks in the display face
   beside a spectral thread; the user speaks in Jost on a chip. Collapses to a spine. ── */
function StMsg({ T, m, phone }) {
  if (m.me) return <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 12 }}><div style={{ maxWidth: '86%', padding: '9px 12px', borderRadius: '16px 16px 4px 16px', background: SP.chip, border: `1px solid ${SP.line}`, fontFamily: T.fontUI, fontSize: phone ? 13 : 12.5, lineHeight: 1.45, color: SP.ink }}>{m.text}{m.ctx && <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>{ST_CTX.slice(0, m.ctx).map((it, i) => <StThumb key={i} T={T} src={it.k === 'p' ? stP(it.code).src : it.src} pos={it.k === 'p' ? stP(it.code).pos : undefined} w={26} h={32} r={5} ring={it.main ? T.accent : null} dark />)}</div>}</div></div>;
  return <div style={{ display: 'flex', gap: 10, marginTop: 14, alignItems: 'stretch' }}><StThread h="auto" style={{ alignSelf: 'stretch', minHeight: 24 }} /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontDisplay, fontSize: phone ? 16.5 : 15.5, lineHeight: 1.35, color: SP.ink, fontWeight: 500 }}>{m.text}</div>
    {m.set === 'cuts' && <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>{ST_CUTS.slice(0, 6).map(c => <StThumb key={c.n} T={T} src={c.src} w={phone ? 42 : 36} h={phone ? 36 : 32} r={6} dark ring={c.n === 6 ? T.accent : null} />)}<span style={{ alignSelf: 'center', fontFamily: T.fontUI, fontSize: 10.5, color: SP.ink3, marginLeft: 2 }}>+6</span></div>}
    {m.set === 'v7' && <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 8 }}><StThumb T={T} src={ST_A + 'cut-06.jpg'} w={44} h={38} r={6} dark ring={T.accent} label="v7" /><StThumb T={T} src={ST_A + 'cut-03.jpg'} w={44} h={38} r={6} dark label="v6" /><span style={{ flex: 1 }} /><StThumbs T={T} dark size={24} /></div>}
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 6, fontFamily: T.fontUI, fontSize: 10.5, color: SP.ink3 }}>{m.set ? <><span>Cuts 4×3 · sales data on</span><span className="press" style={{ color: SP.ink2 }}>Re-run</span><span className="press" style={{ color: SP.ink2 }}>Copy prompt</span></> : null}</div>
  </div></div>;
}
function StPrompt({ T, phone, chips = true, text }) {
  return <div style={{ flex: 'none' }}>
    {chips && <div style={{ display: 'flex', gap: 5, overflow: 'hidden', marginBottom: 8, maskImage: 'linear-gradient(90deg,#000 85%,transparent)', WebkitMaskImage: 'linear-gradient(90deg,#000 85%,transparent)' }}>{ST_TEMPLATES.map(([t, ic], i) => <span key={t} className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 26, padding: '0 10px', borderRadius: 999, background: i === 0 ? SP.ink : SP.chip, color: i === 0 ? SP.bg : SP.ink2, fontFamily: T.fontUI, fontSize: 11, whiteSpace: 'nowrap', flex: 'none' }}><Ic name={ic} size={11} />{t}</span>)}</div>}
    <div style={{ borderRadius: 18, background: SP.bg2, border: `1px solid ${SP.line2}`, boxShadow: `0 0 0 3px ${T.dark ? 'rgba(178,74,90,.12)' : 'rgba(86,28,36,.14)'}`, padding: '10px 10px 8px 12px' }}>
      <div style={{ fontFamily: T.fontUI, fontSize: phone ? 13.5 : 13, color: text ? SP.ink : SP.ink3, minHeight: 20, lineHeight: 1.4 }}>{text || 'Describe the design, or drop a picture'}<span className="aura-dot" style={{ display: 'inline-block', width: 1.5, height: 14, background: T.accent, marginLeft: 2, verticalAlign: -2 }} /></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 8 }}><Hit T={T} icon="paperclip" size={28} iconSize={14} style={{ background: SP.chip, color: SP.ink2 }} /><StCaret T={T} icon="grid-3x3" dark>Cuts grid</StCaret><StCaret T={T} icon="layout-grid" dark>4 × 3</StCaret><span style={{ flex: 1 }} /><Hit T={T} icon="mic" size={28} iconSize={14} style={{ background: SP.chip, color: SP.ink2 }} /><span className="press" style={{ width: 32, height: 32, borderRadius: 16, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center' }}><Ic name="arrow-up" size={16} sw={2.2} /></span></div>
    </div>
  </div>;
}
function StChat({ T, w = 300, phone, msgs = ST_MSGS, collapsed, working, style }) {
  if (collapsed) return <div style={{ width: 34, flex: 'none', background: SP.bg, borderRight: `1px solid ${SP.line}`, display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: 10, gap: 10 }}><span className="press" style={{ width: 24, height: 24, borderRadius: 8, background: SP.chip, display: 'grid', placeItems: 'center', color: SP.ink2 }}><Ic name="chevron-right" size={14} /></span><Orb T={{ ink: SP.ink }} on={working} size={22} /><span style={{ writingMode: 'vertical-rl', fontFamily: T.fontUI, fontSize: 10.5, color: SP.ink3, letterSpacing: '.08em' }}>Blouse · Multicolour floral</span></div>;
  return <div style={{ width: phone ? '100%' : w, flex: 'none', background: SP.bg, color: SP.ink, borderRight: phone ? 0 : `1px solid ${SP.line}`, display: 'flex', flexDirection: 'column', minHeight: 0, height: '100%', ...style }}>
    {!phone && <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 10px 8px 12px', borderBottom: `1px solid ${SP.line}` }}><Orb T={{ ink: SP.ink }} on={working} size={24} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>Blouse track · Multicolour floral, cuts</div><div style={{ display: 'flex', alignItems: 'center', gap: 4, fontFamily: T.fontUI, fontSize: 10.5, color: SP.ink3, marginTop: 1 }}>Stitch is <StMood width={110} /></div></span><Hit T={T} icon="git-branch" size={26} iconSize={13} style={{ color: SP.ink2, background: SP.chip }} /><Hit T={T} icon="panel-left-close" size={26} iconSize={13} style={{ color: SP.ink2, background: SP.chip }} /></div>}
    <div style={{ padding: phone ? '8px 14px' : '8px 12px', borderBottom: `1px solid ${SP.line}` }}><StTray T={T} size={phone ? 40 : 34} stack /></div>
    <div style={{ flex: 1, minHeight: 0, overflow: 'hidden', padding: phone ? '0 14px 6px' : '0 12px 6px', maskImage: 'linear-gradient(180deg, transparent, #000 14px)', WebkitMaskImage: 'linear-gradient(180deg, transparent, #000 14px)' }}>{msgs.map((m, i) => <StMsg key={i} T={T} m={m} phone={phone} />)}</div>
    <div style={{ padding: phone ? '6px 14px 10px' : '6px 12px 12px', borderTop: `1px solid ${SP.line}` }}><StPrompt T={T} phone={phone} /></div>
  </div>;
}

/* ── BLOCK · canvas: dotted stage on deep black, the set or the picked design, zone overlay, tool palette, the mark ── */
function StZoneOverlay({ T, active, w, h, drop }) {
  return <>{(ST_ZONES.Blouse).map(([name, l, t, zw, zh]) => { const on = name === active, dr = drop === name; return <div key={name} style={{ position: 'absolute', left: l + '%', top: t + '%', width: zw + '%', height: zh + '%', borderRadius: 10, border: `1.5px dashed ${on ? T.accent : 'rgba(255,255,255,.55)'}`, boxShadow: on ? `0 0 0 3px ${T.dark ? 'rgba(178,74,90,.25)' : 'rgba(86,28,36,.28)'}` : dr ? '0 0 0 4px rgba(224,80,122,.35)' : 'none', background: dr ? 'rgba(224,80,122,.12)' : 'transparent' }}><span style={{ position: 'absolute', left: 6, top: -10, padding: '2px 7px', borderRadius: 999, background: on ? T.accent : 'rgba(8,8,12,.6)', color: '#fff', fontFamily: T.fontUI, fontSize: 9.5, letterSpacing: '.04em', whiteSpace: 'nowrap' }}>{name}</span></div>; })}</>;
}
function StCanvas({ T, mode = 'set', w = 520, h = 390, zone, drop, working, phone, tools = true, ghost, style }) {
  const src = mode === 'set' ? ST_A + 'cuts-grid.jpg' : ST_A + 'cut-06.jpg';
  return <div style={{ position: 'relative', width: w, height: h, borderRadius: 16, overflow: 'hidden', background: SP.bg2, backgroundImage: `radial-gradient(${SP.line2} 1px, transparent 1px)`, backgroundSize: '22px 22px', flex: 'none', ...style }}>
    <div style={{ position: 'absolute', inset: mode === 'set' ? 0 : 14, borderRadius: mode === 'set' ? 0 : 12, overflow: 'hidden', background: '#fff' }}>
      {mode === 'compare' ? <><div style={{ position: 'absolute', inset: 0 }}>{stImg(ST_A + 'cut-03.jpg')}</div><div style={{ position: 'absolute', inset: 0, clipPath: 'inset(0 0 0 52%)' }}>{stImg(src)}</div><span style={{ position: 'absolute', left: '52%', top: 0, bottom: 0, width: 2, background: '#fff', boxShadow: '0 0 0 1px rgba(0,0,0,.25)' }} /><span style={{ position: 'absolute', left: '52%', top: '50%', transform: 'translate(-50%,-50%)', width: 30, height: 30, borderRadius: 15, background: '#fff', color: '#111', display: 'grid', placeItems: 'center', boxShadow: '0 2px 8px rgba(0,0,0,.35)' }}><Ic name="chevrons-left-right" size={14} /></span><span style={{ position: 'absolute', left: 10, top: 10, padding: '2px 8px', borderRadius: 999, ...veil(), fontSize: 10.5, fontFamily: T.fontUI }}>v6</span><span style={{ position: 'absolute', right: 10, top: 10, padding: '2px 8px', borderRadius: 999, background: T.accent, color: T.onAccent, fontSize: 10.5, fontFamily: T.fontUI }}>v7</span></> : stImg(src)}
      {mode === 'set' && ST_CUTS.map(c => { const col = (c.n - 1) % 4, row = Math.floor((c.n - 1) / 4); const on = c.n === 6; return <span key={c.n} className="press" style={{ position: 'absolute', left: (col * 25) + '%', top: (row * 33.33) + '%', width: '25%', height: '33.33%', boxShadow: on ? `inset 0 0 0 2.5px ${T.accent}` : 'none' }}><span style={{ position: 'absolute', left: 6, top: 6, minWidth: 18, height: 18, padding: '0 5px', borderRadius: 9, background: on ? T.accent : 'rgba(8,8,12,.45)', color: '#fff', fontFamily: T.fontUI, fontSize: 10, fontWeight: 600, display: 'grid', placeItems: 'center' }}>{c.n}</span>{on && <span style={{ position: 'absolute', right: 6, top: 6, width: 18, height: 18, borderRadius: 9, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center' }}><Ic name="check" size={11} sw={2.6} /></span>}</span>; })}
      {mode === 'picked' && <StZoneOverlay T={T} active={zone} drop={drop} />}
    </div>
    {tools && <div style={{ position: 'absolute', right: 10, top: 10, display: 'flex', flexDirection: phone ? 'row' : 'column', gap: 2, padding: 3, borderRadius: 999, ...smoke({ boxShadow: 'none' }) }}>{['mouse-pointer-2', 'zoom-in', 'columns-2', 'maximize-2'].map((ic, i) => <span key={ic} className="press" style={{ width: 28, height: 28, borderRadius: 14, display: 'grid', placeItems: 'center', background: (mode === 'compare' && ic === 'columns-2') || (i === 0 && mode !== 'compare') ? 'rgba(255,255,255,.18)' : 'transparent' }}><Ic name={ic} size={14} /></span>)}</div>}
    <span style={{ position: 'absolute', left: 10, bottom: 10 }}><StMark /></span>
    {mode === 'set' && <span style={{ position: 'absolute', right: 10, bottom: 10, padding: '3px 8px', borderRadius: 999, ...veil(), fontFamily: T.fontUI, fontSize: 10.5 }}>12 tiles · cell 6 picked</span>}
    {working && <span style={{ position: 'absolute', left: 0, right: 0, bottom: 0, height: 2, background: SP.threadH, opacity: .9 }} />}
  </div>;
}
/* version strip: v1 … vn, current ringed, branch mark where a zone edit forked, + for a new generation */
function StStrip({ T, cur = 7, versions = ST_VERSIONS, w = 44, dark = true, compact, style }) {
  return <div style={{ display: 'flex', alignItems: 'center', gap: compact ? 6 : 8, overflow: 'hidden', ...style }}>{versions.map(v => <span key={v.v} style={{ position: 'relative', flex: 'none' }}>{v.branch && <span style={{ position: 'absolute', left: -6, top: '50%', transform: 'translateY(-50%)', color: dark ? SP.ink3 : T.ink3 }}><Ic name="git-branch" size={11} /></span>}<StThumb T={T} src={v.src} w={w} h={Math.round(w * .86)} r={8} ring={v.v === cur ? T.accent : null} label={'v' + v.v} dark={dark} /></span>)}<span className="press" style={{ width: w, height: Math.round(w * .86), borderRadius: 8, border: `1px dashed ${dark ? SP.line2 : T.line2}`, display: 'grid', placeItems: 'center', color: dark ? SP.ink2 : T.ink2, flex: 'none' }}><Ic name="plus" size={14} /></span>{!compact && <><span style={{ flex: 1 }} /><span style={{ fontFamily: T.fontUI, fontSize: 10.5, color: dark ? SP.ink3 : T.ink3, whiteSpace: 'nowrap' }}>v7 of 7 · branch at v5</span></>}</div>;
}
/* the four variations of a zone, under the stage */
function StVariations({ T, dark = true, w = 74, style }) {
  return <div style={{ display: 'flex', alignItems: 'center', gap: 8, ...style }}><span style={{ fontFamily: T.fontUI, fontSize: 11, color: dark ? SP.ink3 : T.ink3, width: 64, lineHeight: 1.3 }}>Sleeve · 4 of 4</span>{[8, 10, 5, 2].map((n, i) => <StThumb key={n} T={T} src={stCut(n).src} w={w} h={Math.round(w * .82)} r={9} ring={i === 1 ? T.accent : null} dark={dark} />)}<StBtn T={T} dark={dark} small icon="check">Keep 2</StBtn></div>;
}

/* ── BLOCK · the right pane in its three states. The controls sit in the same place every time: head · what was made ·
   the one-click row · the buttons at the foot. Docked on web (sand), a half-height sheet on the phone. ── */
const StRow = ({ T, k, children, dark }) => <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}><span style={{ width: 58, flex: 'none', fontFamily: T.fontUI, fontSize: 11, color: dark ? SP.ink3 : T.ink3 }}>{k}</span><span style={{ flex: 1, minWidth: 0, display: 'flex', gap: 5, alignItems: 'center', overflow: 'hidden' }}>{children}</span></div>;
const StChipRow = ({ T, items, on, dark, wrap }) => <div style={{ display: 'flex', gap: 5, flexWrap: wrap ? 'wrap' : 'nowrap', overflow: 'hidden' }}>{items.map(x => <span key={x} className="press" style={{ display: 'inline-flex', alignItems: 'center', height: 26, padding: '0 10px', borderRadius: 999, background: x === on ? (dark ? SP.ink : T.ink) : (dark ? SP.chip : T.chipBg), color: x === on ? (dark ? SP.bg : T.bg) : (dark ? SP.ink : T.ink), fontFamily: T.fontUI, fontSize: 11.5, whiteSpace: 'nowrap', flex: 'none' }}>{x}</span>)}</div>;
function StPane({ T, state = 'set', phone, dark = false, style }) {
  const ink = dark ? SP.ink : T.ink, ink3 = dark ? SP.ink3 : T.ink3, line = dark ? SP.line : T.line;
  const Foot = ({ children }) => <div style={{ marginTop: 'auto', paddingTop: 10, borderTop: `1px solid ${line}`, display: 'flex', flexDirection: 'column', gap: 6 }}>{children}</div>;
  const body = state === 'set' ? <>
    <StHead T={T} dark={dark} title="Set · Cuts 4×3" sub="12 tiles · 8337 main + 5 refs · sales data on" right={<StThumbs T={T} up dark={dark} />} />
    <StRow T={T} k="Made with" dark={dark}><StCaret T={T} dark={dark}>Cuts grid</StCaret><StCaret T={T} dark={dark}>4 × 3</StCaret><span style={{ fontFamily: T.fontUI, fontSize: 11, color: ink3 }}>nano banana</span></StRow>
    <StRow T={T} k="Sent" dark={dark}><span style={{ fontFamily: T.fontUI, fontSize: 11.5, color: ink }}>score 87 · 5.4 pcs/day · 3 of 3 colours free</span></StRow>
    <Sect T={{ ...T, ink, accent: T.accent, fontDisplay: T.fontDisplay }} style={{ margin: '14px 0 6px' }}>On the whole set</Sect>
    <StChipRow T={T} dark={dark} wrap items={['Re-run', 'Re-run · data off', 'More like cell 6', 'Colourways from picked', 'Sketch of picked']} on="More like cell 6" />
    <Sect T={{ ...T, ink, accent: T.accent, fontDisplay: T.fontDisplay }} style={{ margin: '14px 0 6px' }}>Picked · cell 6</Sect>
    <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}><StThumb T={T} src={stCut(6).src} w={64} h={56} r={10} ring={T.accent} dark={dark} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12, color: ink, lineHeight: 1.4 }}>Corset cups · sweetheart line<div style={{ fontSize: 11, color: ink3 }}>picked at 10:04 · thumbs up</div></span><StThumbs T={T} up dark={dark} size={24} /></div>
    <Foot><div style={{ display: 'flex', gap: 6 }}><StBtn T={T} dark={dark} icon="image-plus" style={{ flex: 1 }}>To moodboard</StBtn><StBtn T={T} dark={dark} icon="send" style={{ flex: 1 }}>Share</StBtn></div><StBtn T={T} primary icon="flask-conical" style={{ width: '100%' }}>Save picked as sample</StBtn></Foot>
  </> : state === 'zone' ? <>
    <StHead T={T} dark={dark} title="Zone · Sleeve L" sub="v7 · cut 6 · drop a material, colour or work on it" right={<Hit T={T} icon="x" size={26} iconSize={13} style={{ background: dark ? SP.chip : T.chipBg, color: ink }} />} />
    <StRow T={T} k="Material" dark={dark}><StSwatch m={stM('M-0470')} w={30} h={36} r={7} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12, color: ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>Emerald velvet <span style={{ color: ink3 }}>· M-0470</span></span><span className="press" style={{ fontFamily: T.fontUI, fontSize: 11, color: T.accent, fontWeight: 600 }}>Change</span></StRow>
    <StRow T={T} k="Colour" dark={dark}><StChipRow T={T} dark={dark} items={['Emerald', 'Bottle', 'Rani', 'Gold']} on="Emerald" /></StRow>
    <StRow T={T} k="Work" dark={dark}><StChipRow T={T} dark={dark} items={['Zardozi', 'Sequins', 'Mirror', 'Cutdana', 'Thread', 'Plain']} on="Sequins" /></StRow>
    <StSlider T={T} dark={dark} label="Scale" v={38} txt="Medium" /><StSlider T={T} dark={dark} label="Density" v={64} txt="Heavy" />
    <StRow T={T} k="Repeat" dark={dark}><StSeg T={T} dark={dark} items={['Mirror', 'Flow', 'Scatter']} on="Mirror" small /></StRow>
    <StRow T={T} k="Drape" dark={dark}><StCaret T={T} dark={dark} icon="wind">Draped on mannequin</StCaret><span style={{ fontFamily: T.fontUI, fontSize: 10.5, color: ink3 }}>whole garment</span></StRow>
    <Foot><div style={{ display: 'flex', gap: 6 }}><StBtn T={T} dark={dark} icon="grid-2x2" style={{ flex: 1 }}>4 variations</StBtn><StBtn T={T} primary icon="refresh-cw" style={{ flex: 1 }}>Regenerate zone</StBtn></div></Foot>
  </> : <>
    <StHead T={T} dark={dark} title="Version 7" sub="from v5 · sweetheart, emerald velvet" right={<StThumbs T={T} up dark={dark} />} />
    <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: dark ? SP.chip : T.surface2, border: `1px solid ${line}`, fontFamily: T.fontDisplay, fontSize: 14, color: ink, lineHeight: 1.35 }}>Cell 6, same but sweetheart neck, in emerald velvet.</div>
    <StRow T={T} k="Context" dark={dark}><StTray T={T} items={ST_CTX.slice(0, 4)} dark={dark} meta={null} size={26} /></StRow>
    <StRow T={T} k="Template" dark={dark}><StCaret T={T} dark={dark}>Re-prompt</StCaret><StCaret T={T} dark={dark}>Single</StCaret></StRow>
    <StRow T={T} k="Sent" dark={dark}><span style={{ fontFamily: T.fontUI, fontSize: 11.5, color: ink }}>sales data on · demand band High · pcs 30 d</span></StRow>
    <Sect T={{ ...T, ink, accent: T.accent, fontDisplay: T.fontDisplay }} style={{ margin: '14px 0 6px' }}>Views of v7</Sect>
    <StChipRow T={T} dark={dark} wrap items={['Sketch', 'Close-up of work', 'On model · preview', 'Colourways']} />
    <Foot><div style={{ display: 'flex', gap: 6 }}><StBtn T={T} dark={dark} icon="trash-2" small>Discard</StBtn><StBtn T={T} dark={dark} icon="star" small>Make this the main</StBtn></div><StBtn T={T} primary icon="check" style={{ width: '100%' }}>Keep v7</StBtn></Foot>
  </>;
  return <div style={{ display: 'flex', flexDirection: 'column', height: '100%', padding: phone ? '0 0 22px' : '12px 14px 14px', boxSizing: 'border-box', color: ink, ...style }}>{body}</div>;
}

/* ── BLOCK · the tuner: translucent right pane with fixed tabs, stored per thread ── */
const ST_TUNER_TABS = ['Templates', 'Workflow', 'Models', 'Usage', 'Memory'];
function StTuner({ T, tab = 'Templates', phone, style }) {
  const dark = true, ink = SP.ink, ink3 = SP.ink3;
  const T2 = { ...T, ink, ink2: SP.ink2, ink3, line: SP.line, line2: SP.line2, chipBg: SP.chip, surface: SP.surface, surface2: SP.bg2, bg2: SP.bg2 };
  return <div style={{ display: 'flex', flexDirection: 'column', height: '100%', color: ink, ...style }}>
    {!phone && <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '12px 12px 6px 14px' }}><Orb T={{ ink }} size={24} /><span style={{ flex: 1 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 17, fontWeight: 600 }}>Tune Stitch</div><div style={{ fontFamily: T.fontUI, fontSize: 10.5, color: ink3 }}>as you left it · thread Multicolour floral</div></span><Hit T={T2} icon="x" size={28} iconSize={14} style={{ background: SP.chip }} /></div>}
    <div style={{ display: 'flex', gap: 0, padding: '0 8px', borderBottom: `1px solid ${SP.line}` }}>{ST_TUNER_TABS.map(t => <span key={t} className="press" style={{ position: 'relative', padding: '6px 8px 9px', fontFamily: T.fontUI, fontSize: 12, fontWeight: t === tab ? 600 : 400, color: t === tab ? ink : ink3, whiteSpace: 'nowrap' }}>{t}{t === tab && <span style={{ position: 'absolute', left: 8, right: 8, bottom: -1, height: 2, background: T.accent, borderRadius: 1 }} />}</span>)}</div>
    <div style={{ flex: 1, minHeight: 0, overflow: 'hidden', padding: '8px 14px' }}>
      {tab === 'Templates' && <>{ST_TEMPLATES.slice(0, 5).map(([t, ic], i) => <div key={t} style={{ padding: '8px 0', borderTop: i ? `1px solid ${SP.line}` : 0 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Ic name={ic} size={14} color={ink3} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12.5 }}>{t}</span>{i > 2 && <Ic name="star" size={12} color={T.gold} />}<Ic name={i === 0 ? 'chevron-up' : 'chevron-down'} size={13} color={ink3} /></div>{i === 0 && <div style={{ marginTop: 8 }}><div style={{ padding: '8px 10px', borderRadius: 10, background: SP.chip, fontFamily: T.fontMono, fontSize: 10.5, lineHeight: 1.5, color: SP.ink2 }}>Use {'{main}'} as the garment. Keep its work and colour story. {'{refs}'} guide the cuts. Draw a {'{grid}'} of distinct necklines, sleeves and hemlines on a clear white board, front view, same mannequin, no props.</div><div style={{ display: 'flex', gap: 6, marginTop: 8, alignItems: 'center' }}><StCaret T={T} dark icon="layout-grid">4 × 3</StCaret><StCaret T={T} dark>nano banana</StCaret><span style={{ flex: 1 }} /><span style={{ fontFamily: T.fontUI, fontSize: 10.5, color: ink3 }}>128 runs</span></div></div>}</div>)}</>}
      {tab === 'Models' && <>{ST_MODELS.map(([t, m, kind, n], i) => <div key={t} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 0', borderTop: i ? `1px solid ${SP.line}` : 0 }}><Ic name={kind === 'text' ? 'message-circle' : 'image'} size={13} color={ink3} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12.5, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{t}</span><StCaret T={T} dark>{m}</StCaret></div>)}<div style={{ marginTop: 10, fontFamily: T.fontUI, fontSize: 10.5, color: ink3 }}>Keys and providers live in Settings › Models. This tab picks per template for this thread.</div></>}
      {tab === 'Workflow' && <>{[['Loops', 'Draw once, then re-run only what you pick'], ['Before drawing', 'Read the taste rules · 4 on'], ['After a set', 'Propose one rule if 3 tiles agree'], ['Zone edits', 'Mask only the zone · keep the beads outside']].map(([k, v], i) => <div key={k} style={{ padding: '8px 0', borderTop: i ? `1px solid ${SP.line}` : 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5 }}>{k}</div><div style={{ fontFamily: T.fontUI, fontSize: 11, color: ink3, marginTop: 2 }}>{v}</div></div>)}</>}
      {tab === 'Usage' && <><div style={{ display: 'flex', gap: 8 }}><T2.Kpi label="Runs · Sep" value="259" sub="42 this thread" small /><T2.Kpi label="Images" value="1,204" sub="6 failed" small /></div><div style={{ marginTop: 10 }}><LineG T={T2} series={[{ pts: [12, 18, 15, 22, 26, 24, 31, 28, 36, 34, 40, 38], color: T.accent, width: 2 }]} w={300} h={70} area /></div><div style={{ marginTop: 8, fontFamily: T.fontUI, fontSize: 10.5, color: ink3 }}>cost shows for admin only</div></>}
      {tab === 'Memory' && <>{[['Remember this thread', true], ['Use the taste rules', true], ['Send sales data by default', true], ['Learn from thumbs and swipes', true], ['Web collection · coming later', false]].map(([k, on], i) => <StToggleRow key={k} T={T} label={k} on={on} dark />)}</>}
    </div>
  </div>;
}

/* ── BLOCK · swipe approval (phone): one tile at a time; right keep, left discard, up save ── */
function StSwipe({ T, w = 330 }) {
  const cur = stCut(6), next = stCut(7);
  return <div style={{ position: 'relative', width: w, height: Math.round(w * 1.1), margin: '0 auto' }}>
    <div style={{ position: 'absolute', left: 14, right: 14, top: 18, bottom: 0, borderRadius: 22, overflow: 'hidden', background: '#fff', transform: 'scale(.94)', opacity: .55 }}>{stImg(next.src)}</div>
    <div style={{ position: 'absolute', inset: 0, borderRadius: 22, overflow: 'hidden', background: '#fff', transform: 'rotate(-3deg) translateX(-8px)', boxShadow: '0 30px 60px -20px rgba(0,0,0,.6)' }}>{stImg(cur.src)}
      <span style={{ position: 'absolute', left: 14, top: 14, padding: '4px 10px', borderRadius: 8, border: '2px solid #5FCB8A', color: '#5FCB8A', fontFamily: T.fontUI, fontSize: 13, fontWeight: 700, letterSpacing: '.1em', textTransform: 'uppercase', transform: 'rotate(-8deg)', background: 'rgba(255,255,255,.7)' }}>Keep</span>
      <span style={{ position: 'absolute', left: 12, bottom: 12 }}><StMark /></span>
      <span style={{ position: 'absolute', right: 12, bottom: 12, padding: '3px 8px', borderRadius: 999, ...veil(), fontFamily: T.fontUI, fontSize: 10.5 }}>cell 6 · {cur.name}</span>
    </div>
  </div>;
}

/* ── phone chrome: top bar · search island · node scroller · dock ── */
function StTop({ T, title, back, right, role = 'Design' }) {
  return <div style={{ display: 'flex', alignItems: 'center', padding: '0 10px 0 12px', height: 44, gap: 4 }}>{back ? <Hit T={T} icon="chevron-left" size={40} /> : null}{title ? <span style={{ fontFamily: T.fontDisplay, fontSize: 22, fontWeight: 500, color: T.ink, marginLeft: back ? 0 : 6, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', flex: 1 }}>{title}</span> : <><T.Lockup compact /><span style={{ flex: 1 }} /></>}<span style={{ fontFamily: T.fontUI, fontSize: 12, color: T.ink3, marginRight: 4 }}>{role}</span>{right}<Hit T={T} icon="ellipsis-vertical" size={40} /></div>;
}
function StNodes({ T, active }) {
  const idx = STUDIO_NODES.findIndex(x => x[1] === active); const shift = idx >= 4 ? -(idx - 3) * 96 : 0; /* the active node scrolls into view */
  return <div style={{ position: 'relative', display: 'flex', alignItems: 'center', gap: 4, padding: '8px 36px 0 12px', overflow: 'hidden' }}>{shift ? <span style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: 40, background: `linear-gradient(90deg, ${T.bg}, transparent)`, zIndex: 1, pointerEvents: 'none' }} /> : null}{STUDIO_NODES.map(([ic, l, n]) => { const on = l === active; return <span key={l} className="press" style={{ flex: 'none', display: 'inline-flex', alignItems: 'center', gap: 5, padding: on ? '4px 12px' : '4px 8px', borderRadius: 999, background: on ? T.ink : 'transparent', color: on ? T.bg : T.ink2, fontFamily: T.fontDisplay, fontSize: 16.5, fontWeight: 500, whiteSpace: 'nowrap', transform: shift ? `translateX(${shift}px)` : 'none' }}>{l}{n != null && <span style={{ fontFamily: T.fontUI, fontSize: 10.5, fontWeight: 600, padding: '1px 6px', borderRadius: 999, background: on ? 'rgba(255,255,255,.18)' : T.chipBg, color: on ? T.bg : T.ink2 }}>{n}</span>}</span>; })}<span style={{ position: 'absolute', right: 0, top: 0, bottom: 0, width: 60, background: `linear-gradient(90deg, transparent, ${T.bg} 60%)`, pointerEvents: 'none' }} /><span className="press" style={{ position: 'absolute', right: 10, top: 12, width: 24, height: 24, borderRadius: 12, background: T.chipBg, color: T.ink2, display: 'grid', placeItems: 'center' }}><Ic name="chevron-right" size={13} sw={2.2} /></span></div>;
}
function StHeader({ T, node, title, back, placeholder = 'Track, thread, design no, material', right, children, noSearch, tabs, tab }) {
  return <div style={{ background: T.header, borderBottom: `1px solid ${T.line}`, boxShadow: T.headerShadow, paddingBottom: 8, marginTop: -54, paddingTop: 54, flex: 'none' }}><StTop T={T} title={title} back={back} right={right} />{!noSearch && <DSearch T={T} placeholder={placeholder} />}{node && <StNodes T={T} active={node} />}{tabs && <div style={{ display: 'flex', gap: 2, padding: '6px 12px 0' }}>{tabs.map(([t, n]) => { const on = t === tab; return <span key={t} className="press" style={{ position: 'relative', padding: '6px 9px 8px', fontFamily: T.fontUI, fontSize: 13, fontWeight: on ? 600 : 400, color: on ? T.ink : T.ink3, whiteSpace: 'nowrap' }}>{t}{n != null && <span style={{ fontSize: 10.5, color: T.ink3, marginLeft: 4 }}>{n}</span>}{on && <span style={{ position: 'absolute', left: 9, right: 9, bottom: 0, height: 2, background: T.accent, borderRadius: 1 }} />}</span>; })}</div>}{children}</div>;
}
const stDock = T => <T.Dock active="More" noCart />;
/* half-height sheet with the picture still visible above it (the owner's phone rule for the right pane) */
const StHalfSheet = ({ T, h = 430, title, children, dark }) => <div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, height: h, borderRadius: '26px 26px 0 0', display: 'flex', flexDirection: 'column', ...glass(T, dark ? { background: 'rgba(10,10,14,.9)', border: `1px solid ${SP.line2}`, boxShadow: '0 -20px 60px -20px rgba(0,0,0,.7)' } : { background: T.dark ? 'rgba(28,21,18,.92)' : 'rgba(252,250,246,.94)', boxShadow: '0 -20px 60px -20px rgba(0,0,0,.4)' }) }}><span style={{ width: 36, height: 4, borderRadius: 2, background: dark ? SP.line2 : T.line2, margin: '8px auto 0' }} />{title && <div style={{ display: 'flex', alignItems: 'center', padding: '8px 18px 4px' }}><span style={{ fontFamily: T.fontDisplay, fontSize: 18, fontWeight: 600, color: dark ? SP.ink : T.ink, flex: 1 }}>{title}</span></div>}<div style={{ flex: 1, minHeight: 0, overflow: 'hidden', padding: '0 18px' }}>{children}</div></div>;

/* ── shared list pieces used by both web and phone ── */
const ST_STATE_TONE = s => s.startsWith('Saved') ? 'ok' : s === 'Shared' ? 'blue' : s === 'Archived' ? 'muted' : 'accent';
function StTrackCard({ T, t, on, w, phone }) {
  const [cat, ic, n, last, learned, src] = t;
  return <div className="press" style={{ width: w, flex: 'none', padding: 10, borderRadius: 18, background: T.surface, border: `1px solid ${on ? T.accentLine : T.line}`, boxShadow: on ? `0 0 0 3px ${T.accentSoft}` : T.dark ? 'none' : '0 6px 18px -14px rgba(36,23,18,.25)', display: 'flex', gap: 10, minWidth: 0 }}>
    <StThumb T={T} src={src} w={phone ? 52 : 56} h={phone ? 62 : 66} r={10} />
    <span style={{ flex: 1, minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Ic name={ic} size={13} color={T.ink3} /><span style={{ fontFamily: T.fontDisplay, fontSize: 17, fontWeight: 600, color: T.ink }}>{cat}</span><span style={{ flex: 1 }} /><span style={{ fontFamily: T.fontUI, fontSize: 10.5, color: T.ink3 }}>{last}</span></div><div style={{ fontFamily: T.fontUI, fontSize: 11, color: T.ink3, marginTop: 2 }}>{n} threads</div><div style={{ display: 'flex', gap: 6, marginTop: 5, alignItems: 'stretch' }}><StThread h="auto" style={{ minHeight: 14 }} /><span style={{ fontFamily: T.fontDisplay, fontSize: 12.5, color: T.ink2, lineHeight: 1.3, whiteSpace: phone ? 'normal' : 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{learned}</span></div></span>
  </div>;
}
function StThreadRow({ T, r, on, phone, first }) {
  const [name, ctx, v, last, state, src] = r;
  return <div className="press" style={{ display: 'flex', alignItems: 'center', gap: 10, padding: phone ? '9px 0' : '8px 10px', borderTop: first ? 0 : `1px solid ${T.line}`, background: on ? T.accentSoft : 'transparent', borderRadius: on ? 12 : 0 }}>
    <StThumb T={T} src={src} w={40} h={36} r={8} />
    <span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 13, fontWeight: 600, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{name}</div><Meta T={T} style={{ display: 'block' }}>{ctx} · {v} versions · {last}</Meta></span>
    <Pill T={T} small tone={ST_STATE_TONE(state)}>{state}</Pill>
  </div>;
}
const ST_KIND = { upload: ['upload', 'Upload'], link: ['link', 'Link'], whatsapp: ['message-circle', 'WhatsApp'], stitch: ['sparkles', 'by Stitch'] };
function StMoodTile({ T, it, w, on, phone }) {
  const [ic, l] = ST_KIND[it.kind];
  return <StTile T={T} src={it.src} w={w} h={Math.round(w * 1.05)} r={phone ? 12 : 10} on={on} meta={it.note} style={{ background: T.photoBg }}>{it.kind === 'stitch' ? <span style={{ position: 'absolute', left: 6, top: 6, display: 'inline-flex', alignItems: 'center', gap: 4, height: 18, padding: '0 6px', borderRadius: 999, ...veil({ background: 'rgba(8,8,12,.5)' }), fontFamily: T.fontUI, fontSize: 9, letterSpacing: '.04em' }}><span style={{ width: 8, height: 2, background: SP.threadH, borderRadius: 1 }} />{l}</span> : <span style={{ position: 'absolute', left: 6, top: 6, width: 20, height: 20, borderRadius: 10, ...veil({ background: 'rgba(8,8,12,.5)' }), display: 'grid', placeItems: 'center' }}><Ic name={ic} size={10} /></span>}</StTile>;
}
const ST_HIST_SRC = f => ST_A + f + '.jpg';
function StHistRow({ T, r, on, phone, first }) {
  const [time, thread, what, img, res] = r;
  return <div className="press" style={{ display: 'flex', alignItems: 'center', gap: 10, padding: phone ? '8px 0' : '8px 10px', borderTop: first ? 0 : `1px solid ${T.line}`, background: on ? T.accentSoft : 'transparent', borderRadius: on ? 12 : 0 }}><Mono T={T} size={11} weight={500} color={T.ink3}>{time}</Mono><StThumb T={T} src={ST_HIST_SRC(img)} w={40} h={34} r={7} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{what}</div><Meta T={T} style={{ display: 'block' }}>{thread}</Meta></span><Pill T={T} small tone={res.startsWith('Saved') || res.startsWith('Design') ? 'ok' : res === 'Shared' ? 'blue' : 'muted'}>{res}</Pill></div>;
}
const StVerdict = ({ T, v }) => <Pill T={T} small tone={v === 'Working' ? 'ok' : v === 'Weak' ? 'danger' : 'muted'} fill={v === 'Working'}>{v}</Pill>;
function StWorksRow({ T, r, on, phone, first, moneyOn }) {
  const [img, thread, sno, act, read, tr, pcs, ret, verdict] = r;
  return <div className="press" style={{ display: 'grid', gridTemplateColumns: phone ? '40px 1fr 56px 74px' : '40px 1.4fr 68px 70px 64px 76px 40px 40px 84px', gap: '0 10px', alignItems: 'center', padding: phone ? '8px 0' : '8px 10px', borderTop: first ? 0 : `1px solid ${T.line}`, background: on ? T.accentSoft : 'transparent', borderRadius: on ? 12 : 0, fontFamily: T.fontUI, fontSize: 12, color: T.ink }}>
    <StThumb T={T} src={ST_HIST_SRC(img)} w={40} h={36} r={7} />
    <span style={{ minWidth: 0 }}><div style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{thread}</div><Meta T={T} style={{ display: 'block' }}>{sno}{phone ? ` · ${act === '—' ? 'not activated' : 'activated ' + act} · read ${read}` : ''}</Meta></span>
    {!phone && <><span style={{ color: act === '—' ? T.ink3 : T.ink }}>{act}</span><span style={{ color: read === 'complete' ? T.ok : T.ink2 }}>{read}</span></>}
    <span><Line series={[{ pts: tr, color: T.accent, width: 1.5 }]} w={phone ? 52 : 60} h={20} /></span>
    {!phone && <><span style={{ fontVariantNumeric: 'tabular-nums' }}>{tr[tr.length - 1] * 8}</span><span style={{ fontVariantNumeric: 'tabular-nums', fontWeight: 600 }}>{pcs || '—'}</span><span style={{ color: ret ? T.warn : T.ink3, fontVariantNumeric: 'tabular-nums' }}>{ret || '—'}</span></>}
    <StVerdict T={T} v={verdict} />
  </div>;
}
function StRuleRow({ T, r, first, phone }) { const [text, prov, on] = r; return <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 0', borderTop: first ? 0 : `1px solid ${T.line}` }}><StToggle T={T} on={on} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 15, fontWeight: 500, color: on ? T.ink : T.ink3 }}>{text}</div><div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 2 }}>{prov.startsWith('proposed') && <span style={{ width: 10, height: 2, background: SP.threadH, borderRadius: 1 }} />}<Meta T={T}>{prov}</Meta></div></span>{!phone && <><Hit T={T} icon="pencil" size={26} iconSize={12} style={{ background: T.chipBg, color: T.ink2 }} /><Hit T={T} icon="x" size={26} iconSize={12} style={{ background: T.chipBg, color: T.ink2 }} /></>}</div>; }
function StModelRow({ T, r, first, phone }) { const [t, m, kind, n] = r; return <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 0', borderTop: first ? 0 : `1px solid ${T.line}` }}><Ic name={kind === 'text' ? 'message-circle' : 'image'} size={14} color={T.ink3} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12.5, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{t}<Meta T={T} style={{ display: 'block' }}>{n} runs · Sep</Meta></span><StCaret T={T}>{m}</StCaret>{!phone && <span style={{ width: 8, height: 8, borderRadius: 4, background: T.ok, boxShadow: `0 0 0 3px ${T.ok}33` }} title="key ok" />}</div>; }
/* the selector's tabs and the tile grid, shared by the web dialog and the phone sheet */
const ST_SEL_TABS = [['Products', 612], ['Materials', 214], ['Samples', 9], ['WIP', 4], ['Moodboard', 36]];
function StSelTabs({ T, tab, phone }) { return <div style={{ display: 'flex', gap: 2, borderBottom: `1px solid ${T.line}`, padding: phone ? '0 2px' : 0 }}>{ST_SEL_TABS.map(([t, n]) => { const on = t === tab; return <span key={t} className="press" style={{ position: 'relative', padding: phone ? '8px 7px 10px' : '8px 12px 10px', fontFamily: T.fontUI, fontSize: phone ? 12.5 : 13.5, fontWeight: on ? 600 : 400, color: on ? T.ink : T.ink3, whiteSpace: 'nowrap' }}>{t}{(!phone || on) && <span style={{ fontSize: 10.5, color: T.ink3, marginLeft: 4 }}>{n}</span>}{on && <span style={{ position: 'absolute', left: phone ? 7 : 12, right: phone ? 7 : 12, bottom: -1, height: 2, background: T.accent, borderRadius: 1 }} />}</span>; })}</div>; }
const ST_SEL = ['8337', '8111', '7781', '3355'];
function StSelGrid({ T, tab = 'Products', w, cols, meta = true, phone, sel = ST_SEL }) {
  if (tab === 'Materials') return <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${w}px)`, gap: phone ? 8 : 8 }}>{ST_MATS.map((m, i) => <div key={m.code} className="press" style={{ position: 'relative', width: w, borderRadius: 12, background: T.surface, border: `1px solid ${i === 4 ? T.accent : T.line}`, boxShadow: i === 4 ? `inset 0 0 0 1.5px ${T.accent}` : 'none', overflow: 'hidden' }}><StSwatch m={m} w={w} h={Math.round(w * .78)} r={0} />{i === 4 && <span style={{ position: 'absolute', top: 6, right: 6, width: 20, height: 20, borderRadius: 10, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center', boxShadow: '0 0 0 1.5px rgba(255,255,255,.85)' }}><Ic name="check" size={12} sw={2.6} /></span>}<div style={{ padding: '6px 8px 8px' }}><div style={{ fontFamily: T.fontUI, fontSize: 12, fontWeight: 600, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{m.name}</div><div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 2 }}><Mono T={T} size={10} weight={500} color={T.ink3}>{m.code}</Mono><span style={{ flex: 1 }} />{m.stock === 'Low' ? <Pill T={T} tone="warn" small>Low</Pill> : <Meta T={T}>{m.work}</Meta>}</div></div></div>)}</div>;
  if (tab === 'Samples') return <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${w}px)`, gap: 8 }}>{ST_SAMPLES.map(([no, cat, st, src], i) => <StTile key={no} T={T} src={src} w={w} h={Math.round(w * 1.15)} on={i === 0} foot={no} meta={st} />)}</div>;
  if (tab === 'WIP') return <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${w}px)`, gap: 8 }}>{ST_WIP.map(([no, sub, src]) => <StTile key={no} T={T} src={src} w={w} h={Math.round(w * 1.15)} foot={no.split(' · ')[0]} meta={no.split(' · ')[1]} />)}</div>;
  if (tab === 'Moodboard') return <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${w}px)`, gap: 8 }}>{ST_MOOD_MINE.slice(0, cols * 3).map((it, i) => <StMoodTile key={i} T={T} it={it} w={w} on={i === 0 || i === 2} phone={phone} />)}</div>;
  return <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${w}px)`, gap: 8 }}>{ST_PRODUCTS.map(p => <StTile key={p.code} T={T} src={p.src} pos={p.pos} w={w} h={Math.round(w * 1.2)} on={sel.includes(p.code)} foot={p.code} meta={meta ? `${p.score} · ${p.pcs} pcs` : p.cat}>{meta && <span style={{ position: 'absolute', top: 6, left: 6, padding: '2px 6px', borderRadius: 999, ...veil({ background: 'rgba(8,8,12,.5)' }), fontFamily: T.fontUI, fontSize: 9, letterSpacing: '.04em' }}>{p.band}</span>}</StTile>)}</div>;
}
function StSelTray({ T, phone }) {
  const thumbs = <span style={{ display: 'flex', gap: 5, flex: 'none' }}>{ST_SEL.map((c, i) => <StThumb key={c} T={T} src={stP(c).src} pos={stP(c).pos} w={phone ? 40 : 36} ring={i === 0 ? T.accent : null} x label={i === 0 ? 'main' : 'ref'} />)}<StSwatch m={stM('M-0470')} w={phone ? 40 : 36} h={Math.round((phone ? 40 : 36) * 1.2)} r={8} /></span>;
  const words = <span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, color: T.ink, whiteSpace: 'nowrap' }}>5 of 8 · 8337 is the main</div><Meta T={T} style={{ display: 'block' }}>tap a thumb to make it the main</Meta></span>;
  const btn = <T.Btn small icon="check" style={{ height: 36 }}>Add 5 to context</T.Btn>;
  if (phone) return <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>{thumbs}<div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>{words}{btn}</div></div>;
  return <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>{thumbs}{words}{btn}</div>;
}

/* ── PHONE SCREENS ── */
/* P1 Tracks: category tracks as cards, threads of the picked track, the prompt as a glass tray above the island */
function ScreenStTracks({ T }) {
  return frameF(T, <><StHeader T={T} node="Stitch" />
    <Body style={{ padding: '10px 0 190px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '0 14px' }}><Meta T={T}>6 tracks · one per category · Stitch remembers each</Meta><span style={{ flex: 1 }} /><T.Chip outline icon="plus" style={{ height: 26, fontSize: 11 }}>Track</T.Chip></div>
      <div style={{ display: 'flex', gap: 8, padding: '8px 14px 0', overflow: 'hidden', maskImage: 'linear-gradient(90deg, #000 88%, transparent)', WebkitMaskImage: 'linear-gradient(90deg, #000 88%, transparent)' }}>{ST_TRACKS.slice(0, 3).map((t, i) => <StTrackCard key={t[0]} T={T} t={t} w={230} on={i === 0} phone />)}</div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '12px 14px 0' }}><span style={{ fontFamily: T.fontDisplay, fontSize: 17, fontWeight: 600, color: T.ink }}>Blouse · threads</span><Meta T={T}>6</Meta><span style={{ flex: 1 }} /><T.Chip outline icon="arrow-down-up" style={{ height: 26, fontSize: 11 }}>Last worked</T.Chip></div>
      <div style={{ margin: '8px 14px 0', padding: '0 12px', borderRadius: 16, background: T.surface, border: `1px solid ${T.line}` }}>{ST_THREADS.map((r, i) => <StThreadRow key={r[0]} T={T} r={r} phone first={i === 0} />)}</div>
    </Body></>, <>
    <div style={{ position: 'absolute', left: 14, right: 14, bottom: 98, padding: '8px 8px 8px 14px', borderRadius: 24, display: 'flex', alignItems: 'center', gap: 8, ...glass(T) }}><Orb T={T} size={24} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 13, color: T.ink3 }}>Start a thread · describe or drop a picture</span><span className="press" style={{ width: 34, height: 34, borderRadius: 17, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center' }}><Ic name="arrow-up" size={16} sw={2.2} /></span></div>
    {stDock(T)}</>);
}
/* P2 Designer: the chat full screen on deep space; Stitch's replies carry canvas cards; the prompt tray at the foot */
function StCanvasCard({ T, set }) {
  return <div style={{ marginTop: 8, borderRadius: 16, overflow: 'hidden', background: SP.bg2, border: `1px solid ${SP.line2}` }}>
    <div style={{ position: 'relative', height: set ? 220 : 250, background: '#fff' }}>{stImg(ST_A + (set ? 'cuts-grid.jpg' : 'cut-06.jpg'))}{set && ST_CUTS.map(c => { const col = (c.n - 1) % 4, row = Math.floor((c.n - 1) / 4); return <span key={c.n} style={{ position: 'absolute', left: `calc(${col * 25}% + 5px)`, top: `calc(${row * 33.33}% + 5px)`, minWidth: 16, height: 16, padding: '0 4px', borderRadius: 8, background: c.n === 6 ? T.accent : 'rgba(8,8,12,.45)', color: '#fff', fontFamily: T.fontUI, fontSize: 9, fontWeight: 600, display: 'grid', placeItems: 'center' }}>{c.n}</span>; })}<span style={{ position: 'absolute', left: 8, bottom: 8 }}><StMark /></span></div>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 10px' }}>{set ? <span style={{ display: 'flex', gap: 4 }}>{[1, 2, 3, 4, 5, 6, 7].map(v => <span key={v} style={{ width: 6, height: 6, borderRadius: 3, background: v === 7 ? T.accent : SP.line2 }} />)}</span> : <span style={{ display: 'flex', gap: 4, overflow: 'hidden' }}>{ST_ZONES.Blouse.map(z => <span key={z[0]} style={{ height: 22, padding: '0 8px', borderRadius: 999, background: z[0] === 'Sleeve L' ? T.accent : SP.chip, color: z[0] === 'Sleeve L' ? T.onAccent : SP.ink2, fontFamily: T.fontUI, fontSize: 10.5, display: 'grid', placeItems: 'center', whiteSpace: 'nowrap' }}>{z[0]}</span>)}</span>}<span style={{ flex: 1 }} /><StThumbs T={T} dark size={22} up /><span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontFamily: T.fontUI, fontSize: 11.5, color: SP.ink, fontWeight: 600 }}>Open<Ic name="maximize-2" size={12} /></span></div>
  </div>;
}
function ScreenStChat({ T }) {
  const sp = spOf(T);
  return <div style={{ position: 'relative', height: '100%', background: sp.bg, color: SP.ink, overflow: 'hidden', fontFamily: T.fontUI }}>
    <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(120% 40% at 50% -10%, rgba(255,255,255,.05), transparent 60%)', pointerEvents: 'none' }} />
    <div style={{ position: 'relative', height: '100%', display: 'flex', flexDirection: 'column', paddingTop: 54 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '0 10px 0 6px', height: 44 }}><Hit T={T} icon="chevron-left" size={40} style={{ color: SP.ink }} /><Orb T={{ ink: SP.ink }} on size={26} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>Multicolour floral · cuts</div><div style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 10.5, color: SP.ink3 }}>Blouse track · Stitch is <StMood width={100} /></div></span><Hit T={T} icon="sliders-horizontal" size={36} iconSize={16} style={{ color: SP.ink2, background: SP.chip }} /><Hit T={T} icon="ellipsis-vertical" size={36} iconSize={16} style={{ color: SP.ink2 }} /></div>
      <div style={{ padding: '6px 14px 8px', borderBottom: `1px solid ${SP.line}` }}><StTray T={T} size={40} stack /></div>
      <div style={{ flex: 1, minHeight: 0, overflow: 'hidden', padding: '0 14px' }}>
        <StMsg T={T} m={ST_MSGS[0]} phone /><StMsg T={T} m={{ st: true, text: ST_MSGS[1].text }} phone /><StCanvasCard T={T} set />
        <StMsg T={T} m={ST_MSGS[2]} phone /><StMsg T={T} m={{ st: true, text: ST_MSGS[3].text }} phone /><StCanvasCard T={T} />
      </div>
      <div style={{ padding: '8px 14px 24px', borderTop: `1px solid ${SP.line}` }}><StPrompt T={T} phone /></div>
    </div>
  </div>;
}
/* P3 Canvas full screen: zone chips over the picture, version rail, the Pane button and the tray */
function StCanvasScreen({ T, sheet, tuner }) {
  const sp = spOf(T);
  return <div style={{ position: 'relative', height: '100%', background: sp.bg, color: SP.ink, overflow: 'hidden', fontFamily: T.fontUI }}>
    <div style={{ position: 'relative', height: '100%', display: 'flex', flexDirection: 'column', paddingTop: 54 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '0 10px 0 6px', height: 44 }}><Hit T={T} icon="chevron-left" size={40} style={{ color: SP.ink }} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 600 }}>v7 · cut 6 · sweetheart</div><div style={{ fontSize: 10.5, color: SP.ink3 }}>Multicolour floral · cuts</div></span><StThumbs T={T} dark size={30} up /><Hit T={T} icon="share-2" size={36} iconSize={16} style={{ color: SP.ink2, background: SP.chip, marginLeft: 4 }} /></div>
      <div style={{ padding: '4px 14px 0' }}><StCanvas T={T} mode="picked" w={362} h={sheet ? 300 : 430} zone="Sleeve L" phone /></div>
      {!sheet && <div style={{ padding: '10px 14px 0', display: 'flex', gap: 5, overflow: 'hidden' }}>{ST_ZONES.Blouse.map(z => <span key={z[0]} className="press" style={{ height: 28, padding: '0 11px', borderRadius: 999, background: z[0] === 'Sleeve L' ? T.accent : SP.chip, color: z[0] === 'Sleeve L' ? T.onAccent : SP.ink, fontSize: 11.5, display: 'grid', placeItems: 'center', whiteSpace: 'nowrap', flex: 'none' }}>{z[0]}</span>)}</div>}
      {!sheet && <div style={{ padding: '12px 14px 0', display: 'flex', alignItems: 'center', gap: 8 }}><StStrip T={T} w={38} compact /><span style={{ fontFamily: T.fontUI, fontSize: 10.5, color: SP.ink3, whiteSpace: 'nowrap', flex: 'none' }}>v7 of 7</span></div>}
    </div>
    {sheet ? <StHalfSheet T={T} h={sheet === 'tuner' ? 470 : 430} dark>{sheet === 'tuner' ? <div style={{ height: '100%', margin: '0 -18px' }}><StTuner T={T} tab={tuner || 'Templates'} phone /></div> : <StPane T={T} state={sheet} phone dark />}</StHalfSheet>
      : <div style={{ position: 'absolute', left: 14, right: 14, bottom: 24, display: 'flex', alignItems: 'center', gap: 6, padding: 8, borderRadius: 30, ...glass(T, { background: 'rgba(14,14,20,.75)', border: `1px solid ${SP.line2}` }) }}><StBtn T={T} dark small icon="refresh-cw">Regenerate</StBtn><StBtn T={T} dark small icon="grid-2x2">Variants</StBtn><StBtn T={T} dark small icon="wind" style={{ width: 34, padding: 0 }} /><span style={{ flex: 1 }} /><span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, height: 36, padding: '0 14px', borderRadius: 999, background: T.accent, color: T.onAccent, fontSize: 12.5, fontWeight: 600 }}><Ic name="panel-bottom-open" size={14} />Pane</span></div>}
  </div>;
}
const ScreenStCanvas = ({ T }) => <StCanvasScreen T={T} />;
const ScreenStZoneSheet = ({ T }) => <StCanvasScreen T={T} sheet="zone" />;
const ScreenStTunerSheet = ({ T }) => <StCanvasScreen T={T} sheet="tuner" tuner="Models" />;
/* P5 Context picker sheet */
function ScreenStPicker({ T, tab = 'Products' }) {
  return frameF(T, <StHeader T={T} node="Stitch" />, <>{scrimF(T)}
    <Sheet T={T} h={790} title="Context" foot={<StSelTray T={T} phone />}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}><div style={{ flex: 1, height: 36, borderRadius: 18, background: T.bg2, display: 'flex', alignItems: 'center', gap: 8, padding: '0 12px', fontFamily: T.fontUI, fontSize: 12.5, color: T.ink3 }}><Ic name="search" size={14} />Design no, material, colour, tag</div><span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontFamily: T.fontUI, fontSize: 11, color: T.ink3, whiteSpace: 'nowrap' }}>Sales data<StToggle T={T} on /></span></div>
      <StSelTabs T={T} tab={tab} phone />
      <div style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '8px 0', overflow: 'hidden' }}>{['High demand', 'High growth', 'Category', 'Colour', 'Recent'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 26, fontSize: 11 }}>{c}{i > 1 && i < 4 && <Ic name="chevron-down" size={11} />}</T.Chip>)}<span style={{ flex: 1 }} /><Hit T={T} icon="sliders-horizontal" size={28} iconSize={14} style={{ background: T.surface, border: `1px solid ${T.line2}`, borderRadius: 9 }} /></div>
      <StSelGrid T={T} tab={tab} w={112} cols={3} phone />
    </Sheet></>);
}
/* P6 Swipe approval */
function ScreenStSwipe({ T }) {
  const sp = spOf(T);
  return <div style={{ position: 'relative', height: '100%', background: sp.bg, color: SP.ink, overflow: 'hidden', fontFamily: T.fontUI }}>
    <div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, height: 320, pointerEvents: 'none', overflow: 'hidden', opacity: .45 }}><span className="glow-a" style={{ position: 'absolute', left: '-10%', bottom: 10, width: 280, height: 170, borderRadius: '50%', background: '#E0507A', filter: 'blur(40px)' }} /><span className="glow-b" style={{ position: 'absolute', left: '40%', bottom: -20, width: 260, height: 170, borderRadius: '50%', background: '#6E7BFF', filter: 'blur(40px)' }} /><span className="glow-c" style={{ position: 'absolute', left: '64%', bottom: 26, width: 240, height: 160, borderRadius: '50%', background: '#FFB347', filter: 'blur(40px)' }} /></div>
    <div style={{ position: 'relative', height: '100%', display: 'flex', flexDirection: 'column', paddingTop: 54 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '0 10px 0 6px', height: 44 }}><Hit T={T} icon="chevron-left" size={40} style={{ color: SP.ink }} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, fontWeight: 600 }}>Approve the set · 6 of 12</div><div style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 10.5, color: SP.ink3 }}>Cuts 4×3 · Stitch learns from each swipe</div></span><span style={{ fontFamily: T.fontUI, fontSize: 11, color: SP.ink3 }}>3 kept · 2 out</span></div>
      <div style={{ padding: '18px 0 0' }}><StSwipe T={T} w={318} /></div>
      <div style={{ textAlign: 'center', marginTop: 14 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 19, fontWeight: 600 }}>Corset cups · sweetheart</div><div style={{ fontSize: 11.5, color: SP.ink3, marginTop: 2 }}>right keep · left discard · up save as sample</div></div>
      <div style={{ display: 'flex', justifyContent: 'center', gap: 18, marginTop: 18 }}>{[['x', SP.chip, SP.ink, 54], ['arrow-up', SP.chip, SP.ink, 44], ['heart', T.accent, T.onAccent, 54]].map(([ic, bg, c, s]) => <span key={ic} className="press" style={{ width: s, height: s, borderRadius: s / 2, background: bg, color: c, display: 'grid', placeItems: 'center', border: `1px solid ${SP.line2}`, alignSelf: 'center' }}><Ic name={ic} size={s * .42} sw={2} /></span>)}</div>
      <div style={{ display: 'flex', justifyContent: 'center', gap: 5, marginTop: 16 }}>{ST_CUTS.map(c => <span key={c.n} style={{ width: c.n === 6 ? 16 : 6, height: 6, borderRadius: 3, background: c.n < 6 ? ([2, 4].includes(c.n) ? '#E48383' : '#6FB58C') : c.n === 6 ? SP.ink : SP.line2 }} />)}</div>
    </div>
  </div>;
}
/* P7 · P8 Moodboard */
function ScreenStMood({ T, tab = 'Mine' }) {
  const mine = tab === 'Mine';
  return frameF(T, <><StHeader T={T} node="Moodboard" placeholder="Colour, category, source" tabs={[['Mine', 36], ['Stitch’s', 51]]} tab={tab} />
    <Body style={{ padding: '8px 14px 120px' }}>
      {mine ? <><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}><span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontFamily: T.fontUI, fontSize: 12, color: T.ink }}><StToggle T={T} on={false} />Only my uploads & links</span><span style={{ flex: 1 }} /><T.Chip outline icon="upload" style={{ height: 26, fontSize: 11 }}>Upload</T.Chip><T.Chip outline icon="link" style={{ height: 26, fontSize: 11 }}>Link</T.Chip></div>
        <div style={{ display: 'flex', gap: 5, marginBottom: 8, overflow: 'hidden' }}>{['New', 'Unused', 'Uploads', 'Links', 'WhatsApp', 'By Stitch'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 26, fontSize: 11 }}>{c}</T.Chip>)}</div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 7 }}>{ST_MOOD_MINE.map((it, i) => <StMoodTile key={i} T={T} it={it} w={116} on={i === 2} phone />)}</div></>
        : <>{ST_MOOD_ST.map(([name, n, imgs], gi) => <div key={name} style={{ marginBottom: 12 }}><div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}><StThread w={2} h={14} /><span style={{ fontFamily: T.fontDisplay, fontSize: 16, fontWeight: 600, color: T.ink }}>{name}</span><Meta T={T}>{n} items</Meta><span style={{ flex: 1 }} />{gi === 0 && <T.Chip outline icon="refresh-cw" style={{ height: 26, fontSize: 11 }}>Replenish</T.Chip>}</div><div style={{ display: 'flex', gap: 6, overflow: 'hidden' }}>{imgs.map((f, i) => <StTile key={f} T={T} src={ST_A + f + '.jpg'} w={86} h={92} r={10} meta={['Collected', 'Generated', 'Kept'][i % 3]} />)}</div></div>)}</>}
    </Body></>, stDock(T));
}
const ScreenStMoodMine = ({ T }) => <ScreenStMood T={T} tab="Mine" />;
const ScreenStMoodStitch = ({ T }) => <ScreenStMood T={T} tab="Stitch’s" />;
/* P9 History */
function ScreenStHistory({ T, sheet }) {
  return frameF(T, <><StHeader T={T} node="History" placeholder="Thread, template, day" tabs={[['By thread', 5], ['By day', null]]} tab="By day" />
    <Body style={{ padding: '8px 14px 120px' }}>{ST_HIST.map(([day, rows]) => <div key={day} style={{ marginBottom: 10 }}><Meta T={T} style={{ display: 'block', margin: '4px 0 6px', letterSpacing: '.06em', textTransform: 'uppercase' }}>{day}</Meta><div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, padding: '0 12px' }}>{rows.map((r, i) => <StHistRow key={r[0] + r[2]} T={T} r={r} phone first={i === 0} on={sheet && day === 'Today' && i === 0} />)}</div></div>)}</Body></>,
    sheet ? <>{scrimF(T)}<Sheet T={T} h={520} title="v7 · sweetheart, emerald velvet"><div style={{ display: 'flex', gap: 12 }}><StThumb T={T} src={ST_A + 'cut-06.jpg'} w={110} h={100} r={12} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12, color: T.ink2, lineHeight: 1.5 }}>Multicolour floral · cuts · today 10:41<br />Re-prompt of cell 6 · 8337 main + 5 refs · sales data on<div style={{ marginTop: 6 }}><StMark /></div></span></div><Sect T={T} style={{ margin: '12px 0 6px' }}>Share</Sect><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}><T.Chip outline icon="message-circle">WhatsApp packet</T.Chip><T.Chip outline icon="download">Export</T.Chip><T.Chip outline icon="image-plus">To moodboard</T.Chip></div><Sect T={T} style={{ margin: '12px 0 6px' }}>Use as design content</Sect><Meta T={T} style={{ display: 'block', whiteSpace: 'normal', lineHeight: 1.4 }}>The picture becomes the design-content image of a new master; Hub › Masters completes the rest.</Meta><div style={{ display: 'flex', gap: 6, marginTop: 8 }}><OutBtn T={T} icon="shirt" style={{ flex: 1, justifyContent: 'center' }}>New product master</OutBtn><OutBtn T={T} icon="layers" style={{ flex: 1, justifyContent: 'center' }}>New material master</OutBtn></div><T.Btn icon="flask-conical" style={{ width: '100%', height: 44, marginTop: 10 }}>Save as sample · S-0413</T.Btn></Sheet></> : stDock(T));
}
const ScreenStHistoryItem = ({ T }) => <ScreenStHistory T={T} sheet />;
/* P10 Memory · What works */
function ScreenStWorks({ T }) {
  return frameF(T, <><StHeader T={T} node="Memory" placeholder="Thread, sample no" tabs={[['What works', 5], ['Taste rules', 4]]} tab="What works" />
    <Body style={{ padding: '8px 14px 120px' }}>
      <div style={{ display: 'flex', gap: 8 }}><T.Kpi label="Designs saved" value="5" small /><T.Kpi label="Activated" value="3" small /><T.Kpi label="Working" value="2" tone="ok" small /></div>
      <div style={{ display: 'flex', gap: 8, alignItems: 'stretch', marginTop: 8, padding: '8px 10px', borderRadius: 14, background: T.surface2, border: `1px solid ${T.line}` }}><StThread h="auto" /><span style={{ fontFamily: T.fontDisplay, fontSize: 14, color: T.ink2, lineHeight: 1.35 }}>Not enough data yet · 3 of 5 rows have finished their read. Stitch reads only at five.</span></div>
      <div style={{ display: 'flex', gap: 5, margin: '10px 0 8px', overflow: 'hidden' }}>{['Working', 'Weak', 'Too early', 'Category'].map((c, i) => <T.Chip key={c} outline style={{ height: 26, fontSize: 11 }}>{c}{i === 3 && <Ic name="chevron-down" size={11} />}</T.Chip>)}</div>
      <div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, padding: '0 12px' }}>{ST_WORKS.map((r, i) => <StWorksRow key={r[2]} T={T} r={r} phone first={i === 0} />)}</div>
    </Body></>, stDock(T));
}
/* P11 Settings · Models */
function ScreenStSettings({ T }) {
  return frameF(T, <><StHeader T={T} node="Settings" noSearch tabs={[['Models'], ['Defaults'], ['Usage'], ['Context']]} tab="Models" />
    <Body style={{ padding: '8px 14px 120px' }}>
      <Meta T={T} style={{ display: 'block', whiteSpace: 'normal', lineHeight: 1.4, marginBottom: 6 }}>One model per template. Stitch keeps your choice per thread; change it here for every new thread.</Meta>
      <div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, padding: '0 12px' }}>{ST_MODELS.map((r, i) => <StModelRow key={r[0]} T={T} r={r} phone first={i === 0} />)}</div>
      <Sect T={T} style={{ margin: '12px 0 4px' }}>Providers</Sect>
      <div style={{ borderRadius: 16, background: T.surface, border: `1px solid ${T.line}`, padding: '0 12px' }}>{[['Image · provider A', 'key ok · 1,204 images'], ['Image · provider B', 'key ok · 41 images'], ['Video', 'no key yet · coming later']].map(([k, v], i) => <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 0', borderTop: i ? `1px solid ${T.line}` : 0 }}><span style={{ width: 8, height: 8, borderRadius: 4, background: i < 2 ? T.ok : T.ink3 }} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12.5, color: T.ink }}>{k}<Meta T={T} style={{ display: 'block' }}>{v}</Meta></span><Ic name="chevron-right" size={14} color={T.ink3} /></div>)}</div>
    </Body></>, stDock(T));
}

Object.assign(window, { ST_A, SP, spOf, STUDIO_NODES, ST_CUTS, stCut, ST_SHEET, ST_FLAT, ST_MAIN, ST_PRODUCTS, stP, ST_MATS, stM, ST_SAMPLES, ST_WIP, ST_CTX, ST_TRACKS, ST_THREADS, ST_TEMPLATES, ST_ZONES, ST_VERSIONS, ST_MSGS, ST_MOOD_MINE, ST_MOOD_ST, ST_HIST, ST_WORKS, ST_RULES, ST_MODELS, stImg, StThread, StMood, StMark, StSwatch, StTile, StThumb, StSeg, StSlider, StToggle, StToggleRow, StCaret, StBtn, StThumbs, StHead, StTray, StMsg, StPrompt, StChat, StZoneOverlay, StCanvas, StStrip, StVariations, StRow, StChipRow, StPane, ST_TUNER_TABS, StTuner, StSwipe, StTop, StNodes, StHeader, stDock, StHalfSheet, StTrackCard, StThreadRow, StMoodTile, ST_HIST_SRC, StHistRow, StVerdict, StWorksRow, StRuleRow, StModelRow, ST_SEL_TABS, StSelTabs, ST_SEL, StSelGrid, StSelTray, StCanvasCard, StCanvasScreen,
  ScreenStTracks, ScreenStChat, ScreenStCanvas, ScreenStZoneSheet, ScreenStTunerSheet, ScreenStPicker, ScreenStSwipe, ScreenStMoodMine, ScreenStMoodStitch, ScreenStHistory, ScreenStHistoryItem, ScreenStWorks, ScreenStSettings });
