/* NEW DRAFTS · Production · web, part C (8 Sep 2026): samples (board, deployed reading, new sample, lifecycle with free
   moves, receive a move, make product), costing, karigars (list, ledger, verification, new karigar, analytics), the
   locked state for roles without Production, and the board registration for the whole module. */

/* ── W23–W25 · Samples ── */
const SAMPLE_TABS = [['In designing', 4], ['Deployed, no production', 3], ['Activated', 1], ['Production started', 1]];
const SampleBar = ({ T, right, on }) => <PBar T={T} right={right}><T.Chip icon="search" outline>Sample no, category, karigar</T.Chip><Caret T={T}>Newest activity</Caret>{['Price TBD', 'Costing pending', 'High growth', '15-day read'].map((c, i) => <T.Chip key={c} on={i === on} outline={i !== on} x={i === on}>{c}</T.Chip>)}<AllFilters T={T} /><OutBtn T={T} small icon="plus">New sample</OutBtn></PBar>;
function SampleCardW({ T, s, on }) {
  return <div className="press" style={{ borderRadius: 18, overflow: 'hidden', background: T.surface, border: `1px solid ${on ? T.accentLine : T.line}`, boxShadow: on ? `0 0 0 2px ${T.accentSoft}` : 'none', minWidth: 0 }}>
    <div style={{ position: 'relative', height: 190, background: T.photoBg }}>{s.d.src ? <img src={s.d.src} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} /> : <span style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12, color: T.ink3 }}>No photo yet · add a sketch</span>}<span style={{ position: 'absolute', top: 8, left: 8, display: 'flex', gap: 4 }}><T.PhotoTag>Sample</T.PhotoTag>{s.chips.includes('High growth') && <T.PhotoTag>High growth</T.PhotoTag>}</span>{s.read && <span style={{ position: 'absolute', right: 8, top: 8 }}><ReadRing T={T} n={s.read} size={30} /></span>}</div>
    <div style={{ padding: '9px 11px 11px' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}><span style={{ whiteSpace: 'nowrap' }}><Num T={T} size={19}>{s.no}</Num></span><Meta T={T} style={{ minWidth: 0 }}>{s.cat}</Meta><span style={{ flex: 1 }} /><span style={{ fontFamily: T.fontSerif, fontSize: 14, color: T.ink3 }}>{s.target ? prMoney(s.target) : 'TBD'}</span></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 4 }}>{s.colours.map(c => <Dot key={c} n={c} />)}<Meta T={T}>{s.moves} moves · since {s.started.slice(0, 5)}</Meta></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}><Ic name="map-pin" size={12} color={T.ink3} /><Meta T={T} style={{ flex: 1, color: T.ink2 }}>{s.where}</Meta>{s.chips.filter(c => c !== 'High growth').slice(0, 1).map(c => <Pill key={c} T={T} tone={c.startsWith('Reading') ? 'blue' : 'warn'} small>{c}</Pill>)}</div>
    </div>
  </div>;
}
const SampleMovesPane = ({ T }) => <PPane style={{ padding: '10px 12px 12px' }}><div style={{ display: 'flex', gap: 10 }}><Thumb T={T} d={PR_D('4566')} w={48} h={60} r={11} /><span style={{ flex: 1 }}><Num T={T} size={20}>S-0412</Num><Meta T={T} style={{ display: 'block' }}>Lehenga · cape · Blush · target ₹12,995</Meta><Meta T={T} style={{ display: 'block', marginTop: 2, color: T.ink2 }}>cost so far ₹4,120 · money roles</Meta></span></div><div style={{ marginTop: 10, display: 'grid', gap: 6 }}>{PR_MOVES.map(mv => <div key={mv.n} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 8px', borderRadius: 10, background: T.surface2, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ width: 18, height: 18, borderRadius: 9, background: T.ink, color: T.bg, display: 'grid', placeItems: 'center', fontSize: 10, fontWeight: 600 }}>{mv.n}</span><span style={{ flex: 1 }}>{mv.proc} · {prK(mv.k).name.split(' ')[0]}</span><Pill T={T} tone={mv.back ? 'ok' : 'blue'} small>{mv.back ? 'back' : 'out'}</Pill></div>)}</div><Sect T={T}>References</Sect><div style={{ display: 'flex', gap: 6 }}>{['Pinterest board', 'client photo'].map(r => <span key={r} className="press" style={{ flex: 1, height: 56, borderRadius: 10, background: T.chipBg, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 11, color: T.ink2 }}>{r}</span>)}</div><span style={{ flex: 1 }} /><T.Btn small icon="chevron-right" style={{ height: 34 }}>Open sample</T.Btn></PPane>;
function WebPSamples({ T }) {
  return <PShell T={T} section="Samples" active="Samples" crumb={['Production', 'Samples', 'In designing']} paneTitle="S-0412 · moves" pane={<SampleMovesPane T={T} />} paneWidth={290}>
    <ViewTabs T={T} tabs={SAMPLE_TABS} active="In designing" />
    <PMain>
      <SampleBar T={T} right={<Meta T={T}>9 samples · 4 in designing · 3 on their 15-day read</Meta>} />
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0,1fr))', gap: 12 }}>{PR_SAMPLES.filter(s => s.tab === 'In designing').map((s, i) => <SampleCardW key={s.no} T={T} s={s} on={i === 0} />)}</div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 12, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="info" size={13} color={T.ink3} />A sample moves freely: any process, any order, any karigar, any material. When the piece is right it is deployed to the Catalogue for a 15-day reading; high growth turns it into a product and a first production order.</div>
    </PMain>
  </PShell>;
}
/* W23b · deployed samples · the 15-day reading */
function WebPSamplesDeployed({ T }) {
  const s = PR_SAMPLES.find(x => x.no === 'S-0409');
  return <PShell T={T} section="Samples" active="Samples" crumb={['Production', 'Samples', 'Deployed, no production']} paneTitle="S-0409 · reading day 9 of 15" pane={<PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', gap: 10 }}><Thumb T={T} d={s.d} w={48} h={60} r={11} /><span style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Num T={T} size={20}>S-0409</Num><ReadRing T={T} n={9} /></div><Meta T={T} style={{ display: 'block' }}>Saree · Lavender · deployed 30/08 · 1 pc in Catalogue</Meta><div style={{ marginTop: 4, display: 'flex', gap: 4 }}><Pill T={T} tone="ok" small>High growth</Pill></div></span></div>
    <div style={{ display: 'flex', gap: 6, marginTop: 10 }}><T.Kpi label="Views" value="212" sub="48 customers" small /><T.Kpi label="Cart adds" value="14" sub="6.6 %" small /><T.Kpi label="Orders" value="6" sub="waitlisted" small tone="ok" /></div>
    <Sect T={T} right={<Meta T={T}>daily · 15 days</Meta>}>Interest curve</Sect>
    <LineG T={T} series={[{ pts: [2, 5, 9, 14, 22, 31, 38, 47, 60], color: T.blue, width: 2 }]} w={290} h={64} area />
    <div style={{ marginTop: 10, padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><div style={{ fontWeight: 600, color: T.ink }}>Suggestion · start production · 24 pcs</div>6 waitlisted + growth rate · Lavender 16 · Sky 8 · recipe imports from the 4 moves · costing ₹2,860/pc</div>
    <div style={{ marginTop: 8, display: 'flex', gap: 6 }}><OutBtn T={T} small icon="rotate-ccw">Re-read 15 d</OutBtn><OutBtn T={T} small icon="archive">Drop</OutBtn></div>
    <span style={{ flex: 1 }} />
    <T.Btn small icon="package-check" style={{ height: 34, justifyContent: 'center' }}>Make product · first order</T.Btn>
  </PPane>} paneWidth={320}>
    <ViewTabs T={T} tabs={SAMPLE_TABS} active="Deployed, no production" />
    <PMain>
      <SampleBar T={T} on={3} right={<Meta T={T}>3 samples reading · one at day 15 re-reading</Meta>} />
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0,1fr))', gap: 12 }}>{PR_SAMPLES.filter(x => x.tab === 'Deployed, no production').map((x, i) => <SampleCardW key={x.no} T={T} s={x} on={i === 0} />)}<div style={{ borderRadius: 18, border: `1px dashed ${T.line2}`, padding: 14, display: 'flex', flexDirection: 'column', gap: 6, fontFamily: T.fontUI, fontSize: 12, color: T.ink2 }}><b style={{ color: T.ink }}>How a reading works</b><span>Day 0 · deployed with 1–2 pieces and a TBD or target price.</span><span>Days 1–15 · views, cart adds, waitlist orders counted daily.</span><span>Day 15 · high growth → product + first order; flat → re-read once or drop.</span></div></div>
    </PMain>
  </PShell>;
}
/* W23c · new sample */
function NewSamplePane({ T }) {
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Mono T={T}>S-0419 · auto</Mono><Meta T={T}>designer · Priya S</Meta></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><span className="press" style={{ width: 84, height: 104, borderRadius: 12, border: `1px dashed ${T.line2}`, background: T.chipBg, display: 'grid', placeItems: 'center', color: T.ink2 }}><span style={{ textAlign: 'center', fontFamily: T.fontUI, fontSize: 10.5 }}><Ic name="pen-tool" size={18} /><div>sketch or photo</div></span></span><span style={{ flex: 1, display: 'grid', gap: 8 }}><Field T={T} label="Working name" value="Organza kali · lemon" small /><Field T={T} label="Category" value="Lehenga" caret small /><Field T={T} label="Colours to try" value={<span style={{ display: 'inline-flex', gap: 6, alignItems: 'center' }}><Dot n="Lemon" />Lemon <Dot n="Pista" />Pista · + add</span>} small /></span></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label={<span>Target price<Lock T={T} /></span>} value="₹8,995 · or TBD" small /><Field T={T} label="Season · occasion" value="Festive 26" caret small /></div>
    <PrLab T={T} style={{ marginTop: 10 }}>References</PrLab>
    <div style={{ display: 'flex', gap: 6 }}>{['Pinterest link', 'client photo', '+ add'].map((r, i) => <span key={r} className="press" style={{ flex: 1, height: 48, borderRadius: 10, background: i === 2 ? 'transparent' : T.chipBg, border: i === 2 ? `1px dashed ${T.line2}` : 0, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 11, color: T.ink2 }}>{r}</span>)}</div>
    <Field T={T} label="Brief" ph="e.g. lighter than S-0418, keep the kali panels, no zari" style={{ marginTop: 8 }} />
    <PrLab T={T} style={{ marginTop: 10 }}>First move · optional</PrLab>
    <div style={{ display: 'flex', gap: 8 }}><Field T={T} label="Process" value="Dye" caret small /><Field T={T} label="Karigar" value="Rafiq Bhai · 71" caret small /></div>
    <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Starts In designing · every move is a challan with a gate token · costing accrues per move · money roles only</div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><OutBtn T={T} small>Save draft</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="flask-conical" style={{ height: 34 }}>Start sample</T.Btn></div>
  </PPane>;
}
function WebPSampleNew({ T }) {
  return <PShell T={T} section="Samples" active="Samples" crumb={['Production', 'Samples', 'New sample']} tab="New sample" paneTitle="New sample" pane={<NewSamplePane T={T} />} paneWidth={340}>
    <ViewTabs T={T} tabs={SAMPLE_TABS} active="In designing" />
    <PMain>
      <SampleBar T={T} right={<Meta T={T}>the board stays in view while the pane starts the sample</Meta>} />
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0,1fr))', gap: 12 }}>{PR_SAMPLES.filter(s => s.tab === 'In designing').map(s => <SampleCardW key={s.no} T={T} s={s} />)}</div>
    </PMain>
  </PShell>;
}
function NewMovePane({ T }) {
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <PaneTabs T={T} tabs={['New move', 'Receive']} on="New move" />
    <div style={{ display: 'flex', gap: 8 }}><Field T={T} label="Process · any" value="Latkan" caret small /><Field T={T} label="Colour" value={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Dot n="Blush" />Blush</span>} caret small w={100} /></div>
    <Field T={T} label="Karigar · any" value="Imtiaz Latkan · 66 · 2 jobs" caret small style={{ marginTop: 8 }} />
    <div style={{ display: 'flex', gap: 5, marginTop: 10 }}>{['Materials', 'This sample’s WIPs', 'Dye WIPs'].map((t, i) => <T.Chip key={t} on={i === 1} outline={i !== 1} style={{ height: 26, fontSize: 11 }}>{t}</T.Chip>)}</div>
    <div style={{ marginTop: 6, borderRadius: 12, border: `1px solid ${T.line}`, overflow: 'hidden' }}>{[['wip_stitch_S0412', 'sequin', 'Blush', 'expected back 10/09', true, '1 pc'], ['wip_emb_S0412', 'sequin', 'Blush', 'consumed in move 3', false, null], ['Mono net · C22 Blush', 'net', 'Blush', '0.1 m in hand', true, '0.1 m']].map(([n, tex, sh, meta, on, q]) => <MatRow key={n} T={T} m={{ name: n, shade: sh, tex, code: 'S-0412', group: 'WIP', lastIn: '02/09/26', sup: 'in hand', unit: 'pc', stock: on ? 1 : 0 }} compact tick added={on} right={on ? <span style={{ width: 56, height: 28, borderRadius: 8, border: `1px solid ${T.accentLine}`, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12, fontWeight: 600 }}>{q}</span> : <Meta T={T}>{meta}</Meta>} />)}</div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label={<span>Rate<Lock T={T} /></span>} ph="₹ / pc" small /><Field T={T} label="Due" value="14/09/26" icon="calendar" small w={110} /></div>
    <Field T={T} label="Note to karigar" ph="e.g. small latkans, match the sample" small style={{ marginTop: 8 }} />
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><GateToken T={T} n="on issue" /><span style={{ flex: 1 }} /><T.Btn small icon="arrow-up-right" style={{ height: 34 }}>Issue move 4</T.Btn></div>
  </PPane>;
}
function ReceiveMovePane({ T }) {
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <PaneTabs T={T} tabs={['New move', 'Receive']} on="Receive" />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><InOut T={T} t="receive" /><span style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600 }}>Move 3 · Stitching · Noor Tailors</span><span style={{ flex: 1 }} /><Meta T={T}>due 10/09</Meta></div>
    <PrLab T={T} style={{ marginTop: 10 }}>What came back</PrLab>
    <div style={{ display: 'flex', gap: 6 }}>{['Pieces', 'A WIP · name it', 'Material only'].map((t, i) => <T.Chip key={t} on={i === 0} outline={i !== 0} style={{ height: 26, fontSize: 11 }}>{t}</T.Chip>)}</div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Pieces" value={<T.Step v={1} />} w={120} small /><Field T={T} label="Lands as" value="wip_stitch_S0412 · sample piece" small /></div>
    <PrLab T={T} style={{ marginTop: 10 }}>Materials back to hand</PrLab>
    {[['m3', '0.4 m', 'of 8 m'], ['m5', '0 m', 'of 8 m']].map(([id, q, of]) => { const m = prMat(id); return <div key={id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderTop: `1px solid ${T.line}` }}><Swatch m={m} w={28} h={32} r={7} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12 }}>{prMatName(m)}<Meta T={T}> · {of}</Meta></span><span style={{ width: 60, height: 28, borderRadius: 8, border: `1px solid ${T.line2}`, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12, fontWeight: 600 }}>{q}</span></div>; })}
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Loss" value="0" small /><Field T={T} label="Rejected" value="0" small /><Field T={T} label={<span>Cost this move<Lock T={T} /></span>} value="₹2,200" small /></div>
    <Field T={T} label="Photo of the piece" value="capture · becomes the sample photo" icon="camera" small style={{ marginTop: 8 }} />
    <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Move turns Received · the piece appears in In hand · cost so far ₹4,120 · then: another move, deploy for reading, or make product</div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><GateToken T={T} n="GT-260908-030" /><span style={{ flex: 1 }} /><T.Btn small icon="arrow-down-left" style={{ height: 34 }}>Receive move 3</T.Btn></div>
  </PPane>;
}
function SampleMain({ T, onMove = 2 }) {
  const s = PR_SAMPLES[0];
  return <PMain>
    <PCard T={T}><div style={{ display: 'flex', gap: 14 }}>
      <div style={{ display: 'flex', gap: 6 }}><Thumb T={T} d={s.d} w={80} h={100} r={14} /><div style={{ display: 'grid', gap: 6 }}><span style={{ width: 47, height: 47, borderRadius: 10, background: T.chipBg, display: 'grid', placeItems: 'center' }}><Ic name="pen-tool" size={16} color={T.ink2} /></span><span className="press" style={{ width: 47, height: 47, borderRadius: 10, border: `1px dashed ${T.line2}`, display: 'grid', placeItems: 'center' }}><Ic name="camera" size={16} color={T.ink3} /></span></div></div>
      <span style={{ flex: 1, minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'baseline', gap: 10 }}><Num T={T} size={28}>S-0412</Num><Pill T={T} tone="warn" small>In designing</Pill><Pill T={T} tone="warn" small>Costing pending</Pill><span style={{ flex: 1 }} /><span style={{ fontFamily: T.fontSerif, fontSize: 16, color: T.ink3 }}>TBD · target ₹12,995</span></div><Meta T={T} style={{ display: 'block', marginTop: 3 }}>Lehenga · cape · Blush · started 20/08/26 · Priya S · references: Pinterest board, client photo · brief: lighter cape, keep the sequin border</Meta>
        <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><T.Kpi label="Moves" value="3" sub="Dye → Embroidery → Stitching" small /><T.Kpi label="Now" value="Stitching" sub="Noor Tailors · 3 d · due 10/09" small /><T.Kpi label="In hand" value="0.1 m · 0.05 kg" sub="net C22 · zari back" small /><T.Kpi label={<span>Cost so far<Lock T={T} /></span>} value="₹4,120" sub="dye 54 · emb 1,800 · stitch 2,200 + materials" small /></div></span>
    </div></PCard>
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12 }}><Sect T={T} style={{ margin: 0 }}>Moves</Sect><Meta T={T}>any process, any order, any material · the sequence below is only what happened</Meta><span style={{ flex: 1 }} /><span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>{['Dye', 'Embroidery', 'Stitching', '?'].map((p, i) => <React.Fragment key={p}><span style={{ height: 24, padding: '0 9px', borderRadius: 999, background: p === '?' ? 'transparent' : T.chipBg, border: p === '?' ? `1px dashed ${T.line2}` : 0, display: 'inline-grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 11 }}>{i + 1} · {p}</span>{i < 3 && <Ic name="arrow-right" size={12} color={T.ink3} />}</React.Fragment>)}</span></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0,1fr))', gap: 12, marginTop: 8 }}>{PR_MOVES.map((mv, i) => <MoveCard key={mv.n} T={T} mv={mv} on={i === onMove} />)}</div>
  </PMain>;
}
const SampleTabs = ({ T, right }) => <ViewTabs T={T} tabs={[['Lifecycle', null, 'git-commit-horizontal'], ['In hand', 3], ['Costing'], ['Reading']]} active="Lifecycle" back="Samples" eyebrow="S-0412 · Lehenga · cape" right={right} />;
function WebPSample({ T }) {
  return <PShell T={T} section="Samples" active="Samples" crumb={['Production', 'Samples', 'S-0412']} tab="Sample · S-0412" paneTitle="Move it on" pane={<NewMovePane T={T} />} paneWidth={330}>
    <SampleTabs T={T} right={<div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} small icon="calculator">Send to costing</OutBtn><OutBtn T={T} small icon="eye">Deploy for reading</OutBtn><OutBtn T={T} small icon="package-check">Make product</OutBtn></div>} />
    <SampleMain T={T} />
  </PShell>;
}
function WebPSampleReceive({ T }) {
  return <PShell T={T} section="Samples" active="Samples" crumb={['Production', 'Samples', 'S-0412', 'Receive move 3']} tab="Sample · S-0412" paneTitle="Receive · move 3" pane={<ReceiveMovePane T={T} />} paneWidth={330}>
    <SampleTabs T={T} right={<Meta T={T}>move 3 is back from Noor Tailors · 2 d early</Meta>} />
    <SampleMain T={T} onMove={2} />
  </PShell>;
}
function WebPFinalise({ T }) {
  const derived = [['Embroidery', 'Saleem Creation', '₹1,800/pc'], ['Stitching', 'Noor Tailors', '₹2,200/pc']];
  const mats = [['x', 'Mono net · C22 Blush · dye lot', 2.9, 'm', 'Embroidery', 'from DC-0036 · 3 m issued, 0.1 m loss'], ['m7', null, 0.05, 'kg', 'Embroidery', ''], ['m3', null, 8, 'm', 'Stitching', '0.4 m came back → avg 7.6 ?'], ['m5', null, 8, 'm', 'Stitching', '']];
  return <PShell T={T} section="Samples" active="Samples" crumb={['Production', 'Samples', 'S-0412', 'Make product']} tab="Sample · S-0412" paneTitle="S-0412 · moves" pane={<PPane style={{ padding: '10px 12px 12px' }}><Meta T={T}>for reference while you edit</Meta><div style={{ marginTop: 8, display: 'grid', gap: 8 }}>{PR_MOVES.map(mv => <MoveCard key={mv.n} T={T} mv={mv} phone money />)}</div></PPane>} paneWidth={330}>
    <SampleTabs T={T} right={<Meta T={T}>nothing is written until Create · S-0412 stays as the reference</Meta>} />
    <PMain>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
        <PCard T={T}><StepHead T={T} n={1} title="Product master" sub="number, category, colours, tags" /><div style={{ display: 'flex', gap: 10 }}><Thumb T={T} d={PR_D('4566')} w={56} h={70} r={12} /><div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}><Field T={T} label="Design number" value="4566 · next free" small /><Field T={T} label="Category" value="Lehenga" caret small /><Field T={T} label="Colours" value="Blush · + add" small /><Field T={T} label="Photo" value="move 3 piece · primary" caret small /><Field T={T} label="Category tags" value="cape · sequin · net" caret small /><Field T={T} label="General tags" value="festive · new" caret small /></div></div></PCard>
        <PCard T={T}><StepHead T={T} n={2} title="Process sequence · from the moves" sub="reorder, remove, add · the last is Final" /><div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>{derived.map(([p, k, r], i) => <React.Fragment key={p}><span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, height: 40, padding: '0 10px 0 6px', borderRadius: 12, background: T.surface2, border: `1px solid ${i === 1 ? T.accentLine : T.line2}` }}><Ic name="grip-vertical" size={13} color={T.ink3} /><span style={{ width: 22, height: 22, borderRadius: 11, background: T.ink, color: T.bg, display: 'grid', placeItems: 'center', fontSize: 11, fontWeight: 600 }}>{i + 1}</span><span style={{ fontFamily: T.fontUI, fontSize: 13, fontWeight: 500 }}>{p}</span><Meta T={T}>{k.split(' ')[0]} · {r}<Lock T={T} /></Meta>{i === 1 && <Pill T={T} tone="muted" small>Final</Pill>}<Ic name="x" size={12} color={T.ink3} /></span>{i < 1 && <Ic name="arrow-right" size={14} color={T.ink3} />}</React.Fragment>)}<span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 30, padding: '0 10px', borderRadius: 999, border: `1px dashed ${T.line2}`, fontFamily: T.fontUI, fontSize: 12, color: T.ink2 }}><Ic name="plus" size={12} />Latkan</span></div><Meta T={T} style={{ display: 'block', marginTop: 8 }}>Move 1 (Dye) is not a process: it becomes the dye-ledger cut order in the recipe (Mono net → C22 Blush) and the lot is a dye WIP material.</Meta></PCard>
      </div>
      <PCard T={T} style={{ marginTop: 12, padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '12px 14px 0' }}><StepHead T={T} n={3} title="Materials & averages · issued ÷ 1 pc" sub="edit any average before it becomes the recipe · returns are suggested, not applied" right={<Meta T={T}>4 rows · 1 dye lot</Meta>} /></div>
        <Tbl T={T} cols={[['Material · shade'], ['Issued in the sample', 130, 'left'], ['Avg / pc', 80], ['Unit', 40, 'left'], ['Feeds', 110, 'left'], ['Note', 220, 'left']]} rows={mats.map(([id, nm, q, u, p, note]) => { const m = id === 'x' ? { tex: 'net', shade: 'Blush', dye: true, code: 'MN-C22' } : prMat(id); return [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Swatch m={m} w={30} h={36} r={7} /><span>{nm || prMatName(m)} <Meta T={T}>{m.code}</Meta></span></span>, `${id === 'x' ? 3 : q} ${u} for 1 pc`, <span style={{ display: 'inline-block', width: 62, height: 28, lineHeight: '26px', borderRadius: 8, border: `1px solid ${T.accentLine}`, textAlign: 'center', fontWeight: 600 }}>{q}</span>, u, <Pill T={T} tone="muted" small>{p}</Pill>, note ? <Meta T={T}>{note}</Meta> : <Meta T={T}>—</Meta>]; })} />
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10, padding: '10px 14px' }}>{[['BOM · Embroidery', 'wip_emb_4566_blush', ['Mono net · C22 · 2.9 m', 'Zari thread · 0.05 kg']], ['BOM · Stitching · finished good', '4566_blush', ['wip_emb_4566_blush · 1 pc', 'Santoon · Peach · 8 m', 'Cancan · 8 m']], ['Costing draft · money roles', '', ['materials ₹1,031 · jobs ₹4,000', 'unit cost ₹5,031 · 40 % → ₹8,385', 'target was ₹12,995 · margin 61 %']]].map(([t, w, ls]) => <div key={t} style={{ padding: 10, borderRadius: 14, background: T.surface2, border: `1px solid ${T.line}` }}><div style={{ display: 'flex', alignItems: 'baseline' }}><span style={{ fontFamily: T.fontUI, fontSize: 10.5, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>{t}</span><span style={{ flex: 1 }} /><Mono T={T} size={10.5}>{w}</Mono></div>{ls.map(l => <Meta T={T} key={l} style={{ display: 'block', marginTop: 4, color: T.ink }}>{l}</Meta>)}</div>)}</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 14px', borderTop: `1px solid ${T.line}` }}><Meta T={T}>Creates: product 4566, recipe 1 colour × 2 processes = 2 WIP BOMs + 1 cut order, a costing draft · opens Process setting for review</Meta><span style={{ flex: 1 }} /><OutBtn T={T}>Back to sample</OutBtn><T.Btn small icon="git-branch" style={{ height: 38 }}>Create product · open Process setting</T.Btn></div>
      </PCard>
    </PMain>
  </PShell>;
}

/* ── W26 · Costing ── */
const COSTS = [['2798', 'PO-1187', 2058, 40, 3430, ['Pending approval'], 'Completed'], ['3661', 'PO-1174', 920, 35, 1415, [], 'Completed'], ['4566', 'S-0412', 5031, 40, 8385, ['Missing rate · Latkan'], 'Incomplete'], ['6002', 'PO-1192', 1140, 35, 1754, ['Below target margin'], 'Incomplete'], ['2006', 'PO-1201', 1310, 35, 2015, ['Sync failed'], 'Completed'], ['S-0418', null, 640, 40, null, ['Not priced'], 'Not priced']];
function WebPCosting({ T }) {
  return <PShell T={T} section="Costing" active="Costing" crumb={['Production', 'Costing', 'Completed']} paneTitle="2798 · cost breakdown" pane={<PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', gap: 10 }}><Thumb T={T} d={PR_D('2798')} w={48} h={60} r={11} /><span style={{ flex: 1 }}><Num T={T} size={20}>2798</Num><Meta T={T} style={{ display: 'block' }}>PO-1187 · 85 pcs · last job rate set 12/08 → complete</Meta><div style={{ marginTop: 4 }}><Pill T={T} tone="blue" small>Pending approval · PM or admin</Pill></div></span></div>
    <Sect T={T} right={<Meta T={T}>avg × purchase-rate avg</Meta>}>Materials · ₹1,498</Sect>
    {[['Mono net · dye lot', '0.5 m × ₹62 + dye ₹18', 40], ['Zari thread', '0.04 kg × ₹1,850', 74], ['Cancan', '8 m × ₹28', 224], ['Haddi', '2 m × ₹9', 18], ['Rasgulla', '5 m × ₹35', 175], ['Santoon', '8 m × ₹62', 496], ['BKS 41 choli set', '1 pc × ₹471', 471]].map(r => <div key={r[0]} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 28, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[0]}<Meta T={T}> · {r[1]}</Meta></span><span style={{ fontVariantNumeric: 'tabular-nums' }}>₹{r[2]}</span></div>)}
    <Sect T={T}>Job rates per pc · ₹560</Sect>
    {[['Touching', 40], ['Embroidery', 200], ['Latkan', 0], ['Stitching', 320]].map(r => <div key={r[0]} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 26, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ flex: 1 }}>{r[0]}</span>{r[1] ? <span>₹{r[1]}</span> : <Pill T={T} tone="warn" small>not assigned · ₹0</Pill>}</div>)}
    <div style={{ marginTop: 8, padding: '8px 12px', borderRadius: 14, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12.5 }}><div style={{ display: 'flex' }}><span style={{ flex: 1 }}>Unit cost</span><b>₹2,058</b></div><div style={{ display: 'flex', marginTop: 3 }}><span style={{ flex: 1 }}>Gross margin · Lehenga default</span><span>40 %</span></div><div style={{ display: 'flex', marginTop: 3, alignItems: 'baseline' }}><span style={{ flex: 1 }}>Recommended · cost ÷ 0.6</span><span style={{ fontFamily: T.fontSerif, fontSize: 20, fontWeight: 600 }}>₹3,430</span></div></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Your price" value="₹3,495" small /><Field T={T} label="Margin at that" value="41.1 % · above default" small /></div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} small icon="history">Past prices</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="check" style={{ height: 34 }}>Approve ₹3,495 · sync</T.Btn></div>
  </PPane>}>
    <ViewTabs T={T} tabs={[['Completed', 3], ['Incomplete', 2], ['Not priced', 1], ['Past', 118]]} active="Completed" right={<Meta T={T}>until approved the catalogue shows TBD · money roles only</Meta>} />
    <PMain>
      <PBar T={T} right={<div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><Meta T={T}>default margins</Meta>{[['Lehenga', 40], ['Saree', 35], ['Blouse', 45]].map(([c, m]) => <T.Chip key={c} outline style={{ height: 28 }}>{c} {m} %</T.Chip>)}<OutBtn T={T} small icon="pencil">Edit · admin</OutBtn></div>}><T.Chip icon="search" outline>Design, sample, order</T.Chip><Caret T={T}>Oldest unpriced</Caret>{['Pending approval', 'Missing rate', 'Below target margin', 'Sync failed'].map(c => <T.Chip key={c} outline>{c}</T.Chip>)}</PBar>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0,1fr))', gap: 12 }}>{COSTS.map(([c, ref, cost, mg, price, chips, tab], i) => <div key={c} className="press" style={{ display: 'flex', gap: 12, padding: 12, borderRadius: 18, background: T.surface, border: `1px solid ${i === 0 ? T.accentLine : T.line}`, boxShadow: i === 0 ? `0 0 0 2px ${T.accentSoft}` : 'none', minWidth: 0 }}><Thumb T={T} d={c.startsWith('S-') ? (PR_SAMPLES.find(s => s.no === c) || {}).d : PR_D(c)} w={60} h={76} r={12} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}><Num T={T} size={20}>{c}</Num>{ref && <Mono T={T} size={11}>{ref}</Mono>}<span style={{ flex: 1 }} /><Pill T={T} tone={tab === 'Completed' ? 'ok' : 'muted'} small>{tab}</Pill></div><div style={{ display: 'flex', gap: 12, marginTop: 6, fontFamily: T.fontUI, fontSize: 12 }}><span><Meta T={T} style={{ display: 'block' }}>unit cost</Meta><b>{prMoney(cost)}</b></span><span><Meta T={T} style={{ display: 'block' }}>margin</Meta><b>{mg} %</b></span><span><Meta T={T} style={{ display: 'block' }}>recommended</Meta><b style={{ fontFamily: T.fontSerif, fontSize: 15 }}>{price ? prMoney(price) : 'TBD'}</b></span></div><div style={{ display: 'flex', gap: 4, marginTop: 8, flexWrap: 'wrap' }}>{chips.map(x => <Pill key={x} T={T} tone={/Sync/.test(x) ? 'danger' : /Pending/.test(x) ? 'blue' : 'warn'} fill={/Sync/.test(x)} small>{x}</Pill>)}</div></span></div>)}</div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 12, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="info" size={13} color={T.ink3} />Costing completes when the last job rate is set; unit cost = materials at average purchase rate + job rates; recommended price = cost ÷ (1 − margin). Approval syncs the price to the catalogue and accounts.</div>
    </PMain>
  </PShell>;
}

/* ── W27 · Karigars ── */
const KAR_TABS = [['All', 27], ['Delayed jobs', 4], ['Payment due', 5], ['Capacity risk', 2], ['Analytics', null, 'bar-chart-3']];
const KarBar = ({ T, right, on }) => <PBar T={T} right={right}><T.Chip icon="search" outline>Name, skill, phone</T.Chip><Caret T={T}>Reliability</Caret>{['Delayed jobs', 'Material balance', 'Capacity risk', 'Payment due', 'Unverified'].map((c, i) => <T.Chip key={c} on={i === on} outline={i !== on} x={i === on}>{c}</T.Chip>)}<AllFilters T={T} /><OutBtn T={T} small icon="user-plus">New karigar</OutBtn></PBar>;
const KarHead = ({ T, k }) => <><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ fontFamily: T.fontDisplay, fontSize: 20, fontWeight: 600, flex: 1 }}>{k.name}</span><CallChip T={T}>{k.phone}</CallChip></div>
  <div style={{ display: 'flex', gap: 5, marginTop: 4, alignItems: 'center' }}>{k.skills.map(s => <Pill key={s} T={T} tone="muted" small>{s}</Pill>)}<Meta T={T}>· Delhi · since 2019</Meta></div>
  <div style={{ display: 'flex', gap: 6, marginTop: 10 }}><T.Kpi label="Score" value={k.score} small tone={k.score >= 70 ? 'ok' : undefined} /><T.Kpi label="On time" value={k.onTime + ' %'} small /><T.Kpi label="Capacity" value={k.cap + '/d'} small /></div></>;
function KarigarPane({ T, k }) {
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <KarHead T={T} k={k} />
    <PaneTabs T={T} tabs={['Jobs', 'Material', 'Ledger', 'Verify']} on="Jobs" />
    {PR_JOBS.filter(j => j.k === k.id).slice(0, 4).map(j => <div key={j.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderTop: `1px solid ${T.line}` }}><Thumb T={T} d={j.d} w={26} h={32} r={7} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12 }}><b>{j.code}</b> · {j.proc}<Meta T={T} style={{ display: 'block' }}>{j.o.no} · {j.recd}/{j.planned} · ₹{j.rate}/pc<Lock T={T} /></Meta></span><JobChip T={T} s={j.state} small /></div>)}
    <Sect T={T} right={<Meta T={T}>speed · reliability</Meta>}>Last 12 weeks</Sect>
    <LineG T={T} series={[{ pts: [60, 64, 58, 70, 72, 68, 75, 74, 80, 78, 82, 78], color: T.accent, width: 2 }, { pts: [70, 70, 66, 72, 74, 71, 76, 78, 80, 79, 81, 80], color: T.ok, width: 2, dash: true }]} w={290} h={64} area />
    <span style={{ flex: 1 }} />
    <div style={{ padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><div style={{ display: 'flex' }}><span style={{ flex: 1 }}>Due now · 30-day term<Lock T={T} /></span><b>{prMoney(k.due)}</b></div><div style={{ display: 'flex', marginTop: 2 }}><span style={{ flex: 1, color: T.ink2 }}>Material with them · at cost</span><span>{prMoney(k.bal)}</span></div></div>
  </PPane>;
}
const KarTable = ({ T, on = 1, rows = PR_KARIGARS }) => { const G = ({ v }) => <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><span style={{ width: 40, height: 6, borderRadius: 3, background: T.line2, overflow: 'hidden' }}><span style={{ display: 'block', width: v + '%', height: 6, background: v >= 70 ? T.ok : T.warn }} /></span><b>{v}</b></span>; return <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} onRow={on} cols={[['Karigar'], ['Skills', 96, 'left'], ['Score', 66, 'left'], ['Jobs', 36], ['With them', 92, 'left'], [<span>Due ₹<Lock T={T} /></span>, 68], ['Flags', 176, 'left']]} rows={rows.map(k => [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, minWidth: 0 }}><span style={{ width: 28, height: 28, borderRadius: 8, background: T.ink, color: T.bg, display: 'grid', placeItems: 'center', fontFamily: T.fontDisplay, fontSize: 12, fontWeight: 600, flex: 'none' }}>{k.name.split(' ').slice(0, 2).map(w => w[0]).join('')}</span><span style={{ minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{k.name}<Meta T={T} style={{ display: 'block' }}>{k.onTime} % on time · {k.phone}</Meta></span></span>, <span style={{ display: 'inline-flex', gap: 4, overflow: 'hidden' }}>{k.skills.slice(0, 1).map(s => <Pill key={s} T={T} tone="muted" small>{s}</Pill>)}{k.skills.length > 1 && <Meta T={T}>+{k.skills.length - 1}</Meta>}</span>, <G v={k.score} />, k.jobs, k.withThem, k.due ? prMoney(k.due) : '—', <span style={{ display: 'inline-flex', gap: 4, overflow: 'hidden' }}>{[k.onTime < 70 && ['Delayed', 'warn'], k.bal > 90000 && ['Material', 'warn'], k.due > 40000 && ['Due', 'blue'], k.jobs >= 6 && ['Capacity', 'danger'], k.id === 'k2' && ['1 unverified', 'warn']].filter(Boolean).slice(0, 2).map(([l, t]) => <Pill key={l} T={T} tone={t} small>{l}</Pill>)}</span>])} /></PCard>; };
function WebPKarigars({ T }) {
  return <PShell T={T} section="Karigars" active="Karigars" crumb={['Production', 'Karigars']} paneTitle="Saleem Creation" pane={<KarigarPane T={T} k={prK('k2')} />} paneWidth={320}>
    <ViewTabs T={T} tabs={KAR_TABS} active="All" />
    <PMain><KarBar T={T} right={<Meta T={T}>27 karigars · ₹1.1L due this week · money for manager roles</Meta>} /><KarTable T={T} /></PMain>
  </PShell>;
}
/* W27b · ledger: dues fall per piece received, vouchers, payments */
function LedgerPane({ T, k }) {
  const rows = [['08/09/26', 'MR-00121 · 3 pcs Peach · unverified', null, 'held'], ['06/09/26', 'MR-00119 · 12 pcs Purple × ₹200', 2400, 'OE/MR/33'], ['04/09/26', 'MR-00118 · 15 pcs Sky × ₹200', 3000, 'OE/MR/31'], ['28/08/26', 'Payment · NEFT', -25000, 'PAY/0412'], ['22/08/26', 'PO-1155 · 30 pcs × ₹90', 2700, 'OE/MR/27']];
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <KarHead T={T} k={k} />
    <PaneTabs T={T} tabs={['Jobs', 'Material', 'Ledger', 'Verify']} on="Ledger" />
    <div style={{ display: 'flex', gap: 6 }}><T.Kpi label={<span>Due · 30 d<Lock T={T} /></span>} value={prMoney(k.due)} small tone="ok" /><T.Kpi label="Overdue" value="₹0" small /><T.Kpi label="Paid FY" value="₹3.2L" small /></div>
    <div style={{ marginTop: 8, flex: 1, minHeight: 0, overflow: 'hidden' }}>{rows.map((r, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 36, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><Meta T={T}>{r[0].slice(0, 5)}</Meta><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[1]}</span>{r[2] == null ? <Pill T={T} tone="warn" small>{r[3]}</Pill> : <><Mono T={T} size={10} color={T.ink3}>{r[3]}</Mono><span style={{ fontWeight: 600, color: r[2] < 0 ? T.ok : T.ink, fontVariantNumeric: 'tabular-nums' }}>{r[2] < 0 ? '−' : '+'}{prMoney(Math.abs(r[2]))}</span></>}</div>)}</div>
    <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Dues fall on each verified receive · the voucher is pushed to accounts on verify · payment vouchers are raised here and paid from accounts</div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><OutBtn T={T} small icon="file-text">Statement</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="wallet" style={{ height: 34 }}>Raise payment · ₹41,000</T.Btn></div>
  </PPane>;
}
function WebPKarigarLedger({ T }) {
  return <PShell T={T} section="Karigars" active="Karigars" crumb={['Production', 'Karigars', 'Payment due']} paneTitle="Saleem Creation · ledger" pane={<LedgerPane T={T} k={prK('k2')} />} paneWidth={330}>
    <ViewTabs T={T} tabs={KAR_TABS} active="Payment due" />
    <PMain><KarBar T={T} on={3} right={<Meta T={T}>5 karigars · ₹1,10,400 due this week · 30-day term</Meta>} /><KarTable T={T} on={0} rows={PR_KARIGARS.filter(k => k.due)} />
      <Sect T={T} right={<Meta T={T}>this week</Meta>}>Payments planned</Sect>
      <div style={{ display: 'flex', gap: 10 }}>{[['Noor Tailors', 58800, 'Wed'], ['Saleem Creation', 41000, 'Thu'], ['Meena Touching Works', 6200, 'Fri'], ['Rafiq Bhai', 4400, 'Fri']].map(([n, v, d]) => <PCard key={n} T={T} alt style={{ flex: 1 }}><Meta T={T}>{d}</Meta><div style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, marginTop: 2 }}>{n}</div><div style={{ fontFamily: T.fontSerif, fontSize: 18, fontWeight: 600, marginTop: 2 }}>{prMoney(v)}</div></PCard>)}</div>
    </PMain>
  </PShell>;
}
/* W27c · verification: entries the karigar recorded on his phone (jobber) wait for the floor to confirm */
function WebPKarigarVerify({ T }) {
  const rows = [['MR-00121', 'k2', '2798', 'PO-1187 · Embroidery', 'receive · 3 pcs Peach', '08/09 11:20', 'photo'], ['MI-00218', 'k4', '3661', 'PO-1174 · Stitching', 'hand-over · 8 pcs Pista', '08/09 09:05', 'photo'], ['MR-00123', 'k7', '1457', 'PO-1163 · Ready production', 'receive · 6 pcs Firozi', '07/09 18:40', 'no photo']];
  return <PShell T={T} section="Karigars" active="Karigars" crumb={['Production', 'Karigars', 'Unverified entries']} paneTitle="MR-00121 · verify" pane={<PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><InOut T={T} t="receive" /><Mono T={T}>MR-00121</Mono><Pill T={T} tone="warn" small>Unverified</Pill><span style={{ flex: 1 }} /><Meta T={T}>08/09 11:20</Meta></div>
    <div style={{ display: 'flex', gap: 10, marginTop: 10 }}><Thumb T={T} d={PR_D('2798')} w={48} h={60} r={11} /><span style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}><Num T={T} size={20}>2798</Num><Mono T={T} size={11.5}>PO-1187</Mono></div><Meta T={T} style={{ display: 'block' }}>Embroidery · recorded by Saleem Creation on his phone</Meta><div style={{ marginTop: 4 }}><KarigarPill T={T} name="Saleem Creation" score={78} /></div></span></div>
    <div style={{ marginTop: 10, height: 120, borderRadius: 12, background: T.chipBg, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 11.5, color: T.ink3 }}>photo from the karigar · 3 pcs Peach</div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><Field T={T} label="He says" value="3 pcs · Peach" small /><Field T={T} label="Counted" value="3" small w={80} /><Field T={T} label="Settles" value="none · over-receive" caret small /></div>
    <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.warn + '1F', border: `1px solid ${T.warn}55`, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink }}>Peach was never issued to Saleem. Verifying books the pieces as excess and asks the PM; rejecting sends him a message and keeps the ledger unchanged.</div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><OutBtn T={T} small icon="x">Reject · message</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="badge-check" style={{ height: 34 }}>Verify · gate token</T.Btn></div>
  </PPane>} paneWidth={330}>
    <ViewTabs T={T} tabs={KAR_TABS} active="All" />
    <PMain><KarBar T={T} on={4} right={<Meta T={T}>3 entries wait · karigars record on their phone, the floor confirms</Meta>} />
      <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} onRow={0} cols={[['Entry', 90, 'left'], ['Karigar', 150, 'left'], ['Order · job'], ['What', 170, 'left'], ['When', 90, 'left'], ['Photo', 70, 'left'], ['', 150, 'left']]} rows={rows.map(r => { const k = prK(r[1]); return [<Mono T={T} size={11.5}>{r[0]}</Mono>, k.name, <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><DesignChip T={T} code={r[2]} small /><Meta T={T}>· {r[3]}</Meta></span>, r[4], r[5], r[6] === 'photo' ? <Ic name="image" size={14} color={T.ink2} /> : <Pill T={T} tone="warn" small>none</Pill>, <span style={{ display: 'inline-flex', gap: 6 }}><Pill T={T} tone="warn" small>Unverified</Pill><span className="press" style={{ fontFamily: T.fontUI, fontSize: 11.5, fontWeight: 600, color: T.accent }}>Verify</span></span>]; })} /></PCard>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 12, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="info" size={13} color={T.ink3} />An unverified entry shows on the job with an Unverified pill and raises no due, no voucher and no gate token until the floor verifies it.</div>
    </PMain>
  </PShell>;
}
/* W27d · new karigar */
function WebPKarigarNew({ T }) {
  return <PShell T={T} section="Karigars" active="Karigars" crumb={['Production', 'Karigars', 'New karigar']} tab="New karigar" paneTitle="New karigar" pane={<PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', gap: 8 }}><span className="press" style={{ width: 64, height: 64, borderRadius: 14, border: `1px dashed ${T.line2}`, background: T.chipBg, display: 'grid', placeItems: 'center', color: T.ink2 }}><Ic name="camera" size={18} /></span><span style={{ flex: 1, display: 'grid', gap: 8 }}><Field T={T} label="Name · firm" value="Farhan Zari Works" small /><Field T={T} label="Phone · WhatsApp" value="98xxx xxxxx" small /></span></div>
    <PrLab T={T} style={{ marginTop: 10 }}>Skills · processes he can take</PrLab>
    <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>{PR_SEQ_PROC.map(([p], i) => <T.Chip key={p} on={p === 'Embroidery' || p === 'Latkan'} outline={!(p === 'Embroidery' || p === 'Latkan')} style={{ height: 26, fontSize: 11 }}>{p}</T.Chip>)}</div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><Field T={T} label="Capacity · pcs/day" value="30" small w={110} /><Field T={T} label="City · area" value="Delhi · Seelampur" caret small /></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Payment terms" value="30 days" caret small /><Field T={T} label="Firm · GST" value="unregistered" caret small /></div>
    <PrLab T={T} style={{ marginTop: 10 }}>Rate card <Lock T={T} /> · optional, per process</PrLab>
    <div style={{ borderRadius: 12, border: `1px solid ${T.line}`, overflow: 'hidden' }}>{[['Embroidery', '₹180–240 / pc'], ['Latkan', '₹55–70 / pc']].map(([p, r], i) => <div key={p} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 8px', borderTop: i ? `1px solid ${T.line}` : 0, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ flex: 1 }}>{p}</span><span style={{ width: 120, height: 28, borderRadius: 8, border: `1px solid ${T.line2}`, display: 'grid', placeItems: 'center' }}>{r}</span></div>)}</div>
    <Meta T={T} style={{ display: 'block', marginTop: 8 }}>bank details are entered by accounts in Hub › Masters · the score starts at 70 and moves with tranches</Meta>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><OutBtn T={T} small icon="message-circle">Send app invite</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="user-plus" style={{ height: 34 }}>Add karigar</T.Btn></div>
  </PPane>} paneWidth={330}>
    <ViewTabs T={T} tabs={KAR_TABS} active="All" />
    <PMain><KarBar T={T} right={<Meta T={T}>the list stays · the pane adds the karigar</Meta>} /><KarTable T={T} on={null} /></PMain>
  </PShell>;
}
/* W27e · analytics: speed, reliability, load */
function WebPKarigarAnalytics({ T }) {
  const ks = PR_KARIGARS.slice(0, 6);
  return <PShell T={T} section="Karigars" active="Karigars" crumb={['Production', 'Karigars', 'Analytics']} paneTitle="Saleem Creation" pane={<KarigarPane T={T} k={prK('k2')} />} paneWidth={300}>
    <ViewTabs T={T} tabs={KAR_TABS} active="Analytics" right={<PTabs T={T} tabs={['30 d', '90 d', 'FY']} on="90 d" />} />
    <PMain>
      <div style={{ display: 'flex', gap: 10 }}><T.Kpi label="On-time tranches" value="76 %" sub="of 118 · 90 d" /><T.Kpi label="Avg days late" value="3.4" sub="when late" tone="danger" /><T.Kpi label="Pcs received" value="4,120" sub="90 d · 27 karigars" /><T.Kpi label="Rejections" value="1.8 %" sub="rework rate" /><T.Kpi label="Material with karigars" value="₹3.1L" sub="at cost · money roles" /></div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginTop: 12 }}>
        <PCard T={T}><Sect T={T} style={{ margin: '0 0 8px' }} right={<Meta T={T}>% of tranches met · 90 d</Meta>}>Reliability by karigar</Sect><BarsV T={T} data={ks.map(k => k.onTime)} labels={ks.map(k => k.name.split(' ')[0])} w={380} h={120} color={T.blue} /></PCard>
        <PCard T={T}><Sect T={T} style={{ margin: '0 0 8px' }} right={<Meta T={T}>pcs per day vs capacity</Meta>}>Load this week</Sect>{ks.map(k => { const load = Math.round(k.cap * (k.jobs >= 6 ? 1.15 : k.jobs >= 4 ? .8 : .45)); return <div key={k.id} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 26, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ width: 90, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{k.name.split(' ')[0]}</span><span style={{ flex: 1, height: 8, borderRadius: 4, background: T.line, overflow: 'hidden' }}><span style={{ display: 'block', width: Math.min(100, load / k.cap * 100) + '%', height: 8, background: load > k.cap ? T.danger : T.blue }} /></span><Meta T={T} style={{ width: 70, textAlign: 'right' }}>{load} / {k.cap}</Meta></div>; })}</PCard>
        <PCard T={T}><Sect T={T} style={{ margin: '0 0 8px' }} right={<Meta T={T}>weekly · all karigars</Meta>}>Pieces received</Sect><LineG T={T} series={[{ pts: [280, 310, 260, 340, 360, 330, 390, 370, 410, 380, 420, 400], color: T.accent, width: 2 }]} w={380} h={90} area /></PCard>
        <PCard T={T}><Sect T={T} style={{ margin: '0 0 8px' }} right={<Meta T={T}>why tranches slipped · 90 d</Meta>}>Delay reasons</Sect><div style={{ display: 'flex', gap: 14, alignItems: 'center' }}><Donut T={T} parts={[{ v: 38, color: T.danger }, { v: 27, color: T.warn }, { v: 20, color: T.blue }, { v: 15, color: T.line2 }]} size={96} thick={14} center="28" /><Legend T={T} items={[['Material short', T.danger, '38 %'], ['Karigar late', T.warn, '27 %'], ['Previous job late', T.blue, '20 %'], ['Rework', T.line2, '15 %']]} /></div></PCard>
      </div>
    </PMain>
  </PShell>;
}

/* ── W28 · Production locked for this role ── */
function WebPLocked({ T }) {
  return <WebShell3 T={T} module="Production" crumb={['Production']} section="Production" seg={PROD_SEG} active={null} tabs={PR_TABS('Production')} searchWidth={132}>
    <div style={{ flex: 1, display: 'grid', placeItems: 'center', padding: 24 }}><div style={{ width: 420, padding: 28, borderRadius: 24, background: T.surface, border: `1px solid ${T.line}`, textAlign: 'center' }}><span style={{ width: 56, height: 56, borderRadius: 28, background: T.chipBg, display: 'inline-grid', placeItems: 'center' }}><Ic name="lock" size={22} color={T.ink2} /></span><div style={{ fontFamily: T.fontDisplay, fontSize: 22, fontWeight: 600, marginTop: 12 }}>Production is not in your role</div><Meta T={T} style={{ display: 'block', marginTop: 6, whiteSpace: 'normal', lineHeight: 1.5 }}>Sales executive · you can see production status on a design in the Catalogue (expected date, pieces coming). Job cards, orders, rates and karigars need the Production or Manager role.</Meta><div style={{ display: 'flex', gap: 8, justifyContent: 'center', marginTop: 16 }}><OutBtn T={T} icon="layout-grid">Back to Catalogue</OutBtn><T.Btn icon="send" style={{ height: 36 }}>Ask the admin for access</T.Btn></div><Meta T={T} style={{ display: 'block', marginTop: 12 }}>the request lands in Home › Approvals for the admin</Meta></div></div>
  </WebShell3>;
}

Object.assign(window, { SAMPLE_TABS, SampleBar, SampleCardW, SampleMovesPane, WebPSamples, WebPSamplesDeployed, NewSamplePane, WebPSampleNew, NewMovePane, ReceiveMovePane, SampleMain, SampleTabs, WebPSample, WebPSampleReceive, WebPFinalise, COSTS, WebPCosting, KAR_TABS, KarBar, KarHead, KarigarPane, KarTable, WebPKarigars, LedgerPane, WebPKarigarLedger, WebPKarigarVerify, WebPKarigarNew, WebPKarigarAnalytics, WebPLocked });

/* ── board registration (New drafts) ── */
(window.NEW_DRAFT_MODULES = window.NEW_DRAFT_MODULES || []).push({ module: 'Production', note: 'overview · purchase (PO calendar and list, new PO, inward, past inwards, return) · material catalogue with a new-material form · dye ledger (cut orders, bulk balances, received dye WIP, receive a lot) · process setting (sequence, averages, BOM grid, locked, imported from a sample) · orders (cards, list, new, states) with the lifecycle terminal (assign, issue, Direct issue, receive, finished-goods receive, print) · job cards in five views plus the filters drawer · samples (board, 15-day reading, new, free moves, receive, make product) · costing · karigars (list, ledger, verification, new, analytics) · locked role (8 Sep, after the coverage review). Money only for manager roles; the floor phone shows none', subs: [
  { name: 'Overview', flow: 'module root: tiles, arrivals, recommendation strips, karigar dues pane', phone: [['Overview · tiles, due today, arrivals, high growth', ScreenPOverview], ['Production · locked for a sales role', ScreenPLocked]], web: [['Overview · tiles, arrivals, recommendations, dues pane', WebPOverview], ['Production · locked for this role', WebPLocked]] },
  { name: 'Purchase', flow: 'PO calendar → PO list → new PO in the pane → inward from a PO with the supplier pane → past inwards with gate tokens → return with the credit note · phone: inward capture', phone: [['Purchase orders · list', ScreenPPOList], ['Purchase · new PO sheet', ScreenPNewPO], ['Purchase · inward capture with lot photo', ScreenPInward], ['Purchase · return sheet', ScreenPReturn]], web: [['Purchase orders · calendar, PO pane', WebPPurchaseOrders], ['Purchase orders · list', WebPPOList], ['Purchase orders · new PO pane', WebPPONew], ['Purchase inward · from a PO, variance, accounts card, supplier pane', WebPInward], ['Purchase inward · past, GRN pane', WebPInwardPast], ['Purchase return · credit note pane', WebPReturn]] },
  { name: 'Materials', flow: 'picture-first catalogue sorted by inward → new material with shades → dye ledger: open cut orders → bulk balances and bulk issue → received lots as dye WIP → receive a lot · phone: catalogue, dye receive, dyer balances, bulk issue', phone: [['Materials · catalogue grid', ScreenPMaterials], ['Material · detail, ledger, used in', ScreenPMaterial], ['Materials · new material sheet', ScreenPNewMaterial], ['Dye · receive a cut order', ScreenPDyeReceive], ['Dye · dyer balances', ScreenPDyers], ['Dye · bulk issue sheet', ScreenPBulkIssue], ['Dye · new cut order sheet', ScreenPCutOrder]], web: [['Materials · catalogue, material pane', WebPMaterials], ['Materials · list, new material pane', WebPMaterialNew], ['Dye ledger · open cut orders, new cut order pane', WebPDye], ['Dye ledger · bulk balances, movements, bulk issue pane', WebPDyeBulk], ['Dye ledger · received lots as dye WIP', WebPDyeReceived], ['Dye ledger · receive a lot, what it unblocks', WebPDyeReceive]] },
  { name: 'Process setting', flow: 'product and sequence with the materials pane → materials & averages → BOM grid for Sky with the BOMs pane → Peach copied, locked by production, search pane → a product imported from a sample · phone: recipe view, averages', phone: [['Process setting · sequence, steps', ScreenPSetting], ['Recipe · view per colour', ScreenPRecipe], ['Averages · edit', ScreenPAverages], ['BOM · per process, one colour', ScreenPBom]], web: [['Process setting · product, sequence, steps, materials pane', WebPSetting1], ['Process setting · materials & averages, colour scope', WebPSetting2], ['Process setting · BOM grid Sky, BOMs pane', WebPSetting3], ['Process setting · Peach copied, locked, search pane', WebPSetting4], ['Process setting · imported from S-0412 for review', WebPSetting5]] },
  { name: 'Orders & lifecycle', flow: 'orders as cards (draft, awaiting, active) → list → new order with material readiness → lifecycle terminal (this-job pane) → assign a karigar → issue → issue on a Direct order → receive → receive finished goods → print · phone: orders, lifecycle, issue, receive, finished-goods receive, scan a job, assign, jobber entry', phone: [['Orders · list', ScreenPOrders], ['New production order sheet', ScreenPNewOrder], ['Lifecycle · timeline, process accordion', ScreenPLifecycle], ['Assign karigar sheet', ScreenPAssign], ['Issue · pieces to issue for', ScreenPIssue], ['Receive · pcs by colour, loss, rejection', ScreenPReceive], ['Receive · finished goods, verification', ScreenPReceiveFG], ['Scan a job QR → issue or receive', ScreenPScan], ['Jobber · the karigar records on his phone', ScreenPJobber], ['Print · sticker, printer, share', ScreenPPrint]], web: [['Orders · cards with draft and awaiting states, lifecycle pane', WebPOrders], ['Orders · list', WebPOrdersList], ['New production order · assignment, tranches, readiness pane', WebPNewOrder], ['Lifecycle · head, timeline, job panels, this-job pane', WebPLifecycle], ['Lifecycle · assign a karigar pane', WebPAssign], ['Lifecycle · issue pane, by pieces or by material', WebPIssue], ['Lifecycle · issue on a Direct order (Ready production)', WebPIssueDirect], ['Lifecycle · receive pane, rejection, loss, over-receive', WebPReceive], ['Lifecycle · receive finished goods, verification, transfer', WebPReceiveFG], ['Print · job card A4, issue and receive stickers', WebPPrint]] },
  { name: 'Job cards', flow: 'cards → filters drawer and saved views → swimlanes by journey state → table → gantt → calendar, all with the order lifecycle pane · phone: list, filters, opened card', phone: [['Job cards · list', ScreenPJobs], ['Job cards · sort & filter sheet', ScreenPJobsFilters], ['Job card · opened, issue / receive', ScreenPJob], ['Job cards · swimlanes', ScreenPSwimlanes], ['Job cards · timeline', ScreenPGantt], ['Job cards · calendar', ScreenPCalendar]], web: [['Job cards · cards, lifecycle pane', WebPJobCards], ['Job cards · all filters drawer, saved views', WebPJobFilters], ['Job cards · swimlanes by journey state', WebPSwimlanes], ['Job cards · table, pane collapsed', WebPJobTable], ['Job cards · gantt, today line, tranche marks', WebPGantt], ['Job cards · calendar of tranche and dye dates, day pane', WebPCalendar]] },
  { name: 'Samples', flow: 'board → deployed samples on their 15-day reading → new sample pane → sample lifecycle with free moves and the new-move pane → receive a move → make product: derived sequence, averages, BOM and costing preview · phone: list, lifecycle, new move, receive, new sample', phone: [['Samples · list', ScreenPSamples], ['Sample · lifecycle, moves', ScreenPSample], ['Sample · new move sheet', ScreenPNewMove], ['Sample · receive a move', ScreenPSampleReceive], ['Sample · new sample sheet', ScreenPNewSample], ['Sample · deployed, 15-day reading', ScreenPSampleDeployed], ['Sample → product sheet', ScreenPFinalise]], web: [['Samples · board, moves pane', WebPSamples], ['Samples · deployed, 15-day reading pane', WebPSamplesDeployed], ['Samples · new sample pane', WebPSampleNew], ['Sample · lifecycle, moves, new move pane', WebPSample], ['Sample · receive a move pane', WebPSampleReceive], ['Sample → product · derived sequence, averages, BOM preview', WebPFinalise]] },
  { name: 'Costing', flow: 'cards by state, default margins → breakdown pane with own price and approval', phone: [['Costing · list (manager phone)', ScreenPCosting], ['Costing · breakdown sheet', ScreenPCostBreakdown]], web: [['Costing · cards, margins, breakdown pane', WebPCosting]] },
  { name: 'Karigars', flow: 'rows with score, balances and dues → karigar pane → ledger and payments → verification of karigar-recorded entries → new karigar → analytics', phone: [['Karigars · list', ScreenPKarigars], ['Karigar · detail, jobs, chart', ScreenPKarigar], ['Karigar · verify an entry', ScreenPKarigarVerify], ['Karigars · new karigar sheet', ScreenPNewKarigar]], web: [['Karigars · list, karigar pane', WebPKarigars], ['Karigars · ledger pane, payments planned', WebPKarigarLedger], ['Karigars · unverified entries, verify pane', WebPKarigarVerify], ['Karigars · new karigar pane', WebPKarigarNew], ['Karigars · analytics', WebPKarigarAnalytics]] },
] });
