/* NEW DRAFTS · Studio › AI Designer "Stitch" · web screens (9 Sep 2026) and the board registration. Laptop 1280 × 800 on
   WebShell3 (rail · tab strip · header with the Studio sub-menu buttons · main · RightPane). Blocks and data come from
   mod-studio.jsx. Header nodes (plan §12): Stitch · Moodboard · History · Memory · Settings | Photoshoots · Upload centre.
   The designer terminal = StChat (300) + StCanvas stage + RightPane (340) holding StPane in one of its three states; the
   tuner floats as a translucent pane over the stage. Money: sold ₹ never on tiles; target price for money roles only. */

const STUDIO_SEG = [['Stitch'], ['Moodboard', null, true], ['History'], ['Memory', null, true], ['Settings', null, true], ['Photoshoots', 3], ['Upload centre', 12]];
const ST_TABS = (on) => [{ icon: 'layout-grid', label: 'Catalogue' }, { icon: 'sparkles', label: on, on: true }, { icon: 'flask-conical', label: 'Production · Samples' }];
function StShell({ T, section, active = 'Stitch', crumb, tab, children, pane, paneTitle, paneWidth = 340, paneCollapsed, headerRight, overlay, subOpen }) {
  return <WebShell3 T={T} module="Studio" crumb={crumb || ['Studio', section]} section={section} seg={STUDIO_SEG} active={active} subOpen={subOpen} tabs={ST_TABS(tab || 'Studio · ' + section)} pane={pane} paneTitle={paneTitle} paneWidth={paneWidth} paneCollapsed={paneCollapsed} headerRight={headerRight} overlay={overlay} searchWidth={132}>{children}</WebShell3>;
}
const StMain = ({ children, style, pad = '12px 24px 20px' }) => <div style={{ flex: 1, minWidth: 0, minHeight: 0, overflow: 'hidden', padding: pad, ...style }}>{children}</div>;
const StBar = ({ children, right, style }) => <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 10, overflow: 'hidden', ...style }}>{children}<span style={{ flex: 1 }} />{right}</div>;
const StCard = ({ T, children, style, alt, pad = 12 }) => <div style={{ padding: pad, borderRadius: 18, background: alt ? T.surface2 : T.surface, border: `1px solid ${T.line}`, minWidth: 0, ...style }}>{children}</div>;
const StPPane = ({ children, style }) => <div style={{ padding: 14, height: '100%', overflow: 'hidden', display: 'flex', flexDirection: 'column', boxSizing: 'border-box', ...style }}>{children}</div>;
/* the Tune button in the header: opens the translucent pane */
const TuneBtn = ({ T, on }) => <span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, height: 34, padding: '0 12px 0 8px', borderRadius: 999, border: `1px solid ${on ? T.ink : T.line2}`, background: on ? T.ink : 'transparent', color: on ? T.bg : T.ink, fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 500, whiteSpace: 'nowrap', marginRight: 4 }}><Orb T={{ ink: on ? T.bg : T.ink }} size={20} />Tune</span>;

/* ── W1 Tracks: category tracks across the top, the picked track's threads below, the pane = the picked thread ── */
function StThreadPane({ T }) {
  const r = ST_THREADS[0];
  return <StPPane>
    <div style={{ display: 'flex', gap: 10 }}><StThumb T={T} src={r[5]} w={72} h={64} r={12} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 18, fontWeight: 600, color: T.ink, lineHeight: 1.1 }}>{r[0]}</div><Meta T={T} style={{ display: 'block', marginTop: 4 }}>Blouse track · {r[2]} versions · {r[3]}</Meta><div style={{ marginTop: 6 }}><Pill T={T} small tone="accent">Open</Pill></div></span></div>
    <Sect T={T} style={{ margin: '12px 0 6px' }}>Context</Sect><StTray T={T} dark={false} size={32} meta stack />
    <Sect T={T} style={{ margin: '12px 0 6px' }}>Prompts · 4</Sect>
    {ST_MSGS.filter(m => m.me).map((m, i) => <div key={i} style={{ padding: '6px 0', borderTop: i ? `1px solid ${T.line}` : 0, fontFamily: T.fontUI, fontSize: 12, color: T.ink2, lineHeight: 1.4, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{m.text}</div>)}
    <Sect T={T} style={{ margin: '12px 0 6px' }} right={<Meta T={T}>v7 of 7 · branch at v5</Meta>}>Versions</Sect><StStrip T={T} cur={7} w={31} dark={false} compact />
    <div style={{ marginTop: 10, padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Sent · sales data on · score 87 · 5.4 pcs/day · 3 of 3 colours free</div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} small icon="git-branch">Branch</OutBtn><OutBtn T={T} small icon="archive">Archive</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="arrow-right" style={{ height: 34 }}>Open</T.Btn></div>
  </StPPane>;
}
function WebStTracks({ T }) {
  return <StShell T={T} section="Stitch" crumb={['Studio', 'Stitch', 'Tracks']} tab="Stitch · Tracks" paneTitle="Multicolour floral · cuts" pane={<StThreadPane T={T} />} headerRight={<TuneBtn T={T} />}>
    <ViewTabs T={T} tabs={[['Tracks', 6, 'layers'], ['Designer', null, 'wand-2']]} active="Tracks" right={<Meta T={T}>one track per category · Stitch remembers each</Meta>} />
    <StMain>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10 }}>{ST_TRACKS.map((t, i) => <StTrackCard key={t[0]} T={T} t={t} on={i === 0} />)}</div>
      <StBar style={{ marginTop: 14 }} right={<><T.Chip outline icon="arrow-down-up">Last worked</T.Chip><OutBtn T={T} small icon="plus">New thread</OutBtn></>}><span style={{ fontFamily: T.fontDisplay, fontSize: 17, fontWeight: 600, color: T.ink }}>Blouse · threads</span><Meta T={T}>6 · 3 open</Meta><span style={{ width: 8 }} />{['Open', 'Saved as sample', 'Shared', 'This week'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 28 }}>{c}</T.Chip>)}</StBar>
      <StCard T={T} style={{ padding: '2px 6px' }}>{ST_THREADS.map((r, i) => <StThreadRow key={r[0]} T={T} r={r} on={i === 0} first={i === 0} />)}</StCard>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12, padding: '8px 8px 8px 14px', borderRadius: 22, background: T.surface, border: `1px solid ${T.line2}`, boxShadow: `0 0 0 3px ${T.accentSoft}` }}><Orb T={T} size={24} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 13, color: T.ink3 }}>Start a thread in Blouse · describe the design, or drop a picture</span><StCaret T={T} icon="grid-3x3">Cuts grid</StCaret><StCaret T={T} icon="layout-grid">4 × 3</StCaret><span className="press" style={{ width: 34, height: 34, borderRadius: 17, background: T.accent, color: T.onAccent, display: 'grid', placeItems: 'center' }}><Ic name="arrow-up" size={16} sw={2.2} /></span></div>
    </StMain>
  </StShell>;
}

/* ── W2 · W3 · W4 The designer terminal: chat column · stage · pane in one of three states ── */
function StStage({ T, mode, zone, drop, working, compare, variations, chatCollapsed }) {
  const sp = spOf(T);
  const w = chatCollapsed ? 780 : 520;
  return <div style={{ flex: 1, minWidth: 0, minHeight: 0, background: sp.bg, color: SP.ink, display: 'flex', flexDirection: 'column', position: 'relative' }}>
    <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(90% 40% at 50% -10%, rgba(255,255,255,.05), transparent 60%)', pointerEvents: 'none' }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 16px 0', position: 'relative' }}><span style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600 }}>{mode === 'set' ? 'Set · Cuts 4×3' : compare ? 'v7 against v6' : 'v7 · cut 6'}</span><span style={{ fontFamily: T.fontUI, fontSize: 11, color: SP.ink3 }}>{mode === 'set' ? '12 tiles · pick one to open it' : zone ? `zone ${zone} selected` : 'tap a zone to edit it'}</span><span style={{ flex: 1 }} /><StThumbs T={T} dark up={mode !== 'set'} size={26} /><StBtn T={T} dark small icon="share-2">Share</StBtn></div>
    <div style={{ flex: 1, minHeight: 0, display: 'grid', placeItems: 'center', padding: '10px 16px', position: 'relative' }}><StCanvas T={T} mode={compare ? 'compare' : mode} w={w} h={mode === 'set' ? Math.round(w * .68) : 400} zone={zone} drop={drop} working={working} /></div>
    <div style={{ padding: '0 16px 14px', position: 'relative' }}>{variations ? <StVariations T={T} style={{ marginBottom: 10 }} /> : null}<StStrip T={T} cur={mode === 'set' ? 3 : 7} /></div>
    {working && <div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, height: 160, pointerEvents: 'none', overflow: 'hidden', opacity: .28 }}><span className="glow-a" style={{ position: 'absolute', left: '5%', bottom: -60, width: 260, height: 140, borderRadius: '50%', background: '#E0507A', filter: 'blur(40px)' }} /><span className="glow-b" style={{ position: 'absolute', left: '45%', bottom: -70, width: 240, height: 140, borderRadius: '50%', background: '#6E7BFF', filter: 'blur(40px)' }} /><span className="glow-c" style={{ position: 'absolute', left: '70%', bottom: -50, width: 220, height: 130, borderRadius: '50%', background: '#FFB347', filter: 'blur(40px)' }} /></div>}
  </div>;
}
function WebStDesigner({ T, state = 'set', zone, drop, compare, variations, working, tuner, chatCollapsed, overlayX }) {
  const paneTitle = state === 'set' ? 'Set options' : state === 'zone' ? 'Zone' : 'Version';
  return <StShell T={T} section="Stitch" crumb={['Studio', 'Stitch', 'Designer', 'Blouse', 'Multicolour floral · cuts']} tab="Stitch · Multicolour floral" paneTitle={paneTitle} pane={<StPane T={T} state={state} />} headerRight={<TuneBtn T={T} on={tuner} />} overlay={overlayX || (tuner && <div style={{ position: 'absolute', right: 16 + 340 + 12, top: 101, bottom: 16, width: 372, borderRadius: 22, zIndex: 40, overflow: 'hidden', ...glass({ glass: 'rgba(12,12,18,.72)', glassEdge: SP.line2, glassHi: 'rgba(255,255,255,.12)', shadow: '0 40px 80px -30px rgba(0,0,0,.7)' }) }}><StTuner T={T} tab={tuner === true ? 'Templates' : tuner} /></div>)}>
    <ViewTabs T={T} tabs={[['Tracks', 6, 'layers'], ['Designer', null, 'wand-2']]} active="Designer" right={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Meta T={T}>Blouse track · thread 3 of 6</Meta><StSeg T={T} items={['Chat left', 'Chat right']} on="Chat left" small /></span>} />
    <div style={{ flex: 1, minHeight: 0, display: 'flex' }}><StChat T={T} collapsed={chatCollapsed} working={working} /><StStage T={T} mode={state === 'set' ? 'set' : 'picked'} zone={zone} drop={drop} compare={compare} variations={variations} working={working} chatCollapsed={chatCollapsed} /></div>
  </StShell>;
}
const WebStDesignerSet = ({ T }) => <WebStDesigner T={T} state="set" working />;
const WebStDesignerZone = ({ T }) => <WebStDesigner T={T} state="zone" zone="Sleeve L" drop="Sleeve L" variations />;
const WebStDesignerVersion = ({ T }) => <WebStDesigner T={T} state="version" compare />;
const WebStTuner = ({ T }) => <WebStDesigner T={T} state="version" tuner="Models" chatCollapsed />;

/* ── W5 · W6 The context selector: a glass dialog over the terminal ── */
function StSelector({ T, tab = 'Products', sheet }) {
  return <div style={{ position: 'absolute', inset: 0, zIndex: 30 }}>{scrimF(T)}
    <div style={{ position: 'absolute', left: 84 + 100, top: 60, width: 900, height: 640, borderRadius: 24, display: 'flex', flexDirection: 'column', overflow: 'hidden', ...glass(T, { background: T.dark ? 'rgba(28,21,18,.96)' : 'rgba(252,250,246,.97)', boxShadow: '0 40px 90px -30px rgba(0,0,0,.6)' }) }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '14px 16px 8px 20px' }}><span style={{ fontFamily: T.fontDisplay, fontSize: 20, fontWeight: 600, color: T.ink }}>Context</span><Meta T={T}>pick up to 8 · one is the main</Meta><div style={{ flex: 1, maxWidth: 360, height: 36, borderRadius: 18, background: T.surface, border: `1px solid ${T.accent}`, boxShadow: `0 0 0 3px ${T.accentSoft}`, display: 'flex', alignItems: 'center', gap: 8, padding: '0 12px', marginLeft: 10, fontFamily: T.fontUI, fontSize: 12.5, color: T.ink3 }}><Ic name="search" size={14} />Design no, material, colour, tag<span className="aura-dot" style={{ width: 1.5, height: 14, background: T.accent }} /></div><span style={{ flex: 1 }} /><span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontFamily: T.fontUI, fontSize: 12, color: T.ink }}>Send sales data<StToggle T={T} on /></span><Hit T={T} icon="x" size={32} iconSize={15} style={{ background: T.chipBg }} /></div>
      <div style={{ padding: '0 20px' }}><StSelTabs T={T} tab={tab} /></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '10px 20px 0' }}>{(tab === 'Materials' ? ['In stock', 'Group', 'Shade', 'Work / finish', 'Used in active jobs', 'Dye WIP'] : ['High demand', 'High growth', 'Category', 'Colour', 'Work', 'Recent']).map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 28 }}>{c}{[2, 3].includes(i) && <Ic name="chevron-down" size={11} />}</T.Chip>)}<span style={{ flex: 1 }} /><span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 3, fontFamily: T.fontUI, fontSize: 12, color: T.ink2 }}>{tab === 'Materials' ? 'Last inward' : 'Demand score'}<Ic name="chevron-down" size={12} /></span><span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, height: 30, padding: '0 11px', borderRadius: 999, border: `1px solid ${sheet ? T.ink : T.line2}`, background: sheet ? T.ink : 'transparent', color: sheet ? T.bg : T.ink, fontFamily: T.fontUI, fontSize: 12 }}><Ic name="sliders-horizontal" size={13} />Sort & filter</span></div>
      <div style={{ flex: 1, minHeight: 0, overflow: 'hidden', padding: '10px 20px 0', position: 'relative' }}><StSelGrid T={T} tab={tab} w={tab === 'Materials' ? 136 : 132} cols={6} />
        {sheet && <div style={{ position: 'absolute', right: 20, top: 0, width: 380, maxHeight: 400, borderRadius: 18, padding: '4px 14px 0', overflow: 'hidden', zIndex: 4, ...glass(T, { background: T.dark ? 'rgba(28,21,18,.96)' : 'rgba(252,250,246,.97)' }) }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, height: 40 }}><span style={{ fontFamily: T.fontUI, fontSize: 13, fontWeight: 600, color: T.ink }}>Sort & filter · Materials</span><span style={{ flex: 1 }} /><span style={{ fontSize: 11, color: T.accent, fontFamily: T.fontUI }}>Clear</span></div>{[['Sort', ['Last inward', 'Stock', 'Name', 'Used in']], ['Group', ['Velvet', 'Net', 'Silk', 'Satin', 'Tissue', 'Lace']], ['Finish', ['Plain', 'Sequins', 'Zari', 'Cutdana', 'Mirror']], ['Stock', ['In', 'Low', 'Out', 'On order']], ['Supplier', ['Surat Textiles', 'Mumbai Fabrics', 'Bareilly Works']]].map(([k, opts]) => <div key={k} style={{ padding: '8px 0', borderTop: `1px solid ${T.line}` }}><div style={{ fontFamily: T.fontUI, fontSize: 10.5, letterSpacing: '.08em', textTransform: 'uppercase', color: T.ink3, marginBottom: 6 }}>{k}</div><div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>{opts.map((o, i) => <T.Chip key={o} on={i === 0 && k !== 'Supplier'} outline={!(i === 0 && k !== 'Supplier')} style={{ height: 26, fontSize: 11, padding: '0 9px' }}>{o}</T.Chip>)}</div></div>)}<div style={{ display: 'flex', justifyContent: 'flex-end', padding: '8px 0 12px' }}><T.Btn small style={{ height: 30 }}>Show 62</T.Btn></div></div>}</div>
      <div style={{ padding: '10px 20px 14px', borderTop: `1px solid ${T.line}` }}><StSelTray T={T} /></div>
    </div>
  </div>;
}
const WebStSelector = ({ T }) => <WebStDesigner T={T} state="set" overlayX={<StSelector T={T} tab="Products" />} />;
const WebStSelectorMats = ({ T }) => <WebStDesigner T={T} state="set" overlayX={<StSelector T={T} tab="Materials" sheet />} />;

/* ── W7 Save as sample: a sheet from the pane ── */
function StSaveSheet({ T }) {
  return <div style={{ position: 'absolute', inset: 0, zIndex: 30 }}>{scrimF(T)}
    <div style={{ position: 'absolute', right: 16, top: 60, width: 720, bottom: 40, borderRadius: 24, display: 'flex', overflow: 'hidden', ...glass(T, { background: T.dark ? 'rgba(28,21,18,.96)' : 'rgba(252,250,246,.97)', boxShadow: '0 40px 90px -30px rgba(0,0,0,.6)' }) }}>
      <div style={{ width: 300, flex: 'none', background: SP.bg, padding: 16, display: 'flex', flexDirection: 'column', gap: 10 }}><div style={{ position: 'relative', borderRadius: 14, overflow: 'hidden', background: '#fff', height: 300 }}>{stImg(ST_A + 'cut-06.jpg')}<span style={{ position: 'absolute', left: 8, bottom: 8 }}><StMark /></span></div><div style={{ fontFamily: T.fontUI, fontSize: 11, color: SP.ink3, lineHeight: 1.5 }}>v7 of Multicolour floral · cuts · goes into the sample's photo strip as the sketch. The reference slot takes 8337 and the refs; the first piece comes from sampling.</div><div style={{ display: 'flex', gap: 6, marginTop: 'auto' }}>{[['sketch', 'cut-06'], ['reference', 'blouse-main-sq'], ['first piece', null]].map(([k, f]) => <span key={k} style={{ flex: 1, textAlign: 'center' }}><StThumb T={T} src={f ? ST_A + f + '.jpg' : null} w={82} h={72} r={10} dark /><div style={{ fontFamily: T.fontUI, fontSize: 10, color: SP.ink3, marginTop: 4 }}>{k}</div></span>)}</div></div>
      <div style={{ flex: 1, minWidth: 0, padding: '16px 18px', display: 'flex', flexDirection: 'column' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ fontFamily: T.fontDisplay, fontSize: 22, fontWeight: 600, color: T.ink }}>New sample</span><Mono T={T} size={13}>S-0413</Mono><Meta T={T}>temporary number · Production › Samples › In designing</Meta><span style={{ flex: 1 }} /><Hit T={T} icon="x" size={30} iconSize={14} style={{ background: T.chipBg }} /></div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginTop: 14 }}>{[['Category', 'Blouse'], ['Colours · detected', 'Rani · Peach · Bottle · Emerald'], ['Target price · money roles', '₹9,500'], ['From', 'Multicolour floral · cuts · v7']].map(([k, v]) => <div key={k}><div style={{ fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3, marginBottom: 5 }}>{k}</div><div style={{ height: 36, padding: '0 10px', borderRadius: 11, background: T.surface, border: `1px solid ${T.line2}`, display: 'flex', alignItems: 'center', fontFamily: T.fontUI, fontSize: 12.5, color: T.ink }}>{v}<span style={{ flex: 1 }} /><Ic name="chevron-down" size={13} color={T.ink3} /></div></div>)}</div>
        <div style={{ marginTop: 10 }}><div style={{ fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3, marginBottom: 5 }}>Notes for the karigar</div><div style={{ padding: '8px 10px', borderRadius: 11, background: T.surface, border: `1px solid ${T.line2}`, fontFamily: T.fontUI, fontSize: 12.5, color: T.ink, lineHeight: 1.45 }}>Sweetheart line on cut 6. Emerald velvet under the beads on both sleeves, lotus stays as on 8337. Bead scale medium, density heavy.</div></div>
        <div style={{ marginTop: 10 }}><div style={{ fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3, marginBottom: 5 }}>Reference links</div><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}><T.Chip icon="shirt" style={{ height: 26, fontSize: 11 }}>8337 · main</T.Chip><T.Chip icon="shirt" style={{ height: 26, fontSize: 11 }}>8111 · 7781 · 3355</T.Chip><T.Chip icon="image-plus" style={{ height: 26, fontSize: 11 }}>2 moodboard</T.Chip><T.Chip icon="layers" style={{ height: 26, fontSize: 11 }}>M-0470</T.Chip><T.Chip icon="link" style={{ height: 26, fontSize: 11 }}>pinterest</T.Chip></div></div>
        <Sect T={T} style={{ margin: '14px 0 6px' }}>Or</Sect>
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}><T.Chip outline icon="image-plus">Save to moodboard</T.Chip><T.Chip outline icon="message-circle">Share as WhatsApp packet</T.Chip><T.Chip outline icon="shirt">Design content · new product master</T.Chip><T.Chip outline icon="camera" style={{ opacity: .5 }}>Send to Photoshoots · coming later</T.Chip></div>
        <span style={{ flex: 1 }} />
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><Meta T={T}>Stitch never creates a product · the sample flow does</Meta><span style={{ flex: 1 }} /><OutBtn T={T}>Open in Samples</OutBtn><T.Btn icon="flask-conical" style={{ height: 40 }}>Create sample</T.Btn></div>
      </div>
    </div>
  </div>;
}
const WebStSave = ({ T }) => <WebStDesigner T={T} state="version" overlayX={<StSaveSheet T={T} />} />;

/* ── W8 · W9 Moodboard ── */
function StMoodPane({ T, why }) {
  const it = ST_MOOD_MINE[1];
  return <StPPane>
    <div style={{ borderRadius: 14, overflow: 'hidden', height: 220, background: T.photoBg }}>{stImg(it.src)}</div>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 10 }}><span style={{ width: 12, height: 2, background: SP.threadH, borderRadius: 1 }} /><span style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, color: T.ink }}>Added by Stitch</span><Meta T={T}>· similar to 8337 · 10/09</Meta></div>
    {why && <div style={{ display: 'flex', gap: 8, alignItems: 'stretch', marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}` }}><StThread h="auto" /><span style={{ fontFamily: T.fontDisplay, fontSize: 14, color: T.ink2, lineHeight: 1.35 }}>Why this: the same lotus at a different scale, and a neckline you have not tried on 8337.</span></div>}
    <Sect T={T} style={{ margin: '12px 0 4px' }}>Used in</Sect>
    {[['Multicolour floral · cuts', 'as ref · 10/09'], ['Colourways · rani floral', 'as ref · 02/09']].map(([a, b], i) => <div key={a} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '7px 0', borderTop: i ? `1px solid ${T.line}` : 0, fontFamily: T.fontUI, fontSize: 12 }}><Ic name="wand-2" size={12} color={T.ink3} /><span style={{ flex: 1, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{a}</span><Meta T={T}>{b}</Meta></div>)}
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} small icon="pin">Pin</OutBtn><OutBtn T={T} small icon="x">Remove</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="plus" style={{ height: 34 }}>Use as context</T.Btn></div>
  </StPPane>;
}
function WebStMood({ T, tab = 'Mine' }) {
  const mine = tab === 'Mine';
  return <StShell T={T} section="Moodboard" active="Moodboard" crumb={['Studio', 'Moodboard', tab]} tab={'Moodboard · ' + tab} paneTitle={mine ? 'Picked' : 'Why this'} pane={<StMoodPane T={T} why={!mine} />} headerRight={<TuneBtn T={T} />}>
    <ViewTabs T={T} tabs={[['Mine', 36, 'user'], ['Stitch’s', 51, 'sparkles']]} active={tab} right={mine ? <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontFamily: T.fontUI, fontSize: 12.5, color: T.ink }}><StToggle T={T} on={false} />Only my uploads & links</span> : <OutBtn T={T} small icon="refresh-cw">Replenish · 12 from the catalogue and Mine</OutBtn>} />
    <StMain>
      <StBar right={mine ? <><T.Chip outline icon="arrow-down-up">Newest</T.Chip><OutBtn T={T} small icon="upload">Upload</OutBtn><OutBtn T={T} small icon="link">Paste a link</OutBtn></> : <T.Chip outline icon="arrow-down-up">This week</T.Chip>}><T.Chip icon="search" outline>Colour, category, source</T.Chip>{(mine ? ['New', 'Unused', 'Uploads', 'Links', 'WhatsApp', 'By Stitch', 'Category', 'Colour'] : ['This week', 'Collected', 'Generated', 'Kept', 'Track']).map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 28 }}>{c}{(c === 'Category' || c === 'Colour' || c === 'Track') && <Ic name="chevron-down" size={11} />}</T.Chip>)}</StBar>
      {mine ? <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 10 }}>{ST_MOOD_MINE.map((it, i) => <StMoodTile key={i} T={T} it={it} w={126} on={i === 1} />)}</div>
        : ST_MOOD_ST.map(([name, n, imgs]) => <div key={name} style={{ marginBottom: 14 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}><StThread w={2} h={16} /><span style={{ fontFamily: T.fontDisplay, fontSize: 17, fontWeight: 600, color: T.ink }}>{name}</span><Meta T={T}>{n} items</Meta><span style={{ flex: 1 }} /><span style={{ display: 'inline-flex', gap: 4 }}>{['Collected', 'Generated', 'Kept'].map((k, i) => <T.Chip key={k} on={i === 2} outline={i !== 2} style={{ height: 24, fontSize: 11, padding: '0 8px' }}>{k}</T.Chip>)}</span></div><div style={{ display: 'flex', gap: 10 }}>{imgs.map((f, i) => <StTile key={f} T={T} src={ST_A + f + '.jpg'} w={126} h={118} r={10} on={name.startsWith('Multi') && i === 1} meta={['Collected', 'Generated', 'Kept'][i % 3]} mark={i % 3 === 1} />)}</div></div>)}
    </StMain>
  </StShell>;
}
const WebStMoodMine = ({ T }) => <WebStMood T={T} tab="Mine" />;
const WebStMoodStitch = ({ T }) => <WebStMood T={T} tab="Stitch’s" />;

/* ── W10 History: every generation, grouped by thread then day; the pane shares it or makes it design content ── */
function StHistPane({ T }) {
  return <StPPane>
    <div style={{ position: 'relative', borderRadius: 14, overflow: 'hidden', height: 180, background: '#fff' }}>{stImg(ST_A + 'cut-06.jpg')}<span style={{ position: 'absolute', left: 8, bottom: 8 }}><StMark /></span></div>
    <div style={{ marginTop: 10, fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, color: T.ink }}>v7 · sweetheart, emerald velvet</div><Meta T={T} style={{ display: 'block', marginTop: 2 }}>Multicolour floral · cuts · today 10:41 · re-prompt of cell 6 · 8337 + 5 refs · sales data on</Meta>
    <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontDisplay, fontSize: 14, color: T.ink, lineHeight: 1.35 }}>Cell 6, same but sweetheart neck, in emerald velvet.</div>
    <Sect T={T} style={{ margin: '12px 0 6px' }}>Share</Sect><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}><T.Chip outline icon="message-circle" style={{ height: 28 }}>WhatsApp packet</T.Chip><T.Chip outline icon="download" style={{ height: 28 }}>Export</T.Chip><T.Chip outline icon="image-plus" style={{ height: 28 }}>To moodboard</T.Chip></div>
    <Sect T={T} style={{ margin: '12px 0 6px' }}>Use as design content</Sect><Meta T={T} style={{ display: 'block', whiteSpace: 'normal', lineHeight: 1.4 }}>The picture becomes the design-content image of a new master. Hub › Masters completes the rest.</Meta>
    <div style={{ display: 'flex', gap: 6, marginTop: 8 }}><OutBtn T={T} small icon="shirt" style={{ flex: 1, justifyContent: 'center' }}>New product master</OutBtn><OutBtn T={T} small icon="layers" style={{ flex: 1, justifyContent: 'center' }}>New material master</OutBtn></div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><OutBtn T={T} small icon="wand-2">Reopen thread</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="flask-conical" style={{ height: 34 }}>Save as sample</T.Btn></div>
  </StPPane>;
}
function WebStHistory({ T }) {
  return <StShell T={T} section="History" active="History" crumb={['Studio', 'History', 'By day']} tab="Studio · History" paneTitle="v7 · today 10:41" pane={<StHistPane T={T} />} headerRight={<TuneBtn T={T} />}>
    <ViewTabs T={T} tabs={[['By thread', 5, 'wand-2'], ['By day', null, 'calendar']]} active="By day" right={<Meta T={T}>every set, version and zone variation · 30 d kept · Settings › Defaults</Meta>} />
    <StMain>
      <StBar right={<T.Chip outline icon="arrow-down-up">Newest</T.Chip>}><T.Chip icon="search" outline>Thread, template, day</T.Chip>{['Kept', 'Saved', 'Shared', 'Design content', 'Template', 'Track'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 28 }}>{c}{i > 3 && <Ic name="chevron-down" size={11} />}</T.Chip>)}</StBar>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>{ST_HIST.map(([day, rows]) => <StCard key={day} T={T} style={{ padding: '4px 6px 6px' }}><Meta T={T} style={{ display: 'block', padding: '6px 10px 4px', letterSpacing: '.06em', textTransform: 'uppercase' }}>{day} · {rows.length} generations</Meta>{rows.map((r, i) => <StHistRow key={r[0] + r[2]} T={T} r={r} first={i === 0} on={day === 'Today' && i === 0} />)}</StCard>)}</div>
      <StCard T={T} alt style={{ marginTop: 12, display: 'flex', alignItems: 'center', gap: 12 }}><span style={{ fontFamily: T.fontDisplay, fontSize: 16, fontWeight: 600, color: T.ink }}>Today · the tiles</span><div style={{ display: 'flex', gap: 6, flex: 1, overflow: 'hidden' }}>{[6, 10, 8, 5, 2, 11, 3, 1, 9].map(n => <StThumb key={n} T={T} src={stCut(n).src} w={58} h={50} r={8} ring={n === 6 ? T.accent : null} />)}</div><Meta T={T}>tap any tile · thumbs count as feedback</Meta></StCard>
    </StMain>
  </StShell>;
}

/* ── W11 · W12 Memory: What works · Taste rules ── */
function StWorksPane({ T }) {
  return <StPPane>
    <div style={{ display: 'flex', gap: 8 }}><span style={{ flex: 1, textAlign: 'center' }}><div style={{ position: 'relative', borderRadius: 12, overflow: 'hidden', height: 120, background: '#fff' }}>{stImg(ST_A + 'sheet-03.jpg')}<span style={{ position: 'absolute', left: 6, bottom: 6 }}><StMark /></span></div><Meta T={T} style={{ display: 'block', marginTop: 4 }}>Stitch · design 3</Meta></span><span style={{ flex: 1, textAlign: 'center' }}><div style={{ borderRadius: 12, overflow: 'hidden', height: 120, background: T.photoBg }}>{stImg('assets/crm/8111.jpg', '50% 12%')}</div><Meta T={T} style={{ display: 'block', marginTop: 4 }}>S-0411 · first piece</Meta></span></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><T.Kpi label="Demand" value="96" sub="band High" small /><T.Kpi label="Pcs ordered" value="42" sub="6 customers" small /><T.Kpi label="Returns" value="1" sub="colour" small /></div>
    <Sect T={T} style={{ margin: '12px 0 4px' }}>By colour</Sect>
    {[['Gold', 26, 0], ['Rose gold', 11, 1], ['Ivory', 5, 0]].map(([c, p, r]) => <div key={c} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ width: 4, height: 16, borderRadius: 2, background: c === 'Gold' ? '#C9A45C' : c === 'Ivory' ? '#E8DCC5' : '#D9A08C' }} /><span style={{ flex: 1, color: T.ink }}>{c}</span><b>{p} pcs</b><span style={{ color: r ? T.warn : T.ink3, width: 40, textAlign: 'right' }}>{r ? r + ' back' : '—'}</span></div>)}
    <span style={{ flex: 1 }} />
    <T.Btn icon="wand-2" style={{ width: '100%', height: 40 }}>Make more like this</T.Btn>
  </StPPane>;
}
function WebStWorks({ T }) {
  return <StShell T={T} section="Memory" active="Memory" crumb={['Studio', 'Memory', 'What works']} tab="Memory · What works" paneTitle="S-0411 · Bridal gold corset" pane={<StWorksPane T={T} />} headerRight={<TuneBtn T={T} />}>
    <ViewTabs T={T} tabs={[['What works', 5, 'trending-up'], ['Taste rules', 4, 'list-checks']]} active="What works" right={<Meta T={T}>Stitch designs that became samples, joined to what the ERP already records · rows, not conclusions</Meta>} />
    <StMain>
      <div style={{ display: 'flex', gap: 10 }}><T.Kpi label="Designs saved" value="5" sub="from 3 threads" /><T.Kpi label="Activated" value="3" sub="2 reading" /><T.Kpi label="Working" value="2" sub="demand ≥ 80 after read" tone="ok" /><StCard T={T} alt style={{ flex: 2, display: 'flex', gap: 10, alignItems: 'stretch', padding: '8px 12px' }}><StThread h="auto" /><span style={{ fontFamily: T.fontDisplay, fontSize: 15, color: T.ink2, lineHeight: 1.35, alignSelf: 'center' }}>Not enough data yet · 3 of 5 rows have finished their read. Stitch adds a reading only at five.</span></StCard></div>
      <StBar style={{ marginTop: 12 }} right={<T.Chip outline icon="arrow-down-up">Demand score</T.Chip>}>{['Working', 'Weak', 'Too early', 'Category'].map((c, i) => <T.Chip key={c} outline style={{ height: 28 }}>{c}{i === 3 && <Ic name="chevron-down" size={11} />}</T.Chip>)}</StBar>
      <StCard T={T} style={{ padding: '2px 6px 4px' }}><div style={{ display: 'grid', gridTemplateColumns: '40px 1.4fr 68px 70px 64px 76px 40px 40px 84px', gap: '0 10px', padding: '8px 10px 6px', fontFamily: T.fontUI, fontSize: 10.5, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}><span /><span>Thread · sample</span><span>Activated</span><span>Read</span><span>Demand</span><span>Score</span><span>Pcs</span><span>Back</span><span>Verdict</span></div>{ST_WORKS.map((r, i) => <StWorksRow key={r[2]} T={T} r={r} first={i === 0} on={i === 1} />)}</StCard>
    </StMain>
  </StShell>;
}
function WebStRules({ T }) {
  return <StShell T={T} section="Memory" active="Memory" crumb={['Studio', 'Memory', 'Taste rules']} tab="Memory · Taste rules" paneTitle="Stitch proposes" pane={<StPPane><div style={{ display: 'flex', gap: 8, alignItems: 'stretch', padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}` }}><StThread h="auto" /><span style={{ fontFamily: T.fontDisplay, fontSize: 15, color: T.ink, lineHeight: 1.35 }}>Keep the lotus as the hero on multicolour. Three of four kept tiles in the last two sets had it centred.</span></div><Meta T={T} style={{ display: 'block', marginTop: 8, whiteSpace: 'normal', lineHeight: 1.4 }}>from thread Multicolour floral · cuts · thumbs and swipes of 10/09</Meta><div style={{ display: 'flex', gap: 6, marginTop: 10 }}>{[6, 8, 11].map(n => <StThumb key={n} T={T} src={stCut(n).src} w={72} h={62} r={9} />)}</div><div style={{ display: 'flex', gap: 6, marginTop: 12 }}><OutBtn T={T} small icon="x">Not this</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="check" style={{ height: 32 }}>Add the rule</T.Btn></div><Sect T={T} style={{ margin: '14px 0 4px' }}>How rules are learned</Sect><Meta T={T} style={{ display: 'block', whiteSpace: 'normal', lineHeight: 1.45 }}>Thumbs on sets and tiles, the tile you pick, and swipes on the phone. Stitch proposes a rule when three tiles agree; you switch it on.</Meta></StPPane>} headerRight={<TuneBtn T={T} />}>
    <ViewTabs T={T} tabs={[['What works', 5, 'trending-up'], ['Taste rules', 4, 'list-checks']]} active="Taste rules" right={<OutBtn T={T} small icon="plus">Add a rule</OutBtn>} />
    <StMain>
      <StBar right={<T.Chip outline icon="arrow-down-up">Newest</T.Chip>}>{['On', 'Off', 'Typed by me', 'Proposed by Stitch', 'Category'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 28 }}>{c}{i === 4 && <Ic name="chevron-down" size={11} />}</T.Chip>)}</StBar>
      <div style={{ display: 'grid', gridTemplateColumns: '1.3fr 1fr', gap: 12 }}>
        <StCard T={T} style={{ padding: '2px 12px 4px' }}>{ST_RULES.map((r, i) => <StRuleRow key={r[0]} T={T} r={r} first={i === 0} />)}</StCard>
        <StCard T={T} alt><Sect T={T} style={{ margin: '0 0 6px' }}>Feedback this month</Sect><div style={{ display: 'flex', gap: 8 }}><T.Kpi label="Thumbs up" value="61" small /><T.Kpi label="Thumbs down" value="14" small /><T.Kpi label="Swipes" value="132" sub="on the phone" small /></div><div style={{ marginTop: 10 }}><LineG T={T} series={[{ pts: [4, 6, 5, 9, 11, 10, 14, 12, 16, 15, 19, 18], color: T.accent, width: 2 }, { pts: [2, 2, 3, 2, 4, 3, 3, 4, 3, 5, 4, 4], color: T.ink3, width: 1.5, dash: true }]} w={360} h={90} area /></div><Legend T={T} items={[['kept', T.accent], ['discarded', T.ink3]]} /></StCard>
      </div>
    </StMain>
  </StShell>;
}

/* ── W13 · W14 Settings: Models · Defaults ── */
function WebStSettings({ T, tab = 'Models' }) {
  const models = tab === 'Models';
  return <StShell T={T} section="Settings" active="Settings" crumb={['Studio', 'Settings', tab]} tab={'Settings · ' + tab} paneTitle={models ? 'Providers' : 'What Stitch sends'} pane={<StPPane>{models ? <>{[['Image · provider A', 'key ok', '1,204 images · Sep', T.ok], ['Image · provider B', 'key ok', '41 images · Sep', T.ok], ['Text · chat and prompts', 'key ok', '412 runs · Sep', T.ok], ['Video', 'no key yet', 'coming later', T.ink3]].map(([k, s, n, c], i) => <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 0', borderTop: i ? `1px solid ${T.line}` : 0 }}><span style={{ width: 8, height: 8, borderRadius: 4, background: c, boxShadow: `0 0 0 3px ${c}33` }} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5, color: T.ink }}>{k}</div><Meta T={T} style={{ display: 'block' }}>{s} · {n}</Meta></span><OutBtn T={T} small>Test</OutBtn></div>)}<Sect T={T} style={{ margin: '12px 0 6px' }}>Usage · Sep</Sect><div style={{ display: 'flex', gap: 8 }}><T.Kpi label="Runs" value="259" small /><T.Kpi label="Images" value="1,204" small /><T.Kpi label="Failed" value="6" small tone="danger" /></div><Meta T={T} style={{ display: 'block', marginTop: 8 }}>cost shows for admin only</Meta></> : <><div style={{ fontFamily: T.fontUI, fontSize: 12, color: T.ink2, lineHeight: 1.5 }}>Preview of the text that rides along with 8337 when sales data is on:</div><div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontMono, fontSize: 10.5, lineHeight: 1.55, color: T.ink2 }}>8337 · Blouse · demand band High (87) · 5.4 pcs/day · 30 d 164 pcs · lifetime 1,120 · returns 2 · read complete · colours Rani 61 % Peach 24 % Bottle 15 %</div><Meta T={T} style={{ display: 'block', marginTop: 8, whiteSpace: 'normal', lineHeight: 1.4 }}>Sold ₹ is omitted for roles without the money right, not masked.</Meta></>}</StPPane>} headerRight={<TuneBtn T={T} />}>
    <ViewTabs T={T} tabs={[['Models', null, 'cpu'], ['Defaults', null, 'sliders-horizontal'], ['Usage', null, 'bar-chart-3'], ['Context', null, 'layers']]} active={tab} right={<Meta T={T}>{models ? 'one model per template · the tuner picks per thread' : 'what every new thread starts with'}</Meta>} />
    <StMain>
      {models ? <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: 12 }}><StCard T={T} style={{ padding: '2px 12px 4px' }}>{ST_MODELS.map((r, i) => <StModelRow key={r[0]} T={T} r={r} first={i === 0} />)}</StCard><StCard T={T} alt><Sect T={T} style={{ margin: '0 0 6px' }}>Per model · Sep</Sect>{[['nano banana', 186, T.accent], ['gpt image 2', 73, T.accentLine], ['claude', 412, T.ink3]].map(([m, n, c]) => <div key={m} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '7px 0', fontFamily: T.fontUI, fontSize: 12.5 }}><span style={{ width: 90, color: T.ink2 }}>{m}</span><span style={{ flex: 1, height: 10, borderRadius: 5, background: T.chipBg }}><span style={{ display: 'block', width: Math.round(n / 412 * 100) + '%', height: 10, borderRadius: 5, background: c }} /></span><b style={{ width: 34, textAlign: 'right' }}>{n}</b></div>)}<Meta T={T} style={{ display: 'block', marginTop: 10, whiteSpace: 'normal', lineHeight: 1.4 }}>Models are named the way the BRD names them. Keys and providers sit in the pane; the tuner's Models tab picks per thread.</Meta></StCard></div>
        : <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <StCard T={T} style={{ padding: '4px 12px' }}><Sect T={T} style={{ margin: '8px 0 2px' }}>Sales data</Sect><StToggleRow T={T} label="Default for the switch" right={<StSeg T={T} items={['On', 'Off', 'Ask']} on="On" small />} />{[['Demand score and band', true], ['Pcs 30 d', true], ['Pcs lifetime', true], ['Returns', true], ['Read state', true], ['Sold ₹ · money roles', false]].map(([k, on]) => <StToggleRow key={k} T={T} label={k} on={on} />)}</StCard>
          <StCard T={T} style={{ padding: '4px 12px' }}><Sect T={T} style={{ margin: '8px 0 2px' }}>Generation</Sect><StToggleRow T={T} label="Cells in a grid" right={<StSeg T={T} items={['4×3', '5×4', '3×2']} on="4×3" small />} /><StToggleRow T={T} label="Variations on a zone" right={<StSeg T={T} items={['2', '4', '6']} on="4" small />} /><StToggleRow T={T} label="Mark every render" sub="AI render · not a fit sample" on /><Sect T={T} style={{ margin: '12px 0 2px' }}>Memory</Sect><StToggleRow T={T} label="Remember threads" right={<StSeg T={T} items={['Always', 'Ask', 'Never']} on="Always" small />} /><StToggleRow T={T} label="Keep history for" right={<StSeg T={T} items={['30 d', '90 d', 'A year']} on="90 d" small />} /><StToggleRow T={T} label="Forget everything Stitch learned" sub="asks twice" right={<OutBtn T={T} small icon="trash-2">Forget</OutBtn>} /></StCard>
          <StCard T={T} style={{ padding: '4px 12px', gridColumn: '1 / -1' }}><Sect T={T} style={{ margin: '8px 0 2px' }}>Sharing</Sect><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 24px' }}><StToggleRow T={T} label="WhatsApp share-in number" sub="pictures sent here land in Moodboard › Mine" right={<T.Chip outline icon="message-circle" style={{ height: 28 }}>98152 00110</T.Chip>} /><StToggleRow T={T} label="Who can edit in Stitch" sub="admin and sub-admin edit · production manager and merchandiser view and save" right={<T.Chip outline style={{ height: 28 }}>Roles</T.Chip>} /></div></StCard>
        </div>}
    </StMain>
  </StShell>;
}
const WebStSettingsModels = ({ T }) => <WebStSettings T={T} tab="Models" />;
const WebStSettingsDefaults = ({ T }) => <WebStSettings T={T} tab="Defaults" />;

/* Self-registration: the board reads window.NEW_DRAFT_MODULES; modules.js carries one line for this module. */
(window.NEW_DRAFT_MODULES = window.NEW_DRAFT_MODULES || []).push({ module: 'Studio', note: 'AI designer "Stitch" · chat + canvas terminal on deep space · context selector · zone edit · versions · moodboard Mine / Stitch’s · history · what works · taste rules · settings · fixed tuner · phone with every option, the pane as a half sheet, swipe approval (9 Sep). Sold ₹ never on tiles; target price for money roles', subs: [
  { name: 'Stitch · Tracks', flow: 'category tracks → threads of a track → start a thread from the prompt', phone: [['Tracks · categories, threads, prompt tray', ScreenStTracks]], web: [['Tracks · category cards, threads, thread pane', WebStTracks]] },
  { name: 'Stitch · Designer', flow: 'set on the stage → tile picked, zone selected, material dropped → re-prompt and versions compared → the tuner as I left it', phone: [['Designer · chat with canvas cards', ScreenStChat], ['Canvas · zone chips, version rail, Pane button', ScreenStCanvas], ['Canvas · zone pane as a half sheet', ScreenStZoneSheet], ['Canvas · tuner as a half sheet', ScreenStTunerSheet], ['Swipe approval · keep, discard, save', ScreenStSwipe]], web: [['Designer · set on the stage, set options', WebStDesignerSet], ['Designer · zone selected, material dropped, 4 variations', WebStDesignerZone], ['Designer · v7 against v6, version pane', WebStDesignerVersion], ['Designer · tuner pane, chat collapsed', WebStTuner]] },
  { name: 'Context selector', flow: 'Products → Materials with sort & filter → Samples · WIP · Moodboard tabs → add to context', phone: [['Context · picker sheet', ScreenStPicker]], web: [['Context · Products, sales data on', WebStSelector], ['Context · Materials with sort & filter', WebStSelectorMats]] },
  { name: 'Hand-off', flow: 'save picked as sample → S-0413 in Production › Samples · In designing', phone: [], web: [['Save as sample · sheet', WebStSave]] },
  { name: 'Moodboard', flow: 'Mine with the one-click switch → Stitch’s by track with Replenish', phone: [['Moodboard · Mine', ScreenStMoodMine], ['Moodboard · Stitch’s', ScreenStMoodStitch]], web: [['Moodboard · Mine, picked item pane', WebStMoodMine], ['Moodboard · Stitch’s, why this', WebStMoodStitch]] },
  { name: 'History', flow: 'every generation by day → share externally or use as design content', phone: [['History · by day', ScreenStHistory], ['History · an item, share or design content', ScreenStHistoryItem]], web: [['History · by day, item pane', WebStHistory]] },
  { name: 'Memory', flow: 'what works (rows, not conclusions) → taste rules with provenance', phone: [['Memory · what works', ScreenStWorks]], web: [['Memory · what works table', WebStWorks], ['Memory · taste rules, Stitch proposes', WebStRules]] },
  { name: 'Settings', flow: 'models per template → defaults · memory · sharing', phone: [['Settings · models', ScreenStSettings]], web: [['Settings · models, providers pane', WebStSettingsModels], ['Settings · defaults, what Stitch sends', WebStSettingsDefaults]] },
] });

Object.assign(window, { STUDIO_SEG, ST_TABS, StShell, StMain, StBar, StCard, StPPane, TuneBtn, StThreadPane, WebStTracks, StStage, WebStDesigner, WebStDesignerSet, WebStDesignerZone, WebStDesignerVersion, WebStTuner, StSelector, WebStSelector, WebStSelectorMats, StSaveSheet, WebStSave, StMoodPane, WebStMood, WebStMoodMine, WebStMoodStitch, StHistPane, WebStHistory, StWorksPane, WebStWorks, WebStRules, WebStSettings, WebStSettingsModels, WebStSettingsDefaults });
