/* NEW DRAFTS · Production · web, part A (8 Sep 2026, revised after the coverage review): shell, overview, purchase,
   materials catalogue, dye ledger, process setting. Laptop 1280 × 800 on WebShell3 (rail, tab strip, header with the
   sub-menu buttons, RightPane). Part B (mod-production-web2.jsx) holds orders + lifecycle, job cards, samples, costing,
   karigars and registers the module on the board. Shared data and components come from mod-production.jsx.
   House rules applied here: one filled maroon button per screen (the pane's action wins when a pane form is open;
   toolbar "New …" buttons are outlined), the design photo beside every design number, money only where the caption
   says money roles, action tags filled, state pills outlined. */

const PROD_SEG = [['Purchase', null, true], ['Materials', null, true], ['Process setting'], ['Orders', null, true], ['Job cards', null, true], ['Samples', null, true], ['Costing'], ['Karigars']];
const PR_TABS = (on, extra) => [{ icon: 'layout-grid', label: 'Catalogue' }, { icon: 'scissors', label: on, on: true }, ...(extra || [{ icon: 'package', label: 'Dispatch · Out of stock' }])];
const PANE_W = 340; /* one pane width for the whole module */
function PShell({ T, section, active, crumb, tab, extraTabs, children, pane, paneTitle, paneWidth = PANE_W, paneCollapsed, headerRight }) {
  return <WebShell3 T={T} module="Production" crumb={crumb || ['Production', section]} section={section} seg={PROD_SEG} active={active} tabs={PR_TABS(tab || 'Production · ' + section, extraTabs)} pane={pane} paneTitle={paneTitle} paneWidth={paneWidth} paneCollapsed={paneCollapsed} headerRight={headerRight} searchWidth={132}>{children}</WebShell3>;
}
const PMain = ({ children, style, pad = '12px 24px 20px' }) => <div style={{ flex: 1, minWidth: 0, minHeight: 0, overflow: 'hidden', padding: pad, ...style }}>{children}</div>;
const PPane = ({ children, style }) => <div style={{ padding: 14, height: '100%', overflow: 'hidden', display: 'flex', flexDirection: 'column', ...style }}>{children}</div>;
const PBar = ({ T, children, right, style }) => <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 10, overflow: 'hidden', ...style }}>{children}<span style={{ flex: 1 }} />{right}</div>;
const PCard = ({ T, children, style, alt, pad = 12 }) => <div style={{ padding: pad, borderRadius: 18, background: alt ? T.surface2 : T.surface, border: `1px solid ${T.line}`, minWidth: 0, ...style }}>{children}</div>;
const PTabs = ({ T, tabs, on, iconOnly }) => <span style={{ display: 'inline-flex', padding: 3, borderRadius: 999, background: T.bg2, flex: 'none' }}>{tabs.map(t => { const l = Array.isArray(t) ? t[0] : t, ic = Array.isArray(t) ? t[1] : null; const a = l === on; return <span key={l} className="press" title={l} style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 26, padding: iconOnly && !a ? '0 8px' : '0 10px', borderRadius: 999, background: a ? T.surface : 'transparent', color: a ? T.ink : T.ink3, fontFamily: T.fontUI, fontSize: 12, fontWeight: a ? 600 : 400, whiteSpace: 'nowrap', boxShadow: a ? '0 1px 3px rgba(0,0,0,.08)' : 'none' }}>{ic && <Ic name={ic} size={13} />}{iconOnly && !a ? null : l}</span>; })}</span>;
const PaneTabs = ({ T, tabs, on }) => <div style={{ display: 'flex', gap: 2, padding: '0 4px', borderBottom: `1px solid ${T.line}`, marginBottom: 10 }}>{tabs.map(t => <span key={t} className="press" style={{ position: 'relative', padding: '6px 8px 9px', fontFamily: T.fontUI, fontSize: 12.5, fontWeight: t === on ? 600 : 400, color: t === on ? T.ink : T.ink3, whiteSpace: 'nowrap' }}>{t}{t === on && <span style={{ position: 'absolute', left: 8, right: 8, bottom: -1, height: 2, background: T.accent, borderRadius: 1 }} />}</span>)}</div>;
/* caret chip: neutral outline with a chevron, shows the value when set */
const Caret = ({ T, children, on, style }) => <T.Chip outline={!on} on={on} style={{ height: 30, ...style }}>{children}<Ic name="chevron-down" size={12} /></T.Chip>;
const AllFilters = ({ T }) => <T.Chip icon="sliders-horizontal" outline>All filters</T.Chip>;
const Lock = ({ T }) => <Ic name="lock" size={10} color={T.ink3} style={{ marginLeft: 3, verticalAlign: -1 }} />;

/* ── W0 · Overview (module root) ── */
const RecStrip = ({ T, title, items, link, sample }) => <PCard T={T}><Sect T={T} style={{ margin: '0 0 8px' }} right={<span className="press" style={{ fontFamily: T.fontUI, fontSize: 11.5, color: T.accent, whiteSpace: 'nowrap' }}>{link}</span>}>{title}</Sect><div style={{ display: 'flex', gap: 10, overflow: 'hidden' }}>{items.map(([code, w, s], i) => { const d = sample ? (PR_SAMPLES.find(x => x.no === code) || {}).d || { code } : PR_D(code); return <div key={i} className="press" style={{ display: 'flex', gap: 8, alignItems: 'center', padding: 8, borderRadius: 14, background: T.surface2, border: `1px solid ${T.line}`, minWidth: 0, flex: 1 }}><Thumb T={T} d={d} w={40} h={50} r={9} /><span style={{ minWidth: 0 }}><Num T={T} size={16}>{code}</Num><Meta T={T} style={{ display: 'block', marginTop: 3, whiteSpace: 'normal', lineHeight: 1.3 }}>{w}</Meta></span></div>; })}</div></PCard>;
function WebPOverview({ T }) {
  return <PShell T={T} section="Overview" crumb={['Production']} tab="Production · Overview" paneTitle="Payments due this week" pane={<PPane><Meta T={T}>karigar dues fall per piece received · 30-day term · money roles</Meta><div style={{ marginTop: 8 }}>{PR_KARIGARS.filter(k => k.due).map(k => <div key={k.id} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 40, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12.5 }}><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{k.name}</span><span style={{ fontFamily: T.fontSerif, fontSize: 15, fontWeight: 600 }}>{prMoney(k.due)}</span></div>)}</div><div style={{ display: 'flex', fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, padding: '8px 0', borderTop: `1px solid ${T.line2}` }}><span style={{ flex: 1 }}>Due this week</span><span style={{ fontFamily: T.fontSerif, fontSize: 16 }}>₹1,10,400</span></div><span style={{ flex: 1 }} /><OutBtn T={T} icon="wallet" style={{ justifyContent: 'center' }}>Karigars › Ledger · raise vouchers</OutBtn></PPane>}>
    <PMain>
      <div style={{ display: 'flex', gap: 10 }}><T.Kpi label="Active orders" value="12" sub="9 with a job running" /><T.Kpi label="Pcs in production" value="1,046" sub="across 12 orders" /><T.Kpi label="FG received today" value="46" sub={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}><Thumb T={T} d={PR_D('3661')} w={14} h={18} r={4} />3661 · PO-1174</span>} tone="ok" /><T.Kpi label="Serviceable jobs" value="9" sub="inputs in stock · 4 waiting on floor" /><T.Kpi label="Delayed jobs" value="7" sub="past a tranche date" tone="danger" /><T.Kpi label="Unassigned" value="11" sub="no karigar yet" /><T.Kpi label="Floor today" value="14 · 9" sub="issues · receives → Hub" /></div>
      <PCard T={T} style={{ marginTop: 12 }}><Sect T={T} style={{ margin: '0 0 6px' }} right={<Meta T={T}>PO calendar · Dye ledger</Meta>}>Arriving this week · purchases and dye lots</Sect>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 20px' }}>{[['PU-0342', 'Surat Textiles', 'Santoon Peach 200 m · Cancan 500 m', 'today', 'PO-1187 waits', 'm3'], ['DC-0034', 'Rafiq Bhai · dye', 'Mono net → C11 Lilac · 150 m', 'Fri 12/09', 'PO-1192 waits', null, 'Lilac'], ['PU-0345', 'Bareilly Works', 'Rasgulla 300 m', 'Wed 10/09', 'PO-1187 stuck on it', 'm9'], ['DC-0035', 'Raja Dyers · dye', 'Mono net → C07 Peach · 120 m', 'Mon 15/09', 'PO-1187 Peach', null, 'Peach'], ['PU-0339', 'Surat Textiles', 'Zari 5 kg', 'Fri 12/09', null, 'm7'], ['DS-0007', 'Rafiq Bhai · dye', 'Mono net → b4 Bottle · 60 m', 'Sun 14/09', null, null, 'Bottle']].map(r => <div key={r[0]} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 36, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12.5 }}><Swatch m={r[5] ? prMat(r[5]) : { tex: 'net', shade: r[6], dye: true }} w={18} h={18} r={5} /><Mono T={T} size={11.5}>{r[0]}</Mono><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[1]} · <span style={{ color: T.ink2 }}>{r[2]}</span></span>{r[4] && <Pill T={T} tone="warn" small>{r[4]}</Pill>}<Meta T={T}>{r[3]}</Meta></div>)}</div></PCard>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginTop: 12 }}>
        <RecStrip T={T} title="High growth · first production" link="Samples › Deployed" sample items={[['S-0409', 'reading 9/15 · high growth · 1 pc back'], ['S-0411', 'activated · 2 pc in Catalogue · orders 14']]} />
        <RecStrip T={T} title="Priority production" link="Orders · Priority production" items={[['2798', 'score 78 · 4 d cover · 12 free'], ['3661', 'score 71 · 9 d cover · 8 free'], ['6002', 'score 84 · out of stock']]} />
        <RecStrip T={T} title="Low-stock reorder" link="+ order from suggestion" items={[['2006', 'selling 3/day · runs out in 11 d'], ['1243', 'selling 2/day · 14 d cover']]} />
        <RecStrip T={T} title="Stop further production" link="Orders · Active · stop" items={[['D9107', 'sell-through 18 % · score 20'], ['1457', 'score 33 · 47 free · PO-1163 running']]} />
      </div>
    </PMain>
  </PShell>;
}

/* ── W1–W3 · Purchase ── */
const PO_ROWS = [['PU-0342', 'Surat Textiles', ['m3', 'm5'], '08/09/26', 'PO-1187', 'Expected today', 'warn', '2798'], ['PU-0345', 'Bareilly Works', ['m9'], '10/09/26', 'PO-1187', 'Production-blocking', 'danger', '2798'], ['PU-0339', 'Surat Textiles', ['m7'], '12/09/26', null, 'Open', 'muted'], ['PU-0331', 'Mumbai Fabrics', ['m6'], '02/09/26', 'PO-1192', 'Overdue 6 d', 'danger', '6002'], ['PU-0328', 'Surat Textiles', ['m14'], '15/09/26', null, 'Partially received', 'warn'], ['PU-0346', 'Surat Textiles', ['m10'], '18/09/26', null, 'Pending approval', 'blue']];
function POCalendar({ T }) {
  const days = Array.from({ length: 35 }, (_, i) => i - 1);
  const ev = { 2: ['PU-0331', 'Mumbai', 'm6', 'danger', '6002', 'PO-1192'], 8: ['PU-0342', 'Surat', 'm3', 'warn', '2798', 'PO-1187'], 10: ['PU-0345', 'Bareilly', 'm9', 'danger', '2798', 'PO-1187'], 12: ['PU-0339', 'Surat', 'm7', 'muted'], 15: ['PU-0328', 'Surat', 'm14', 'warn'], 18: ['PU-0346', 'Surat', 'm10', 'blue'], 20: ['PO-1187 end', null, null, 'end', '2798'], 30: ['PO-1201 end', null, null, 'end', '2006'] };
  return <div style={{ borderRadius: 16, border: `1px solid ${T.line}`, background: T.surface, overflow: 'hidden' }}>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7,1fr)', borderBottom: `1px solid ${T.line}` }}>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => <span key={d} style={{ padding: '6px 8px', fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>{d}</span>)}</div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7,1fr)' }}>{days.map((d, i) => { const inM = d >= 1 && d <= 30; const e = inM ? ev[d] : null; const tone = e && (e[3] === 'danger' ? T.danger : e[3] === 'warn' ? T.warn : e[3] === 'blue' ? T.blue : e[3] === 'end' ? T.accent : T.ink2); return <div key={i} style={{ height: 82, padding: 6, borderRight: i % 7 < 6 ? `1px solid ${T.line}` : 0, borderBottom: i < 28 ? `1px solid ${T.line}` : 0, background: d === 8 ? T.accentSoft : 'transparent', boxSizing: 'border-box', overflow: 'hidden' }}><div style={{ fontFamily: T.fontUI, fontSize: 11, color: inM ? T.ink2 : T.ink3, fontWeight: d === 8 ? 600 : 400 }}>{inM ? d : ''}</div>{e && <div style={{ marginTop: 5, padding: '3px 6px', borderRadius: 7, background: e[3] === 'end' ? T.accentSoft : T.chipBg, borderLeft: `2px solid ${tone}` }}><div style={{ display: 'flex', alignItems: 'center', gap: 4, fontFamily: T.fontMono, fontSize: 10, color: tone, whiteSpace: 'nowrap' }}>{e[2] ? <Swatch m={prMat(e[2])} w={12} h={12} r={3} /> : <Thumb T={T} d={PR_D(e[4])} w={12} h={15} r={3} />}{e[0]}</div>{e[1] && <div style={{ fontFamily: T.fontUI, fontSize: 10, color: T.ink3, marginTop: 1, display: 'flex', alignItems: 'center', gap: 4, whiteSpace: 'nowrap' }}>{e[1]}{e[5] && <><Thumb T={T} d={PR_D(e[4])} w={10} h={13} r={2} />→ {e[5]}</>}</div>}</div>}</div>; })}</div>
  </div>;
}
const POPane = ({ T }) => <PPane>
  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Pill T={T} tone="warn" small>Expected today</Pill><Pill T={T} tone="ok" small>Approved · PM</Pill><Meta T={T}>raised 28/08/26 · Surat book</Meta></div>
  <div style={{ marginTop: 10 }}>{[['m3', 200, 62], ['m5', 500, 28]].map(([id, q, r]) => { const m = prMat(id); return <div key={id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '7px 0', borderTop: `1px solid ${T.line}` }}><Swatch m={m} w={34} h={40} r={8} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12.5 }}>{prMatName(m)}<Meta T={T} style={{ display: 'block' }}>{q} {m.unit} × ₹{r} <Lock T={T} /></Meta></span><span style={{ fontFamily: T.fontSerif, fontSize: 15, fontWeight: 600 }}>{prMoney(q * r)}</span></div>; })}</div>
  <div style={{ marginTop: 10, padding: '8px 10px', borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><div style={{ display: 'flex', alignItems: 'center', gap: 6, fontWeight: 600, color: T.ink }}>Linked <DesignChip T={T} code="2798" /> · PO-1187</div>Stitching waits on Cancan · due 20/09/26 · 85 pcs</div>
  <Sect T={T}>Inwards</Sect>
  {[['GRN-0418', '08/09/26', '680 units · variance −20 m', 'awaiting approval']].map(r => <div key={r[0]} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 36, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><Mono T={T} size={11.5}>{r[0]}</Mono><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[2]}</span><Pill T={T} tone="blue" small>{r[3]}</Pill></div>)}
  <div style={{ marginTop: 10, display: 'flex', gap: 6, alignItems: 'center' }}><span style={{ width: 56, height: 56, borderRadius: 10, background: T.chipBg, display: 'grid', placeItems: 'center' }}><Ic name="image" size={18} color={T.ink3} /></span><Meta T={T}>photo from WhatsApp · 28/08 14:02</Meta></div>
  <span style={{ flex: 1 }} /><div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} icon="printer" small>Print</OutBtn><OutBtn T={T} icon="message-circle" small>Send</OutBtn><span style={{ flex: 1 }} /><T.Btn small icon="package-check" style={{ height: 36 }}>Take inward</T.Btn></div>
</PPane>;
const POBar = ({ T, sort = 'Expected arrival', right }) => <PBar T={T} right={right}><T.Chip icon="search" outline>Supplier, material, PO</T.Chip><Caret T={T}>{sort}</Caret>{['Due this week', 'Overdue', 'Production-blocking', 'Open', 'Partially received'].map((c, i) => <T.Chip key={c} on={i === 2} outline={i !== 2} x={i === 2}>{c}</T.Chip>)}<AllFilters T={T} /><OutBtn T={T} small icon="plus">New PO</OutBtn></PBar>;
const PO_TABS = [['Calendar', null, 'calendar'], ['List', 6, 'list'], ['Past', 128, 'history']];
function WebPPurchaseOrders({ T }) {
  return <PShell T={T} section="Purchase orders" active="Purchase" crumb={['Production', 'Purchase', 'Orders']} paneTitle="PU-0342 · Surat Textiles" pane={<POPane T={T} />}>
    <ViewTabs T={T} tabs={PO_TABS} active="Calendar" />
    <PMain><POBar T={T} right={<Meta T={T}>September 2026 · 6 open · 2 production-blocking</Meta>} /><POCalendar T={T} /></PMain>
  </PShell>;
}
const POList = ({ T, on = 0 }) => <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} onRow={on} cols={[['PO', 76, 'left'], ['Supplier · lines'], ['Expected', 80, 'left'], ['Linked order', 150, 'left'], ['Value ₹', 84], ['State', 150, 'left']]} rows={PO_ROWS.map(r => [<Mono T={T} size={11.5}>{r[0]}</Mono>, <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, minWidth: 0 }}>{r[2].map(id => <Swatch key={id} m={prMat(id)} w={26} h={30} r={7} />)}<span style={{ minWidth: 0 }}><div>{r[1]}</div><Meta T={T} style={{ display: 'block', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[2].map(id => prMatName(prMat(id))).join(' · ')}</Meta></span></span>, r[3].slice(0, 5), r[4] ? <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5 }}><DesignChip T={T} code={r[7]} small /><Meta T={T}>· {r[4]}</Meta></span> : <Meta T={T}>—</Meta>, <span>{prMoney([26400, 3500, 185000, 4400, 125000, 6200][PO_ROWS.indexOf(r)])}<Lock T={T} /></span>, <Pill T={T} tone={r[6]} fill={r[6] === 'danger'} small>{r[5]}</Pill>])} /><div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderTop: `1px solid ${T.line}` }}><Meta T={T}>6 open · sorted by expected arrival · rates for money roles</Meta></div></PCard>;
function WebPPOList({ T }) {
  return <PShell T={T} section="Purchase orders" active="Purchase" crumb={['Production', 'Purchase', 'Orders', 'List']} paneTitle="PU-0342 · Surat Textiles" pane={<POPane T={T} />}>
    <ViewTabs T={T} tabs={PO_TABS} active="List" />
    <PMain><POBar T={T} sort="Expected arrival" right={<Meta T={T}>state pill + up to two flags per row</Meta>} /><POList T={T} /></PMain>
  </PShell>;
}
function NewPOPane({ T }) {
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Mono T={T}>PU-0347 · auto</Mono><Meta T={T}>Surat purchase book</Meta></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><Field T={T} label="Supplier" value="Surat Textiles · score 81" caret small /><Field T={T} label="Book" value="Surat purchase" caret small w={120} /></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Expected" value="18/09/26" icon="calendar" small /><Field T={T} label="Link to a production order" value={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 5 }}><DesignChip T={T} code="2798" small /> · PO-1187 · Stitching due 20/09</span>} caret small /></div>
    <PrLab T={T} style={{ marginTop: 12 }}>Lines</PrLab>
    <div style={{ borderRadius: 12, border: `1px solid ${T.line}`, overflow: 'hidden' }}>{[['m10', 300, 62], ['m5', 500, 28]].map(([id, q, r], i) => { const m = prMat(id); return <div key={id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '7px 8px', borderTop: i ? `1px solid ${T.line}` : 0 }}><Swatch m={m} w={30} h={36} r={7} /><span style={{ flex: 1, minWidth: 0, fontFamily: T.fontUI, fontSize: 12 }}>{prMatName(m)}<Meta T={T} style={{ display: 'block' }}>{m.code} · {m.stock} {m.unit} in stock</Meta></span><span style={{ width: 62, height: 30, borderRadius: 8, border: `1px solid ${T.line2}`, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12, fontWeight: 600 }}>{q} {m.unit}</span><span style={{ width: 54, height: 30, borderRadius: 8, border: `1px solid ${T.line2}`, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12 }}>₹{r}</span></div>; })}<div style={{ display: 'flex', alignItems: 'center', padding: '6px 8px', borderTop: `1px solid ${T.line}` }}><OutBtn T={T} small icon="plus">Add a line</OutBtn><span style={{ flex: 1 }} /><Meta T={T}>rates · money roles</Meta></div></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><span className="press" style={{ width: 64, height: 64, borderRadius: 12, border: `1px dashed ${T.line2}`, background: T.chipBg, display: 'grid', placeItems: 'center', color: T.ink2 }}><Ic name="camera" size={18} /></span><span style={{ flex: 1 }}><Meta T={T} style={{ display: 'block', whiteSpace: 'normal', lineHeight: 1.35 }}>photos from WhatsApp / Telegram · 2 attached · the supplier gets the PO on WhatsApp with the pictures</Meta><Field T={T} label="Narration" ph="e.g. same lot as PU-0319" small style={{ marginTop: 6 }} /></span></div>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Meta T={T}>PM approves</Meta><span style={{ flex: 1 }} /><OutBtn T={T} small>Save draft</OutBtn><T.Btn small icon="send" style={{ height: 34 }}>Raise PO · send</T.Btn></div>
  </PPane>;
}
function WebPPONew({ T }) {
  return <PShell T={T} section="Purchase orders" active="Purchase" crumb={['Production', 'Purchase', 'Orders', 'New PO']} tab="New purchase order" paneTitle="New purchase order" pane={<NewPOPane T={T} />}>
    <ViewTabs T={T} tabs={PO_TABS} active="List" />
    <PMain><POBar T={T} right={<Meta T={T}>the pane raises the PO · the list stays in view</Meta>} /><POList T={T} on={null} /></PMain>
  </PShell>;
}
const INW_TABS = [['New', null, 'plus'], ['Past', 128, 'history']];
const SupplierPane = ({ T }) => <PPane>
  <Meta T={T}>what the approver sees</Meta>
  <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><T.Kpi label="Supplier score" value="81" small /><T.Kpi label="Overdue" value="₹0" small tone="ok" /><T.Kpi label="GRNs FY" value="34" small /></div>
  <Sect T={T}>Last purchases</Sect>
  {[['PU-0328', '22/08/26', 'Butta kaam satin · 40 pc', '₹50,000'], ['PU-0319', '10/08/26', 'Santoon Sky · 300 m', '₹18,600'], ['PU-0311', '30/07/26', 'BKS 41 Purple · 45 pc', '₹21,600']].map(r => <div key={r[0]} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 38, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><Mono T={T} size={11.5}>{r[0]}</Mono><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', color: T.ink2 }}>{r[2]}</span><span style={{ fontFamily: T.fontSerif, fontSize: 14, fontWeight: 600 }}>{r[3]}</span></div>)}
  <span style={{ flex: 1 }} />
  <div style={{ padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Pushed to accounts on approval · gate token GT-260908-019 raised by the guard · group firms appear under Supplier as "Radhika Collection · inbound"</div>
</PPane>;
function WebPInward({ T }) {
  return <PShell T={T} section="Purchase inward" active="Purchase" crumb={['Production', 'Purchase', 'Inward', 'New']} paneTitle="Surat Textiles" pane={<SupplierPane T={T} />}>
    <ViewTabs T={T} tabs={INW_TABS} active="New" />
    <PMain>
      <PBar T={T}><T.Chip icon="search" outline>Find a purchase order · supplier, material, date</T.Chip>{['PO-linked', 'Ad hoc'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0}>{c}</T.Chip>)}<span style={{ flex: 1 }} /><Meta T={T}>PU-0342 picked · lines pre-filled</Meta></PBar>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', gap: 10 }}><Field T={T} label="Supplier" value="Surat Textiles" caret /><Field T={T} label="Book" value="Surat purchase" caret /><Field T={T} label="Supplier invoice no · date" value="ST/26-27/0891 · 08/09/26" /><Field T={T} label="Inward no · date" value="GRN-0418 · 08/09/26" icon="calendar" /><Field T={T} label="Consignee firm" value="Shree Radha Studio" caret /></div>
      <PCard T={T} style={{ marginTop: 10, padding: 0, overflow: 'hidden' }}>
        <Tbl T={T} cols={[['Material'], ['Ordered', 72], ['Received', 84], ['Unit', 40, 'left'], [<span>Rate ₹<Lock T={T} /></span>, 66], [<span>Value ₹<Lock T={T} /></span>, 84], ['Variance', 116, 'left'], ['Lot photo', 80, 'left']]} rows={[['m3', 200, 200, 62], ['m5', 500, 480, 28]].map(([id, o, g, r]) => { const m = prMat(id); return [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Swatch m={m} w={32} h={38} r={8} /><span>{prMatName(m)}<Meta T={T} style={{ display: 'block' }}>{m.code} · {m.group}</Meta></span></span>, o, <span style={{ display: 'inline-block', width: 64, height: 30, lineHeight: '28px', borderRadius: 8, border: `1px solid ${g < o ? T.warn : T.line2}`, textAlign: 'center', fontWeight: 600 }}>{g}</span>, m.unit, r, prMoney(g * r), g < o ? <Pill T={T} tone="warn" small>short {o - g} {m.unit}</Pill> : <Meta T={T}>none</Meta>, <span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, color: T.ink2, fontSize: 11.5 }}><Ic name="camera" size={13} />add</span>]; })} />
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderTop: `1px solid ${T.line}` }}><OutBtn T={T} small icon="plus">Add a line</OutBtn><OutBtn T={T} small icon="plus">New material · from the lot</OutBtn><span style={{ flex: 1 }} /><Meta T={T}>2 lines · 680 units</Meta><span style={{ fontFamily: T.fontSerif, fontSize: 18, fontWeight: 600 }}>{prMoney(200 * 62 + 480 * 28)}</span></div>
      </PCard>
      <PCard T={T} style={{ marginTop: 10 }} alt>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ fontFamily: T.fontDisplay, fontSize: 15, fontWeight: 600 }}>Accounts · money roles</span><Meta T={T}>the voucher pushed to accounts · the warehouse executive sees an invoice-photo tile here instead</Meta><span style={{ flex: 1 }} /><Ic name="chevron-up" size={14} color={T.ink3} /></div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 8, marginTop: 8 }}><Field T={T} label="Terms of payment" value="30 days" caret small /><Field T={T} label="Freight inward ₹" value="800" small /><Field T={T} label="Additional cost ₹" value="0" small /><Field T={T} label="Discount" value="0 %" small /><Field T={T} label="Vendor broker · agency" value="—" caret small /><Field T={T} label="GST by place of supply" value="IGST 5 % · Gujarat" caret small /></div>
        <div style={{ display: 'flex', gap: 14, marginTop: 8, fontFamily: T.fontUI, fontSize: 12, color: T.ink2, flexWrap: 'wrap' }}><span>Taxable ₹26,640</span><span>IGST ₹1,332</span><span>Round off −₹0.30</span><b style={{ color: T.ink }}>Gross total ₹27,972</b></div>
      </PCard>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10 }}><Field T={T} label="Narration" ph="e.g. 20 m Cancan short, credit note to follow" /><span style={{ alignSelf: 'flex-end', display: 'flex', gap: 8 }}><OutBtn T={T}>Save draft</OutBtn><T.Btn small icon="check" style={{ height: 38 }}>Take inward · send to approval</T.Btn></span></div>
    </PMain>
  </PShell>;
}
const GRN_ROWS = [['GRN-0418', '08/09/26', 'Surat Textiles', 'PU-0342', ['m3', 'm5'], '680', 25840, 'Cancan −20 m', 'Awaiting approval', 'GT-260908-019'], ['GRN-0417', '06/09/26', 'Local market', null, ['m8'], '300 m', 2700, null, 'Approved', 'GT-260906-002'], ['GRN-0416', '30/08/26', 'Raja Dyers', 'DC-0029', ['m1'], '218 m', null, '2 m loss', 'Dye receive', 'GT-260830-014'], ['GRN-0415', '24/08/26', 'Surat Textiles', 'PU-0330', ['m3'], '120 m', 7440, null, 'Approved', 'GT-260824-006'], ['GRN-0414', '22/08/26', 'Surat Textiles', 'PU-0328', ['m14'], '10 pc of 40', 12500, 'partial', 'Approved', 'GT-260822-009']];
function WebPInwardPast({ T }) {
  return <PShell T={T} section="Purchase inward" active="Purchase" crumb={['Production', 'Purchase', 'Inward', 'Past']} paneWidth={300} paneTitle="GRN-0418 · Surat Textiles" pane={<PPane>
    <div style={{ display: 'flex', gap: 8 }}><span style={{ width: 84, height: 84, borderRadius: 12, background: T.chipBg, display: 'grid', placeItems: 'center' }}><Ic name="image" size={22} color={T.ink3} /></span><span style={{ flex: 1 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 18, fontWeight: 600 }}>GRN-0418</div><Meta T={T} style={{ display: 'block' }}>08/09/26 · PU-0342 · ST/26-27/0891 · lot photo</Meta><div style={{ marginTop: 6, display: 'flex', gap: 5 }}><Pill T={T} tone="blue" small>Awaiting approval</Pill><Pill T={T} tone="warn" small>Variance</Pill></div></span></div>
    <div style={{ marginTop: 10 }}>{[['m3', '200 m of 200'], ['m5', '480 m of 500']].map(([id, q]) => { const m = prMat(id); return <div key={id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderTop: `1px solid ${T.line}` }}><Swatch m={m} w={30} h={36} r={7} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12.5 }}>{prMatName(m)}</span><Meta T={T}>{q}</Meta></div>; })}</div>
    <div style={{ marginTop: 10, display: 'flex', gap: 6, alignItems: 'center' }}><GateToken T={T} n="GT-260908-019" done /><Meta T={T}>accounts push on approval</Meta></div>
    <span style={{ flex: 1 }} /><div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} small icon="undo-2">Return against this</OutBtn><OutBtn T={T} small icon="printer">Re-print</OutBtn></div>
  </PPane>}>
    <ViewTabs T={T} tabs={INW_TABS} active="Past" />
    <PMain>
      <PBar T={T} right={<Meta T={T}>128 inwards · this FY · Hub › Purchase report</Meta>}><T.Chip icon="search" outline>Supplier, material, GRN, date</T.Chip><Caret T={T}>Newest</Caret>{['PO-linked', 'Ad hoc', 'Pending approval', 'Variance', 'Today'].map((c, i) => <T.Chip key={c} on={i === 2} outline={i !== 2} x={i === 2}>{c}</T.Chip>)}<AllFilters T={T} /></PBar>
      <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} onRow={0} cols={[['GRN', 80, 'left'], ['Date', 54, 'left'], ['Supplier · lines'], ['Against', 72, 'left'], ['Qty', 72, 'left'], [<span>Value ₹<Lock T={T} /></span>, 74], ['Variance', 100, 'left'], ['Approval', 118, 'left'], ['Gate token', 112, 'left']]} rows={GRN_ROWS.map(r => [<Mono T={T} size={11.5}>{r[0]}</Mono>, r[1].slice(0, 5), <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, minWidth: 0 }}>{r[4].map(id => <Swatch key={id} m={prMat(id)} w={24} h={28} r={6} />)}<span style={{ minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[2]}<Meta T={T}> · {r[4].map(id => prMatName(prMat(id))).join(' · ')}</Meta></span></span>, r[3] ? <Mono T={T} size={11}>{r[3]}</Mono> : <Meta T={T}>ad hoc</Meta>, r[5], r[6] ? prMoney(r[6]) : <Meta T={T}>dye lot</Meta>, r[7] ? <Pill T={T} tone="warn" small>{r[7]}</Pill> : <Meta T={T}>none</Meta>, <Pill T={T} tone={r[8] === 'Approved' ? 'ok' : r[8] === 'Dye receive' ? 'muted' : 'blue'} small>{r[8]}</Pill>, <GateToken T={T} n={r[9]} done />])} /></PCard>
    </PMain>
  </PShell>;
}
function WebPReturn({ T }) {
  return <PShell T={T} section="Purchase return" active="Purchase" crumb={['Production', 'Purchase', 'Return']} paneTitle="Credit note · building" pane={<PPane>
    <div style={{ padding: 12, borderRadius: 14, border: `1px solid ${T.line2}`, background: T.surface2 }}><div style={{ display: 'flex', alignItems: 'baseline' }}><span style={{ fontFamily: T.fontDisplay, fontSize: 16, fontWeight: 600 }}>Purchase return</span><span style={{ flex: 1 }} /><Mono T={T} size={11.5}>PR-0044 · auto</Mono></div><Meta T={T} style={{ display: 'block', marginTop: 2 }}>against GRN-0418 · Surat Textiles · ST/26-27/0891</Meta>
      <div style={{ marginTop: 10, fontFamily: T.fontUI, fontSize: 12.5 }}>{[['Cancan · CN01', '40 m × ₹28', 1120]].map(r => <div key={r[0]} style={{ display: 'flex', gap: 8, padding: '6px 0', borderTop: `1px solid ${T.line}` }}><span style={{ flex: 1 }}>{r[0]}<Meta T={T} style={{ display: 'block' }}>{r[1]}</Meta></span><span style={{ fontFamily: T.fontSerif, fontSize: 15, fontWeight: 600 }}>{prMoney(r[2])}</span></div>)}</div>
      <div style={{ display: 'flex', gap: 8, marginTop: 8, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ flex: 1, color: T.ink2 }}>IGST 5 %</span><span>₹56</span></div>
      <div style={{ display: 'flex', gap: 8, marginTop: 6, fontFamily: T.fontUI, fontSize: 13, fontWeight: 600 }}><span style={{ flex: 1 }}>Credit note</span><span style={{ fontFamily: T.fontSerif, fontSize: 18 }}>₹1,176</span></div>
      <Meta T={T} style={{ display: 'block', marginTop: 6 }}>E-invoice · IRN pending · Ack no · date on push</Meta></div>
    <Meta T={T} style={{ display: 'block', marginTop: 8 }}>issued with the return · goes to accounts approval before the push · money roles</Meta><span style={{ flex: 1 }} /><OutBtn T={T} small icon="printer" style={{ justifyContent: 'center' }}>Print credit note + delivery note</OutBtn>
  </PPane>}>
    <ViewTabs T={T} tabs={[['New', null, 'plus'], ['Past', 9, 'history']]} active="New" />
    <PMain>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', gap: 10 }}><Field T={T} label="Inward to return against" value="GRN-0418 · Surat Textiles · 08/09/26" caret /><Field T={T} label="Reason" value="Damaged · water marks" caret /><Field T={T} label="Despatch through" value="Patel Parcel Service" caret /><Field T={T} label="Delivery note no" value="DN-0044 · auto" /><Field T={T} label="Gate token" value="GT-260908-026 · auto" /></div>
      <PCard T={T} style={{ marginTop: 12, padding: 0, overflow: 'hidden' }}><Tbl T={T} cols={[['Material'], ['Received', 80], ['Return qty', 90], ['Unit', 44, 'left'], [<span>Rate ₹<Lock T={T} /></span>, 70], [<span>Value ₹<Lock T={T} /></span>, 90], ['Reason', 160, 'left']]} rows={[['m3', 200, 0], ['m5', 480, 40]].map(([id, g, r]) => { const m = prMat(id); return [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Swatch m={m} w={32} h={38} r={8} /><span>{prMatName(m)}</span></span>, g, <span style={{ display: 'inline-block', width: 64, height: 30, lineHeight: '28px', borderRadius: 8, border: `1px solid ${r ? T.accentLine : T.line2}`, textAlign: 'center', fontWeight: 600 }}>{r}</span>, m.unit, m.price, prMoney(r * m.price), r ? 'Damaged · water marks' : <Meta T={T}>—</Meta>]; })} /></PCard>
      <div style={{ display: 'flex', gap: 8, marginTop: 12, justifyContent: 'flex-end' }}><OutBtn T={T}>Cancel</OutBtn><T.Btn small icon="undo-2" style={{ height: 38 }}>Raise return and credit note</T.Btn></div>
      <Sect T={T} right={<Meta T={T}>Hub › Purchase return report</Meta>}>Past returns · 9</Sect>
      <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} cols={[['Return', 80, 'left'], ['Date', 70, 'left'], ['Supplier · material'], ['Against', 90, 'left'], ['Qty', 70], [<span>Credit ₹<Lock T={T} /></span>, 80], ['Credit note', 150, 'left']]} rows={[['PR-0043', '28/08/26', 'Mumbai Fabrics · Mono net · Mono', 'GRN-0409', '60 m', 2772, 'CN pushed · ack 2/9'], ['PR-0042', '14/08/26', 'Bareilly Works · Rasgulla', 'GRN-0402', '100 m', 3675, 'CN pushed · ack 16/8']].map(r => [<Mono T={T} size={11.5}>{r[0]}</Mono>, r[1].slice(0, 5), r[2], <Mono T={T} size={11}>{r[3]}</Mono>, r[4], prMoney(r[5]), <Pill T={T} tone="ok" small>{r[6]}</Pill>])} /></PCard>
    </PMain>
  </PShell>;
}

/* ── W4 · Materials catalogue ── */
function MatPane({ T, m }) {
  return <PPane style={{ padding: 0 }}>
    <div style={{ display: 'flex', gap: 4, padding: 8, background: T.bg2 }}><Swatch m={m} w={150} h={112} r={12} /><div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 4 }}>{[m.lastIn, '12/08/26'].map((d, i) => <span key={i} style={{ position: 'relative', borderRadius: 8, overflow: 'hidden' }}><Swatch m={m} w="100%" h={54} r={8} style={{ width: '100%', filter: i ? 'saturate(.8)' : 'none' }} /><span style={{ position: 'absolute', left: 4, bottom: 3, fontFamily: T.fontUI, fontSize: 9, color: '#fff', textShadow: '0 1px 2px rgba(0,0,0,.6)' }}>lot {d.slice(0, 5)}</span></span>)}<span className="press" style={{ borderRadius: 8, border: `1px dashed ${T.line2}`, display: 'grid', placeItems: 'center', color: T.ink3 }}><Ic name="camera" size={14} /></span><span className="press" style={{ borderRadius: 8, background: T.chipBg, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 9.5, color: T.ink2, textAlign: 'center', padding: 4 }}>use on job cards</span></div></div>
    <div style={{ padding: '10px 14px 14px', flex: 1, minHeight: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
      <Meta T={T} style={{ display: 'block', marginBottom: 4 }}>photo stand-ins · lot photos from inward land here · primary set in Studio</Meta>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}><span style={{ fontFamily: T.fontDisplay, fontSize: 22, fontWeight: 600 }}>{m.name}</span><span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontFamily: T.fontUI, fontSize: 12.5, color: T.ink2 }}><span style={{ width: 10, height: 10, borderRadius: 3, background: prShade(m.shade) }} />{m.shade}</span><span style={{ flex: 1 }} /><StockWord T={T} m={m} /></div>
      <Meta T={T} style={{ display: 'block', marginTop: 2 }}>{m.code} · {m.group} · {m.unit} · {m.dye ? m.dye.dyer : m.sup} · {m.city}{m.barcode !== false && ' · barcode 8901 2345'}</Meta>
      <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><T.Kpi label="On hand" value={`${m.stock} ${m.unit}`} small tone={m.out ? 'danger' : undefined} /><T.Kpi label="On order" value={m.order ? `${m.order} ${m.unit}` : '—'} small /><T.Kpi label="Consumed · month" value={`${m.consumed || Math.round(m.stock * .4)} ${m.unit}`} small /></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="bell" size={12} color={T.ink3} />{m.reorder ? <span>Reorder level {m.reorder} {m.unit} · <span className="press" style={{ color: T.accent }}>edit</span></span> : <span>No reorder level yet · <span className="press" style={{ color: T.accent }}>set one</span> · Low shows only with a level</span>}<span style={{ flex: 1 }} /><span>Rate avg ₹{m.price || '—'}<Lock T={T} /></span></div>
      {m.dye && <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 12, background: T.accentSoft, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><b style={{ color: T.ink }}>Lineage</b> · {m.dye.from} → {m.dye.dyer} · cut order {m.dye.cut} · shade {m.dye.code} · received {m.lastIn}</div>}
      <Sect T={T} right={<Meta T={T}>accounts voucher on each row</Meta>}>Stock ledger</Sect>
      {[[m.lastIn, m.dye ? 'Dye receive · ' + m.dye.cut : 'Inward · GRN-04' + (m.id.slice(1) + 10), '+' + (m.dye ? m.stock : Math.round(m.stock * .6)), m.unit, 'OE/PI/41'], ['04/09/26', 'Issue · PO-1187 · Embroidery', '−10', m.unit, 'OE/MI/58'], ['26/08/26', 'Issue · PO-1187 · Embroidery', '−12.5', m.unit, 'OE/MI/52']].map((r, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 32, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><Meta T={T}>{r[0]}</Meta><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[1]}</span><Mono T={T} size={10} weight={500} color={T.ink3}>{r[4]}</Mono><span style={{ fontWeight: 600, color: r[2][0] === '+' ? T.ok : T.ink }}>{r[2]} {r[3]}</span></div>)}
      <Sect T={T}>Used in</Sect>
      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>{['2798', '6002', '4566'].slice(0, Math.max(1, m.used % 4)).map(c => <span key={c} className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '3px 8px 3px 3px', borderRadius: 999, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5 }}><Thumb T={T} d={PR_D(c)} w={22} h={26} r={6} /><span style={{ fontFamily: T.fontDisplay, fontSize: 14, fontWeight: 600 }}>{c}</span></span>)}</div>
      <span style={{ flex: 1 }} />
      <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><OutBtn T={T} small icon="shopping-cart">Raise PO</OutBtn><OutBtn T={T} small icon="git-branch">Add to a recipe</OutBtn><OutBtn T={T} small icon="printer">Label</OutBtn><span style={{ flex: 1 }} /><Meta T={T}>Dispatch › Stock › Material</Meta></div>
    </div>
  </PPane>;
}
const MAT_TABS = [['Catalogue', 14, 'layers'], ['Dye ledger', 3, 'droplets']];
const MatBar = ({ T }) => <PBar T={T} right={<Meta T={T}>14 materials · 22 shades · sorted by last inward</Meta>}><T.Chip icon="search" outline>Material, shade, code, supplier</T.Chip><Caret T={T}>Last inward · newest</Caret>{['Low', 'Out', 'On order', 'Used in active jobs', 'Dye WIP'].map(c => <T.Chip key={c} outline>{c}</T.Chip>)}<Caret T={T}>Group</Caret><Caret T={T}>Supplier</Caret><Caret T={T}>Source</Caret><AllFilters T={T} /><OutBtn T={T} small icon="plus">New material</OutBtn></PBar>;
function WebPMaterials({ T }) {
  return <PShell T={T} section="Materials" active="Materials" crumb={['Production', 'Materials', 'Catalogue']} paneTitle="Mono net · Sky" pane={<MatPane T={T} m={prMat('m2')} />}>
    <ViewTabs T={T} tabs={MAT_TABS} active="Catalogue" right={<PTabs T={T} tabs={[['Grid', 'layout-grid'], ['List', 'list']]} on="Grid" />} />
    <PMain><MatBar T={T} /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, minmax(0,1fr))', gap: 12 }}>{PR_MATS.slice(0, 10).map((m, i) => <MatCard key={m.id} T={T} m={m} on={i === 1} />)}</div></PMain>
  </PShell>;
}
function NewMaterialPane({ T }) {
  const m = { tex: 'satin', shade: 'Wine' };
  return <PPane style={{ padding: '10px 12px 12px' }}>
    <div style={{ display: 'flex', gap: 8 }}><span className="press" style={{ width: 84, height: 96, borderRadius: 12, border: `1px dashed ${T.line2}`, background: T.chipBg, display: 'grid', placeItems: 'center', color: T.ink2 }}><span style={{ textAlign: 'center', fontFamily: T.fontUI, fontSize: 10.5 }}><Ic name="camera" size={18} /><div>photo · from WhatsApp</div></span></span><span style={{ flex: 1, display: 'grid', gap: 8 }}><Field T={T} label="Material name" value="Nidha satin" small /><Field T={T} label="Group" value="Base fabric" caret small /></span></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Category tags" value="satin · shiny · lining" caret small /><Field T={T} label="Unit" value="m" caret small w={70} /></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Supplier · code" value="Surat Textiles · SUR-014" caret small /><Field T={T} label="Source" value="Surat · domestic" caret small w={130} /></div>
    <PrLab T={T} style={{ marginTop: 12 }}>Shades · one material, many shades, one master each</PrLab>
    <div style={{ borderRadius: 12, border: `1px solid ${T.line}`, overflow: 'hidden' }}>{[['NS01', 'Wine'], ['NS03', 'Mehroon'], ['NS04', 'Rani']].map(([c, s], i) => <div key={c} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 8px', borderTop: i ? `1px solid ${T.line}` : 0 }}><Swatch m={{ tex: 'satin', shade: s }} w={28} h={28} r={7} /><Mono T={T} size={11.5}>{c}</Mono><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12.5 }}>{s}</span><Ic name="x" size={12} color={T.ink3} /></div>)}<div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '6px 8px', borderTop: `1px solid ${T.line}` }}><OutBtn T={T} small icon="plus">Add a shade</OutBtn><Meta T={T}>code auto · pick the swatch colour</Meta></div></div>
    <div style={{ display: 'flex', gap: 8, marginTop: 10 }}><Field T={T} label="Reorder level" value="100 m" small /><Field T={T} label={<span>Purchase rate ₹<Lock T={T} /></span>} value="₹78" small /><Field T={T} label="General tags" value="lining · festive" small /></div>
    <Meta T={T} style={{ display: 'block', marginTop: 8 }}>alias, print name, tax category and MRP stay in Hub › Masters</Meta>
    <span style={{ flex: 1 }} />
    <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}><Meta T={T}>lands in the catalogue as "no inward yet"</Meta><span style={{ flex: 1 }} /><T.Btn small icon="check" style={{ height: 34 }}>Save material · 3 shades</T.Btn></div>
  </PPane>;
}
function WebPMaterialNew({ T }) {
  return <PShell T={T} section="Materials" active="Materials" crumb={['Production', 'Materials', 'Catalogue', 'New material']} tab="New material" paneTitle="New material" pane={<NewMaterialPane T={T} />}>
    <ViewTabs T={T} tabs={MAT_TABS} active="Catalogue" right={<PTabs T={T} tabs={[['Grid', 'layout-grid'], ['List', 'list']]} on="List" />} />
    <PMain><MatBar T={T} /><PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} cols={[['Material · shade'], ['Group', 100, 'left'], ['On hand', 74], ['On order', 74], ['Last inward', 84, 'left'], ['Supplier', 120, 'left'], ['Used in', 60], [<span>Rate<Lock T={T} /></span>, 60]]} rows={PR_MATS.slice(0, 11).map(m => [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, minWidth: 0 }}><Swatch m={m} w={28} h={34} r={7} /><span style={{ minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{prMatName(m)}<Meta T={T}> · {m.code}</Meta></span><StockWord T={T} m={m} /></span>, m.group, <span style={{ color: m.out ? T.danger : T.ink }}>{m.stock} {m.unit}</span>, m.order ? `${m.order} ${m.unit}` : '—', m.lastIn.slice(0, 5), m.dye ? m.dye.dyer : m.sup, m.used, m.price ? '₹' + m.price : '—'])} /></PCard></PMain>
  </PShell>;
}

/* ── W5–W7 · Dye ledger ── */
const DyerRail = ({ T, on }) => <div style={{ width: 184, flex: 'none', borderRight: `1px solid ${T.line}`, background: T.surface, padding: '12px 12px', overflow: 'hidden' }}>
  <div style={{ fontFamily: T.fontDisplay, fontSize: 16, fontWeight: 600 }}>Dyers</div><Meta T={T} style={{ display: 'block', marginTop: 2 }}>undyed fabric out with them</Meta>
  {PR_DYERS.map((dy, i) => { const k = prK(dy.k); return <div key={dy.k} className="press" style={{ marginTop: 10, padding: 10, borderRadius: 14, background: on === i ? T.accentSoft : T.surface2, border: `1px solid ${on === i ? T.accentLine : T.line}` }}><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><span style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{k.name}</span><span style={{ fontFamily: T.fontUI, fontSize: 11, fontWeight: 600, color: k.score >= 70 ? T.ok : T.warn }}>{k.score}</span></div>{dy.bal.map(([m, q, u]) => { const res = m.startsWith('Mono') ? (dy.k === 'k6' ? 120 : 210) : 0; return <div key={m} style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Swatch m={{ tex: m.startsWith('Mono') ? 'net' : 'satin', shade: 'Mono' }} w={18} h={18} r={5} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{m}</div><div style={{ fontSize: 10.5, color: T.ink3 }}>free {(q - res).toLocaleString('en-IN')} {u}</div></span><b style={{ color: T.ink, fontVariantNumeric: 'tabular-nums' }}>{q.toLocaleString('en-IN')} {u}</b></div>; })}</div>; })}
  <div style={{ marginTop: 12, padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11, color: T.ink2 }}>Balance = bulk issued − dyed lots received − loss · cut orders reserve, receipts move the balance</div>
</div>;
const CutRows = ({ T, rows = PR_CUTS, on }) => <Tbl T={T} onRow={on} cols={[['Cut order', 74, 'left'], ['Material → shade · for'], ['Ordered · recd', 92], ['Balance', 64], ['Due', 48, 'left'], ['State', 84, 'left']]} rows={rows.map(c => [<span><Mono T={T} size={11.5}>{c.no}</Mono>{c.single && <Meta T={T} style={{ display: 'block', fontSize: 10 }}>single</Meta>}</span>, <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, minWidth: 0 }}><Swatch m={{ tex: c.mat.startsWith('Mono') ? 'net' : 'satin', shade: c.shade, dye: c.state === 'Received' }} w={30} h={30} r={8} /><span style={{ minWidth: 0 }}><div style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{c.mat} → <b>{c.code} {c.shade}</b></div><div style={{ display: 'flex', alignItems: 'center', gap: 4, marginTop: 1 }}><Meta T={T}>{prK(c.dyer).name.split(' ')[0]} · for</Meta><DesignChip T={T} code={c.forCode} small /><Meta T={T}>{c.for.includes(' · ') ? '· ' + c.for.split(' · ').slice(1).join(' · ') : ''}</Meta></div></span></span>, `${c.qty} · ${c.recd || '—'} m`, c.qty - c.recd > 0 && c.state === 'Received' ? <span style={{ color: T.warn }}>{+(c.qty - c.recd).toFixed(1)} m loss</span> : `${c.qty - c.recd} m`, c.due.slice(0, 5), <Pill T={T} tone={c.state === 'Received' ? 'ok' : 'blue'} small>{c.state}</Pill>])} />;
const DYE_PANE_TABS = ['Cut order', 'Bulk issue', 'Single issue & order'];
function CutOrderForm({ T, byKarigar }) {
  return <PPane>
    <PaneTabs T={T} tabs={DYE_PANE_TABS} on="Cut order" />
    <div style={{ display: 'flex', gap: 6, marginBottom: 8 }}>{['By material', 'By karigar'].map((t, i) => <T.Chip key={t} on={byKarigar ? i === 1 : i === 0} outline={byKarigar ? i !== 1 : i !== 0} style={{ height: 28 }}>{t}</T.Chip>)}</div>
    {byKarigar ? <>
      <Field T={T} label="Dyer" value="Raja Dyers · 2 materials with him" caret />
      {[['Mono net · Mono', 'net', '2,400 m', 'C07 · Peach', 'Peach', '120 m', '2,280 m'], ['Santoon · Mono', 'satin', '800 m', 'c13 · Peach', 'Peach', '60 m', '740 m']].map(([m, tex, bal, code, sh, q, after]) => <div key={m} style={{ marginTop: 8, padding: 8, borderRadius: 12, background: T.surface2, border: `1px solid ${T.line}` }}><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Swatch m={{ tex, shade: 'Mono' }} w={26} h={26} r={7} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12.5 }}>{m}<Meta T={T}> · {bal} with him</Meta></span></div><div style={{ display: 'flex', gap: 6, marginTop: 6 }}><Field T={T} value={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 5 }}><span style={{ width: 10, height: 10, borderRadius: 3, background: prShade(sh) }} />{code}</span>} caret small /><Field T={T} value={q} small w={70} /><Field T={T} value={'free ' + after} small w={92} /></div></div>)}
      <OutBtn T={T} small icon="plus" style={{ marginTop: 8 }}>Add material</OutBtn>
    </> : <>
      <Field T={T} label="Material with a dyer" value={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Swatch m={{ tex: 'net', shade: 'Mono' }} w={18} h={18} r={5} />Mono net · Mono</span>} caret />
      <Field T={T} label="Dyer" value="Raja Dyers · 2,400 m with him · 2,280 free" caret style={{ marginTop: 8 }} />
      <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Shade code" value={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><span style={{ width: 12, height: 12, borderRadius: 3, background: prShade('Peach') }} />C07 · Peach</span>} caret /><Field T={T} label="Qty" value="120 m" w={90} /></div>
    </>}
    <div style={{ display: 'flex', gap: 8, marginTop: 8 }}><Field T={T} label="Due" value="15/09/26" icon="calendar" /><Field T={T} label={<span>Rate per m<Lock T={T} /></span>} value="₹18" /><Field T={T} label="Cut order no" value="DC-0037 · auto" /></div>
    <Field T={T} label="For (optional)" value={<span style={{ display: 'inline-flex', alignItems: 'center', gap: 5 }}><DesignChip T={T} code="2798" small /> · PO-1187 · Peach</span>} caret style={{ marginTop: 8 }} />
    <Field T={T} label="Narration" ph="e.g. match the Peach santoon swatch" style={{ marginTop: 8 }} />
    <div style={{ marginTop: 10, padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Reserves 120 m of Raja's 2,400 m · free 2,280 m · the balance moves when the dyed lot is received · it returns as a dye WIP material</div>
    <span style={{ flex: 1 }} /><div style={{ display: 'flex', gap: 6 }}><GateToken T={T} n="on issue" /><span style={{ flex: 1 }} /><T.Btn small icon="scissors" style={{ height: 36 }}>Raise cut order</T.Btn></div>
  </PPane>;
}
const DYE_VIEWS = ['Open cut orders', 'Bulk balances', 'Received (dye WIP)', 'History'];
const DyeBar = ({ T, right }) => <PBar T={T} right={right || <div style={{ display: 'flex', gap: 6 }}><OutBtn T={T} small icon="plus">Bulk issue</OutBtn><OutBtn T={T} small icon="arrow-down-left">Receive</OutBtn><OutBtn T={T} small icon="scissors">Cut order</OutBtn></div>}><T.Chip icon="search" outline style={{ width: 124 }}>Cut order, shade</T.Chip><T.Chip on>With dyer</T.Chip><AllFilters T={T} /></PBar>;
function WebPDye({ T }) {
  return <PShell T={T} section="Materials" active="Materials" crumb={['Production', 'Materials', 'Dye ledger']} tab="Production · Dye ledger" paneWidth={308} paneTitle="New cut order" pane={<CutOrderForm T={T} />}>
    <ViewTabs T={T} tabs={MAT_TABS} active="Dye ledger" right={<PTabs T={T} tabs={DYE_VIEWS} on="Open cut orders" />} />
    <div style={{ flex: 1, minHeight: 0, display: 'flex' }}>
      <DyerRail T={T} on={0} />
      <PMain pad="12px 20px 20px">
        <DyeBar T={T} />
        <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><CutRows T={T} on={0} /></PCard>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="info" size={13} color={T.ink3} />A received lot lands in the Materials catalogue as "Mono net · C04" tagged dye WIP, pickable in any recipe and addable to a running order from its lifecycle. Single orders (DS-) are numbered and received the same way.</div>
      </PMain>
    </div>
  </PShell>;
}
const BULK_ROWS = [['k6', 'Mono net · Mono', 'net', 2400, 120, 218, 2, 2400], ['k6', 'Santoon · Mono', 'satin', 800, 0, 0, 0, 800], ['k5', 'Mono net · Mono', 'net', 1150, 210, 196, 4, 1150]];
function WebPDyeBulk({ T }) {
  return <PShell T={T} section="Materials" active="Materials" crumb={['Production', 'Materials', 'Dye ledger', 'Bulk balances']} tab="Production · Dye ledger" paneWidth={308} paneTitle="Bulk issue" pane={<PPane>
    <PaneTabs T={T} tabs={DYE_PANE_TABS} on="Bulk issue" />
    <Meta T={T}>undyed fabric · no colour yet · comes back shade by shade against cut orders</Meta>
    <Field T={T} label="Dyer" value="Raja Dyers · 74" caret style={{ marginTop: 8 }} />
    <PrLab T={T} style={{ marginTop: 10 }}>Materials from the godown</PrLab>
    {[['m6', 1000], ['m3', 0]].map(([id, q]) => { const m = prMat(id); return <div key={id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderTop: `1px solid ${T.line}` }}><Swatch m={m} w={34} h={40} r={8} /><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 12.5 }}>{prMatName(m)}<Meta T={T} style={{ display: 'block' }}>{m.stock} {m.unit} in godown</Meta></span><span style={{ width: 80, height: 32, borderRadius: 9, border: `1px solid ${q ? T.accentLine : T.line2}`, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, color: q ? T.ink : T.ink3 }}>{q ? `${q} ${m.unit}` : `0 ${m.unit}`}</span></div>; })}
    <OutBtn T={T} small icon="plus" style={{ marginTop: 8 }}>Add material</OutBtn>
    <Field T={T} label="Narration" ph="lot and bale numbers" style={{ marginTop: 10 }} />
    <Field T={T} label="Lot photo" value="capture" icon="camera" style={{ marginTop: 8 }} />
    <div style={{ marginTop: 10, padding: '8px 10px', borderRadius: 12, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>Raja's Mono net after: <b style={{ color: T.ink }}>3,400 m</b> · shows as material with him in Karigars</div>
    <span style={{ flex: 1 }} /><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><GateToken T={T} n="GT-260908-027" /><span style={{ flex: 1 }} /><T.Btn small icon="arrow-up-right" style={{ height: 36 }}>Issue 1,000 m</T.Btn></div>
  </PPane>}>
    <ViewTabs T={T} tabs={MAT_TABS} active="Dye ledger" right={<PTabs T={T} tabs={DYE_VIEWS} on="Bulk balances" />} />
    <div style={{ flex: 1, minHeight: 0, display: 'flex' }}>
      <DyerRail T={T} on={0} />
      <PMain pad="12px 20px 20px">
        <DyeBar T={T} right={<Meta T={T}>issued − received − loss = balance · reserved by open cut orders</Meta>} />
        <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} onRow={0} cols={[['Dyer · material'], ['Issued', 66], ['Reserved', 64], ['Returned', 70], ['Loss', 44], ['Balance', 66], ['Free', 56]]} rows={BULK_ROWS.map(r => [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Swatch m={{ tex: r[2], shade: 'Mono' }} w={28} h={28} r={7} /><span>{prK(r[0]).name}<Meta T={T} style={{ display: 'block' }}>{r[1]}</Meta></span></span>, `${(r[3] + r[5] + r[6]).toLocaleString('en-IN')} m`, r[4] ? `${r[4]} m` : '—', r[5] ? `${r[5]} m` : '—', r[6] ? <span style={{ color: T.warn }}>{r[6]} m</span> : '—', <b>{r[7].toLocaleString('en-IN')} m</b>, `${(r[7] - r[4]).toLocaleString('en-IN')} m`])} /></PCard>
        <Sect T={T} right={<Meta T={T}>Raja Dyers · Mono net</Meta>}>Movements</Sect>
        <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><Tbl T={T} head={false} cols={[['Date', 76, 'left'], ['What'], ['Qty', 110], ['Gate token', 130, 'left']]} rows={[['30/08/26', 'Received DC-0029 · C09 Purple', '−218 m · 2 m loss', 'GT-260830-014'], ['20/08/26', 'Cut order DC-0035 · C07 Peach', 'reserved 120 m', '—'], ['12/08/26', 'Bulk issue BI-0021', '+2,620 m', 'GT-260812-003']].map(r => [<Meta T={T}>{r[0]}</Meta>, r[1], <span style={{ fontWeight: 600, color: r[2][0] === '+' ? T.ok : T.ink }}>{r[2]}</span>, r[3] === '—' ? <Meta T={T}>—</Meta> : <GateToken T={T} n={r[3]} done />])} /></PCard>
      </PMain>
    </div>
  </PShell>;
}
function WebPDyeReceived({ T }) {
  const lots = PR_MATS.filter(m => m.dye);
  return <PShell T={T} section="Materials" active="Materials" crumb={['Production', 'Materials', 'Dye ledger', 'Received']} tab="Production · Dye ledger" paneWidth={308} paneTitle="Mono net · Purple" pane={<MatPane T={T} m={prMat('m1')} />}>
    <ViewTabs T={T} tabs={MAT_TABS} active="Dye ledger" right={<PTabs T={T} tabs={DYE_VIEWS} on="Received (dye WIP)" />} />
    <div style={{ flex: 1, minHeight: 0, display: 'flex' }}>
      <DyerRail T={T} on={null} />
      <PMain pad="12px 20px 20px">
        <DyeBar T={T} right={<Meta T={T}>dyed lots · each is a material in the catalogue with its lineage</Meta>} />
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0,1fr))', gap: 12 }}>{[...lots, { id: 'x1', name: 'Mono net', code: 'MN-C22', shade: 'Blush', tex: 'net', group: 'Base fabric', unit: 'm', stock: 0.1, order: 0, lastIn: '24/08/26', sup: 'Raja Dyers', dye: { dyer: 'Raja Dyers', cut: 'DC-0036', code: 'C22', from: 'Mono net · Mono' } }].map((m, i) => <MatCard key={m.id} T={T} m={m} on={i === 0} />)}</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 12, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="info" size={13} color={T.ink3} />Each lot shows in Process setting's Materials pane under "Dye WIP" and can be swapped into a running order from the lifecycle's inputs.</div>
      </PMain>
    </div>
  </PShell>;
}
function WebPDyeReceive({ T }) {
  const c = PR_CUTS[2];
  return <PShell T={T} section="Materials" active="Materials" crumb={['Production', 'Materials', 'Dye ledger', 'Receive DC-0034']} tab="Production · Dye ledger" paneWidth={308} paneTitle="DC-0034 · waiting on it" pane={<PPane>
    <div style={{ padding: 10, borderRadius: 14, background: T.surface2, border: `1px solid ${T.line}` }}><div style={{ display: 'flex', gap: 10 }}><Thumb T={T} d={PR_D('6002')} w={44} h={56} r={10} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}><Num T={T} size={18}>6002</Num><Mono T={T} size={11.5}>PO-1192</Mono></div><Meta T={T} style={{ display: 'block' }}>Lilac 30 · Blush 30 · Materials pending</Meta><div style={{ marginTop: 6 }}><JobChip T={T} s="Waiting previous" small /></div></span></div><Meta T={T} style={{ display: 'block', marginTop: 8 }}>Embroidery needs 0.5 m/pc of net C11 → 15 m for Lilac; this lot covers it and 9 more orders.</Meta></div>
    <Sect T={T}>After this receive</Sect>
    {[['Embroidery · PO-1192 · Lilac', 'Waiting previous → Ready to issue'], ['Rafiq Bhai · Mono net', '1,150 m → 1,000 m'], ['Materials catalogue', '+ Mono net · C11 Lilac · 147 m'], ['Karigars › Rafiq Bhai › Ledger', <span>₹2,646 due · 147 m × ₹18<Lock T={T} /></span>]].map((r, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, height: 38, borderTop: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r[0]}</span><Meta T={T}>{r[1]}</Meta></div>)}
    <span style={{ flex: 1 }} /><OutBtn T={T} small icon="git-branch" style={{ justifyContent: 'center' }}>Use this lot in PO-1192 · Embroidery · Lilac</OutBtn>
  </PPane>}>
    <ViewTabs T={T} tabs={MAT_TABS} active="Dye ledger" right={<PTabs T={T} tabs={DYE_VIEWS} on="Open cut orders" />} />
    <div style={{ flex: 1, minHeight: 0, display: 'flex' }}>
      <DyerRail T={T} on={1} />
      <PMain pad="12px 20px 20px">
        <PCard T={T} style={{ padding: 0, overflow: 'hidden' }}><CutRows T={T} rows={PR_CUTS.slice(0, 3)} on={2} /></PCard>
        <PCard T={T} style={{ marginTop: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>{['Cut order', 'Single order'].map((t, i) => <T.Chip key={t} on={i === 0} outline={i !== 0} style={{ height: 28 }}>{t}</T.Chip>)}<Field T={T} value="DC-0034" caret small w={130} /><span style={{ flex: 1 }} /><Pill T={T} tone="blue" small>With dyer</Pill></div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Swatch m={{ tex: 'net', shade: 'Lilac', dye: true }} w={64} h={72} r={12} /><span style={{ flex: 1 }}><div style={{ fontFamily: T.fontDisplay, fontSize: 20, fontWeight: 600 }}>Receive · {c.no} · Mono net → C11 Lilac</div><div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 3 }}><Meta T={T}>{prK(c.dyer).name} · {c.qty} m ordered on 28/08/26 · due {c.due} · for</Meta><DesignChip T={T} code="6002" small /><Meta T={T}>· PO-1192</Meta></div></span></div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 10, marginTop: 12 }}><Field T={T} label="Received" value="147 m" /><Field T={T} label="Process loss" value="3 m" /><Field T={T} label="Rejected (separate)" value="0 m" /><Field T={T} label="Shade photo" value="capture" icon="camera" /><Field T={T} label="Lands as" value="Mono net · C11 · 147 m" /></div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12 }}><GateToken T={T} n="GT-260908-025" /><Meta T={T}>Rafiq Bhai's Mono net balance after: 1,000 m · print the lot label</Meta><span style={{ flex: 1 }} /><OutBtn T={T}>Cancel</OutBtn><T.Btn small icon="arrow-down-left" style={{ height: 38 }}>Receive 147 m</T.Btn></div>
        </PCard>
      </PMain>
    </div>
  </PShell>;
}

/* ── W8–W11 · Process setting ── */
const StepHead = ({ T, n, title, sub, right, done }) => <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}><span style={{ width: 24, height: 24, borderRadius: 12, background: done ? T.ok : T.ink, color: T.bg, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 12, fontWeight: 600 }}>{done ? <Ic name="check" size={12} sw={3} /> : n}</span><span style={{ fontFamily: T.fontDisplay, fontSize: 18, fontWeight: 600, whiteSpace: 'nowrap' }}>{title}</span>{sub && <Meta T={T} style={{ minWidth: 0 }}>{sub}</Meta>}<span style={{ flex: 1 }} />{right}</div>;
/* header flags: up to three independent pills (chips guideline 3D) */
const RecipeFlagRow = ({ T, incomplete, override, locked, imported }) => <div style={{ display: 'flex', gap: 5, alignItems: 'center', flexWrap: 'wrap' }}>{imported ? <Pill T={T} tone="blue" small>Imported from S-0412 · review</Pill> : null}{incomplete ? <Pill T={T} tone="warn" small>BOM incomplete · {incomplete}</Pill> : null}{override ? <Pill T={T} tone="blue" small>Colour override · {override} rows</Pill> : null}{locked ? <Pill T={T} tone="warn" small>Locked by {locked}</Pill> : null}</div>;
const ProdHeadRow = ({ T, code = '2798', name = 'Plazo set · Lehenga · launched 12/06/26', colours = PR_RECIPE.colours, locked, imported, compact, incomplete = 1, override = 3, tags = 'Surat · net · zari · S M L' }) => <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
  <Thumb T={T} d={PR_D(code)} w={compact ? 40 : 56} h={compact ? 50 : 70} r={12} />
  <span style={{ minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}><Num T={T} size={26}>{code}</Num><Meta T={T}>{name}{tags ? ` · ${tags}` : ''}</Meta></div><div style={{ display: 'flex', gap: 6, marginTop: 6, alignItems: 'center' }}>{colours.map(c => <span key={c} style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 26, padding: '0 9px 0 4px', borderRadius: 999, background: T.chipBg, fontFamily: T.fontUI, fontSize: 11.5 }}><Thumb T={T} d={PR_D(code)} w={18} h={18} r={9} /><Dot n={c} s={7} />{c}</span>)}<span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, height: 26, padding: '0 9px', borderRadius: 999, border: `1px dashed ${T.line2}`, fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}><Ic name="plus" size={12} />colour</span><Caret T={T} style={{ height: 26, fontSize: 11.5 }}>Recipe option 1</Caret></div>{(imported || incomplete || override || locked) ? <div style={{ marginTop: 6 }}><RecipeFlagRow T={T} incomplete={incomplete} override={override} locked={locked} imported={imported} /></div> : null}</span>
  <span style={{ flex: 1 }} />
  <OutBtn T={T} small icon="copy">Copy recipe from…</OutBtn>
</div>;
const SeqChips = ({ T, seq = PR_RECIPE.seq, code = '2798', feeds }) => <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
  {seq.map((p, i) => { const last = i === seq.length - 1; return <React.Fragment key={p}><span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, height: 40, padding: '0 12px 0 6px', borderRadius: 12, background: T.surface, border: `1px solid ${last ? T.accentLine : T.line2}` }}><Ic name="grip-vertical" size={13} color={T.ink3} /><span style={{ width: 22, height: 22, borderRadius: 11, background: T.ink, color: T.bg, display: 'grid', placeItems: 'center', fontFamily: T.fontUI, fontSize: 11, fontWeight: 600 }}>{i + 1}</span><span style={{ fontFamily: T.fontUI, fontSize: 13, fontWeight: 500 }}>{p}</span><Mono T={T} size={10.5} color={T.ink3}>{last ? `${code} · finished good` : prWipName(p, code)}</Mono><span style={{ fontFamily: T.fontUI, fontSize: 10.5, padding: '1px 6px', borderRadius: 999, background: T.chipBg, color: T.ink2 }}>pcs</span>{feeds && feeds[p] && <Meta T={T} style={{ fontSize: 10.5 }}>→ {feeds[p]}</Meta>}{last && <Pill T={T} tone="muted" small>Final</Pill>}<Ic name="x" size={12} color={T.ink3} /></span>{i < seq.length - 1 && <Ic name="arrow-right" size={14} color={T.ink3} />}</React.Fragment>; })}
  <span style={{ width: 1, height: 24, background: T.line2, margin: '0 4px' }} />
  <Meta T={T}>Add:</Meta>{PR_SEQ_PROC.filter(p => !seq.includes(p[0])).map(([p, , ic]) => <span key={p} className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 30, padding: '0 10px', borderRadius: 999, border: `1px dashed ${T.line2}`, fontFamily: T.fontUI, fontSize: 12, color: T.ink2 }}><Ic name={ic} size={12} />{p}</span>)}<span className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 5, height: 30, padding: '0 10px', borderRadius: 999, border: `1px dashed ${T.accentLine}`, fontFamily: T.fontUI, fontSize: 12, color: T.accent }}><Ic name="plus" size={12} />New process</span>
</div>;
/* right pane of process setting: Materials · BOMs · Search */
function MaterialsPaneTab({ T, added = ['m4', 'm2', 'm7', 'm6', 'm5', 'm8', 'm9', 'm10'] }) {
  return <>
    <div style={{ display: 'flex', gap: 6, marginBottom: 6 }}><T.Chip icon="search" outline style={{ height: 28, flex: 1 }}>Material, shade, code</T.Chip><Caret T={T} style={{ height: 28 }}>Newest inward</Caret></div>
    <div style={{ display: 'flex', gap: 5, marginBottom: 4, overflow: 'hidden' }}>{['All', 'Dye WIP', 'Base fabric', 'Accessory', 'In stock'].map((c, i) => <T.Chip key={c} on={i === 0} outline={i !== 0} style={{ height: 24, fontSize: 10.5, padding: '0 8px' }}>{c}</T.Chip>)}</div>
    <div style={{ flex: 1, minHeight: 0, overflow: 'hidden' }}>{PR_MATS.slice(0, 9).map(m => <MatRow key={m.id} T={T} m={m} compact tick added={added.includes(m.id)} right={<span style={{ textAlign: 'right', flex: 'none' }}><div style={{ fontFamily: T.fontUI, fontSize: 12.5, fontWeight: 600, color: m.out ? T.danger : T.ink, fontVariantNumeric: 'tabular-nums' }}>{m.stock} {m.unit}</div></span>} />)}</div>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}><Meta T={T} style={{ flex: 1 }}>sorted by inward date · dye lots appear as they come back</Meta><OutBtn T={T} small icon="plus">New material</OutBtn></div>
  </>;
}
function BomCards({ T, colour = 'Sky', code = '2798' }) {
  return <div style={{ flex: 1, minHeight: 0, overflow: 'hidden' }}>{PR_RECIPE.seq.map((p, i) => { const rows = PR_RECIPE.rows.filter(r => r.to.includes(p) && (r.scope === 'all' || r.scope === colour)); const w = PR_RECIPE.wips.find(x => x[1] === p); const last = p === PR_RECIPE.final; return <div key={p} style={{ marginBottom: 8, borderRadius: 14, background: last ? T.accentSoft : T.surface2, border: `1px solid ${last ? T.accentLine : T.line}`, overflow: 'hidden' }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 10px', borderBottom: `1px solid ${T.line}` }}><span style={{ fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.08em', textTransform: 'uppercase', color: T.ink3 }}>{i + 1} · {p}</span><span style={{ flex: 1 }} /><Mono T={T} size={10.5}>{last ? `${code}_${colour.toLowerCase()} · FG` : prWipName(p, code, colour)}</Mono></div>
    {w && <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '5px 10px', fontFamily: T.fontUI, fontSize: 11.5 }}><span style={{ width: 20, height: 20, borderRadius: 5, background: T.chipBg, display: 'grid', placeItems: 'center' }}><Ic name="layers" size={11} color={T.ink2} /></span><span style={{ flex: 1 }}>{prWipName(w[0], code, colour)}</span><b>1 pc</b></div>}
    {rows.map((r, k) => { const m = prMat(r.m); return <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '4px 10px', fontFamily: T.fontUI, fontSize: 11.5 }}><Swatch m={m} w={20} h={20} r={5} /><span style={{ flex: 1, minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{prMatName(m)} <Meta T={T}>{m.code}</Meta></span><b>{r.avg} {r.unit}</b></div>; })}
    {rows.length === 0 && !w && <Meta T={T} style={{ display: 'block', padding: '6px 10px' }}>nothing ticked yet</Meta>}
  </div>; })}</div>;
}
function SearchRecipesTab({ T }) {
  return <>
    <T.Chip icon="search" outline style={{ height: 28, width: '100%' }}>Design no, material used, process</T.Chip>
    <div style={{ display: 'flex', gap: 5, margin: '6px 0 8px', overflow: 'hidden' }}>{['Lehenga', 'Uses Mono net', 'Complete'].map(c => <T.Chip key={c} outline x style={{ height: 24, fontSize: 10.5, padding: '0 8px' }}>{c}</T.Chip>)}</div>
    {[['6002', '3 processes · Embroidery → Latkan → Stitching · net from dye lot C11', true], ['3661', '2 processes · Pleating → Stitching', true], ['2006', '2 processes · Embroidery → Saree stitching', false], ['4566', 'draft · being created from S-0412', null]].map(([c, s, done], i) => <div key={c} className="press" style={{ display: 'flex', gap: 10, padding: 8, borderRadius: 14, background: i === 0 ? T.accentSoft : 'transparent', borderTop: i ? `1px solid ${T.line}` : 0 }}><Thumb T={T} d={PR_D(c)} w={40} h={50} r={9} /><span style={{ flex: 1, minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}><Num T={T} size={17}>{c}</Num>{done === false && <Pill T={T} tone="warn" small>incomplete</Pill>}{done === null && <Pill T={T} tone="muted" small>draft</Pill>}</div><Meta T={T} style={{ display: 'block', marginTop: 3, whiteSpace: 'normal' }}>{s}</Meta></span></div>)}
    <div style={{ marginTop: 10, padding: 10, borderRadius: 14, background: T.surface2, border: `1px solid ${T.line}` }}><div style={{ fontFamily: T.fontUI, fontSize: 12, fontWeight: 600 }}>6002 · Lilac BOM (preview)</div>{[['Embroidery', 'Mono net C11 0.5 m · Zari 0.05 kg'], ['Latkan', 'wip_emb 1 pc'], ['Stitching', 'wip_lat 1 pc · Santoon 8 m · Cancan 8 m']].map(r => <Meta T={T} key={r[0]} style={{ display: 'block', marginTop: 3 }}>{r[0]} ← {r[1]}</Meta>)}<div style={{ display: 'flex', gap: 6, marginTop: 8 }}><OutBtn T={T} small icon="copy">Copy sequence</OutBtn><OutBtn T={T} small icon="copy">Sequence + BOM</OutBtn></div></div>
  </>;
}
const PSPane = ({ T, tab, colour, code }) => <PPane style={{ padding: '8px 12px 12px' }}><PaneTabs T={T} tabs={['Materials', 'BOMs', 'Search']} on={tab} />{tab === 'Materials' ? <MaterialsPaneTab T={T} /> : tab === 'BOMs' ? <BomCards T={T} colour={colour} code={code} /> : <SearchRecipesTab T={T} />}</PPane>;
const RecipeFoot = ({ T, note = '3 colours × 4 processes = 12 WIP BOMs · saved together', primary = 'Save recipe' }) => <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10 }}><Meta T={T}>{note}</Meta><span style={{ flex: 1 }} /><OutBtn T={T}>Cancel</OutBtn><T.Btn small icon="check" style={{ height: 36 }}>{primary}</T.Btn></div>;
function WebPSetting1({ T }) {
  return <PShell T={T} section="Process setting" active="Process setting" crumb={['Production', 'Process setting', '2798']} tab="Process setting · 2798" paneTitle="Recipe helpers" pane={<PSPane T={T} tab="Materials" />}>
    <PMain>
      <PCard T={T}><StepHead T={T} n={1} title="Product" sub="pick or add a product master · its colours · a photo per colour, one marked primary" done right={<Meta T={T}>one recipe per product · colours may differ · the next step opens when this one is done</Meta>} /><ProdHeadRow T={T} /></PCard>
      <PCard T={T} style={{ marginTop: 10 }}><StepHead T={T} n={2} title="Processes in sequence" sub="drag to order · the number is the step · the last one marked Final makes finished goods · unit per step" /><SeqChips T={T} /><Meta T={T} style={{ display: 'block', marginTop: 8 }}>Each step auto-creates its WIP master per colour (wip_touch_2798_sky …). Dye is not a step: dyed fabric arrives from the Dye ledger as a material. Ready production is the process for designs bought ready-made from a karigar (Direct book).</Meta></PCard>
      <PCard T={T} style={{ marginTop: 10 }} alt><StepHead T={T} n={3} title="Materials & averages" sub="every material once, for all colours · Step 4 ticks the process" right={<OutBtn T={T} small icon="arrow-right">Open · 13 rows</OutBtn>} />
        <div style={{ display: 'flex', gap: 8, overflow: 'hidden' }}>{PR_RECIPE.rows.slice(0, 6).map((r, i) => { const m = prMat(r.m); return <span key={i} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '4px 9px 4px 4px', borderRadius: 999, background: T.surface, border: `1px solid ${T.line}`, fontFamily: T.fontUI, fontSize: 11.5, whiteSpace: 'nowrap' }}><Swatch m={m} w={22} h={22} r={6} />{prMatName(m)} <b>{r.avg} {r.unit}</b>{r.scope !== 'all' && <Dot n={r.scope} s={7} />}</span>; })}<Meta T={T} style={{ alignSelf: 'center' }}>+7 more · 8 materials · 3 dye lots</Meta></div></PCard>
      <PCard T={T} style={{ marginTop: 10 }} alt><StepHead T={T} n={4} title="BOM per process, per colour" sub="one tab per colour · Sky · Purple · Peach · copy from the first" right={<OutBtn T={T} small icon="arrow-right">Open grid</OutBtn>} />
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>{[['Sky', 4], ['Purple', 4], ['Peach', 3]].map(([c, n]) => <span key={c} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '5px 10px', borderRadius: 999, background: T.surface, border: `1px solid ${n < 4 ? T.warn + '88' : T.line}`, fontFamily: T.fontUI, fontSize: 12 }}><Dot n={c} s={8} />{c}<span style={{ display: 'inline-flex', gap: 3 }}>{PR_RECIPE.seq.map((p, k) => <span key={p} style={{ width: 8, height: 8, borderRadius: 4, background: k < n ? T.ok : 'transparent', border: `1.5px solid ${k < n ? T.ok : T.warn}`, boxSizing: 'border-box' }} />)}</span><Meta T={T}>{n} of 4{n < 4 ? ' · Stitching missing' : ''}</Meta></span>)}<Meta T={T}>the recipe is complete when every process of every colour has a BOM</Meta></div></PCard>
      <RecipeFoot T={T} />
    </PMain>
  </PShell>;
}
function WebPSetting2({ T }) {
  const rows = PR_RECIPE.rows;
  return <PShell T={T} section="Process setting" active="Process setting" crumb={['Production', 'Process setting', '2798', 'Materials & averages']} tab="Process setting · 2798" paneTitle="Recipe helpers" pane={<PSPane T={T} tab="Materials" />}>
    <PMain>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><ProdHeadRow T={T} compact /></div>
      <PCard T={T} style={{ marginTop: 10, padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '12px 14px 0' }}><StepHead T={T} n={3} title="Materials & averages" sub="per pc · same material twice when two processes consume it · scope a row to one or more colours" right={<div style={{ display: 'flex', gap: 6 }}><T.Chip outline icon="search" style={{ height: 28 }}>Filter rows</T.Chip><OutBtn T={T} small icon="plus">Add materials</OutBtn></div>} /></div>
        <Tbl T={T} cols={[['Material · shade · code'], ['Stock now', 84], ['Avg / pc', 76], ['Unit', 36, 'left'], ['Colour scope · pick any', 206, 'left'], ['Feeds', 128, 'left'], ['', 60]]} rows={rows.slice(0, 9).map((r, i) => { const m = prMat(r.m); return [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, minWidth: 0 }}><Swatch m={m} w={30} h={36} r={7} /><span style={{ minWidth: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{prMatName(m)}<Meta T={T}> · {m.code}{m.dye ? ' · dye wip' : ''}</Meta></span></span>, <span style={{ color: m.out ? T.danger : m.low ? T.warn : T.ink }}>{m.stock} {m.unit}</span>, <span style={{ display: 'inline-block', width: 62, height: 28, lineHeight: '26px', borderRadius: 8, border: `1px solid ${T.line2}`, textAlign: 'center', fontWeight: 600 }}>{r.avg}</span>, r.unit, <span style={{ display: 'inline-flex', gap: 4 }}>{['all', ...PR_RECIPE.colours].map(c => { const on = r.scope === c || (r.scope === 'all' && c === 'all'); return <span key={c} className="press" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, height: 22, padding: '0 7px', borderRadius: 999, background: on ? T.ink : 'transparent', border: `1px solid ${on ? T.ink : T.line2}`, color: on ? T.bg : T.ink2, fontSize: 10.5 }}>{c !== 'all' && <Dot n={c} s={6} />}{c === 'all' ? 'All' : c}</span>; })}</span>, <span style={{ display: 'inline-flex', gap: 4 }}>{r.to.map(p => <Pill key={p} T={T} tone="muted" small>{p}</Pill>)}{r.dual && <Meta T={T}>2nd use</Meta>}</span>, <span style={{ display: 'inline-flex', gap: 4 }}><Hit T={T} icon="copy" size={26} iconSize={13} style={{ background: T.chipBg }} /><Hit T={T} icon="trash-2" size={26} iconSize={13} style={{ background: T.chipBg }} /></span>]; })} />
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 14px', borderTop: `1px solid ${T.line}` }}><Meta T={T}>averages here are the starting values · the BOM grid may set a different average per process · 13 rows</Meta><span style={{ flex: 1 }} /><OutBtn T={T} small icon="arrow-right">Set BOMs</OutBtn></div>
      </PCard>
      <RecipeFoot T={T} />
    </PMain>
  </PShell>;
}
/* the BOM grid for one colour */
function BomGrid({ T, colour = 'Sky', code = '2798', missingOnly }) {
  const seq = PR_RECIPE.seq; const rows = PR_RECIPE.rows.filter(r => r.scope === 'all' || r.scope === colour);
  const Cell = ({ on, dis, dim }) => <span style={{ width: 96, flex: 'none', display: 'grid', placeItems: 'center', opacity: dim ? .35 : 1 }}><span className={dis ? undefined : 'press'} style={{ width: 18, height: 18, borderRadius: 5, background: on ? T.ink : dis ? T.chipBg : 'transparent', border: `1.5px solid ${on ? T.ink : dis ? 'transparent' : T.line2}`, color: T.bg, display: 'grid', placeItems: 'center', opacity: dis ? .5 : 1 }}>{on && <Ic name="check" size={12} sw={3} />}</span></span>;
  const head = <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 12px', borderBottom: `1px solid ${T.line}` }}><span style={{ width: 24, flex: 'none' }}><span style={{ width: 16, height: 16, borderRadius: 5, background: T.ink, color: T.bg, display: 'grid', placeItems: 'center' }}><Ic name="check" size={10} sw={3} /></span></span><span style={{ flex: 1, fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>Materials list · tick = in this colour</span><span style={{ width: 90, flex: 'none', textAlign: 'right', fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>Avg / pc</span><span style={{ width: 40, flex: 'none', fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>Unit</span>{seq.map((p, i) => <span key={p} style={{ width: 96, flex: 'none', textAlign: 'center', fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: p === PR_RECIPE.final ? T.ink : T.ink3, fontWeight: p === PR_RECIPE.final ? 600 : 400, opacity: missingOnly && p !== 'Stitching' ? .35 : 1 }}>{i + 1} · {p}</span>)}</div>;
  const row = (left, avg, unit, cells, k, tint, inCol = true) => <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '2px 12px', borderTop: `1px solid ${T.line}`, background: tint || 'transparent' }}><span style={{ width: 24, flex: 'none' }}><span style={{ width: 16, height: 16, borderRadius: 5, background: inCol ? T.ink : 'transparent', border: `1.5px solid ${inCol ? T.ink : T.line2}`, color: T.bg, display: 'grid', placeItems: 'center' }}>{inCol && <Ic name="check" size={10} sw={3} />}</span></span><span style={{ flex: 1, minWidth: 0, overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' }}>{left}</span><span style={{ width: 90, flex: 'none', textAlign: 'right' }}><span style={{ display: 'inline-block', width: 58, height: 22, lineHeight: '20px', borderRadius: 7, border: `1px solid ${T.line2}`, textAlign: 'center', fontFamily: T.fontUI, fontSize: 12, fontWeight: 600 }}>{avg}</span></span><span style={{ width: 40, flex: 'none', fontFamily: T.fontUI, fontSize: 11.5, color: T.ink2 }}>{unit}</span>{cells}</div>;
  const count = p => rows.filter(r => r.to.includes(p)).length + (PR_RECIPE.wips.find(x => x[1] === p) ? 1 : 0);
  return <div style={{ borderRadius: 16, border: `1px solid ${T.line}`, background: T.surface, overflow: 'hidden' }}>
    {head}
    {rows.map((r, i) => { const m = prMat(r.m); return row(<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Swatch m={m} w={22} h={24} r={6} /><span style={{ fontFamily: T.fontUI, fontSize: 12.5 }}>{prMatName(m)} <Meta T={T}>{m.code}{m.dye ? ' · dye wip' : ''}{r.dual ? ' · 2nd use' : ''}{!m.dye && m.name === 'Mono net' && colour === 'Peach' ? ' · undyed · dye lot DC-0035 due 15/09' : ''}</Meta></span></span>, r.avg, r.unit, seq.map(p => <Cell key={p} on={r.to.includes(p)} dim={missingOnly && p !== 'Stitching'} />), i); })}
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 12px', borderTop: `1px solid ${T.line}`, background: T.bg2 }}><span style={{ fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>WIPs list · auto per process · each feeds one later process</span><span style={{ flex: 1 }} /><span style={{ width: 96, flex: 'none', textAlign: 'center', fontFamily: T.fontUI, fontSize: 10, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>finished good</span></div>
    {seq.map((p, i) => { const w = PR_RECIPE.wips.find(x => x[0] === p); const last = p === PR_RECIPE.final; return row(<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><span style={{ width: 22, height: 24, borderRadius: 6, background: T.chipBg, display: 'grid', placeItems: 'center' }}><Ic name="layers" size={12} color={T.ink2} /></span><Mono T={T} size={12} weight={500}>{last ? `${code}_${colour.toLowerCase()}` : prWipName(p, code, colour)}</Mono>{last && <Pill T={T} tone="muted" small>finished good</Pill>}</span>, 1, 'pc', seq.map((q, k) => <Cell key={q} on={w && w[1] === q} dis={k <= i} dim={missingOnly && q !== 'Stitching'} />), 'w' + i, last ? T.accentSoft : undefined); })}
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 12px', borderTop: `1px solid ${T.line}` }}><span style={{ width: 24 }} /><Meta T={T} style={{ flex: 1 }}>a tick is the setting · the BOMs pane shows the result live</Meta><span style={{ width: 130 }} />{seq.map(p => { const n = count(p); const set = n > 0 && !(colour === 'Peach' && p === 'Stitching'); return <span key={p} style={{ width: 96, flex: 'none', display: 'grid', placeItems: 'center' }}>{set ? <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontFamily: T.fontUI, fontSize: 11, color: T.ok }}><Ic name="check" size={12} sw={2.5} />BOM set · {n}</span> : <OutBtn T={T} small style={{ height: 26, padding: '0 9px', fontSize: 11 }}>Set BOM</OutBtn>}</span>; })}</div>
  </div>;
}
const ColourTabsRow = ({ T, on, copyFrom, right }) => <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>{PR_RECIPE.colours.map(c => <T.Chip key={c} on={c === on} outline={c !== on} style={{ height: 32 }}><Dot n={c} s={8} />{c}{c === 'Peach' && <Pill T={T} tone="warn" small>1 missing</Pill>}</T.Chip>)}<OutBtn T={T} small icon="copy">Copy {copyFrom || 'Sky'} to the other colours</OutBtn><span style={{ flex: 1 }} />{right}</div>;
const BomChips = ({ T, colour, missing }) => <div style={{ display: 'flex', gap: 6 }}><Caret T={T} on>{colour}</Caret><T.Chip on={missing} outline={!missing} style={{ height: 28 }}>Missing assignments</T.Chip><T.Chip outline style={{ height: 28 }}>Selected only</T.Chip><T.Chip outline style={{ height: 28 }}>Materials | WIPs</T.Chip></div>;
function WebPSetting3({ T }) {
  return <PShell T={T} section="Process setting" active="Process setting" crumb={['Production', 'Process setting', '2798', 'BOM · Sky']} tab="Process setting · 2798" paneTitle="BOMs · Sky" pane={<PSPane T={T} tab="BOMs" colour="Sky" />}>
    <PMain>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><ProdHeadRow T={T} compact /></div>
      <div style={{ marginTop: 10 }}><StepHead T={T} n={4} title="BOM per process · Sky" sub="tick each process that consumes a row · WIP rows feed one later process" right={<div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><Meta T={T}>Sky · 4 of 4 processes have a BOM · 12 BOMs saved together</Meta><T.Btn small icon="check" style={{ height: 32 }}>Save recipe</T.Btn></div>} /></div>
      <ColourTabsRow T={T} on="Sky" right={<BomChips T={T} colour="Sky" />} />
      <BomGrid T={T} colour="Sky" />
    </PMain>
  </PShell>;
}
function WebPSetting4({ T }) {
  return <PShell T={T} section="Process setting" active="Process setting" crumb={['Production', 'Process setting', '2798', 'BOM · Peach']} tab="Process setting · 2798" paneTitle="Recipe helpers" pane={<PSPane T={T} tab="Search" />}>
    <PMain>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><ProdHeadRow T={T} locked="PO-1187" compact /></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8, padding: '6px 12px', borderRadius: 12, background: T.warn + '1F', border: `1px solid ${T.warn}55`, fontFamily: T.fontUI, fontSize: 12, color: T.ink }}><Ic name="lock" size={14} color={T.warn} />Locked by PO-1187 · that order keeps the recipe it started with · edits apply to new orders · add a dye lot to a running order from its lifecycle.</div>
      <div style={{ marginTop: 8 }}><StepHead T={T} n={4} title="BOM per process · Peach" sub="copied from Sky · colour rows swapped (Santoon Peach; Mono net undyed until its dye lot lands)" right={<div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><Meta T={T}>Peach · 3 of 4 · Stitching not set · saves as incomplete</Meta><T.Btn small icon="check" style={{ height: 32 }}>Save recipe</T.Btn></div>} /></div>
      <ColourTabsRow T={T} on="Peach" right={<BomChips T={T} colour="Peach" missing />} />
      <BomGrid T={T} colour="Peach" missingOnly />
    </PMain>
  </PShell>;
}
/* W8b · a product imported from a sample lands here pre-filled for review */
function WebPSetting5({ T }) {
  const seq = ['Embroidery', 'Stitching'];
  return <PShell T={T} section="Process setting" active="Process setting" crumb={['Production', 'Process setting', '4566', 'Imported from S-0412']} tab="Process setting · 4566" paneTitle="Recipe helpers" pane={<PPane style={{ padding: '8px 12px 12px' }}><PaneTabs T={T} tabs={['Materials', 'BOMs', 'Search', 'S-0412 moves']} on="S-0412 moves" /><Meta T={T}>the sample's moves, for reference while you review</Meta><div style={{ marginTop: 8, display: 'grid', gap: 8 }}>{PR_MOVES.map(mv => <MoveCard key={mv.n} T={T} mv={mv} phone money />)}</div></PPane>}>
    <PMain>
      <PCard T={T}><StepHead T={T} n={1} title="Product" sub="new master · created from the sample · photo from the first piece, mark it primary in Studio" done /><ProdHeadRow T={T} code="4566" name="Blush cape · Lehenga · from S-0412" colours={['Blush']} imported incomplete={0} override={0} tags="Surat · net · sequin · S M L" /></PCard>
      <PCard T={T} style={{ marginTop: 10 }}><StepHead T={T} n={2} title="Processes in sequence · derived from 3 moves" sub="dye became the cut order DC-0036 · reorder or add before saving" done /><SeqChips T={T} seq={seq} code="4566" /></PCard>
      <PCard T={T} style={{ marginTop: 10, padding: 0, overflow: 'hidden' }} alt>
        <div style={{ padding: '12px 14px 0' }}><StepHead T={T} n={3} title="Materials & averages · issued ÷ 1 pc" sub="edit any average · the sample's issued quantity sits beside it" /></div>
        <Tbl T={T} cols={[['Material · shade · code'], ['In the sample', 110, 'left'], ['Avg / pc', 76], ['Unit', 36, 'left'], ['Feeds', 120, 'left'], ['From', 130, 'left']]} rows={[['x', 'Mono net · C22 Blush · dye lot', '2.9 m', 2.9, 'm', 'Embroidery'], ['m7', null, '0.05 kg', 0.05, 'kg', 'Embroidery'], ['m3', null, '8 m', 8, 'm', 'Stitching'], ['m5', null, '8 m', 8, 'm', 'Stitching']].map(([id, nm, s, avg, u, p]) => { const m = id === 'x' ? { tex: 'net', shade: 'Blush', dye: true, code: 'MN-C22' } : prMat(id); return [<span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}><Swatch m={m} w={30} h={36} r={7} /><span>{nm || prMatName(m)} <Meta T={T}>{m.code}</Meta></span></span>, <Meta T={T}>{s} for 1 pc</Meta>, <span style={{ display: 'inline-block', width: 62, height: 28, lineHeight: '26px', borderRadius: 8, border: `1px solid ${T.accentLine}`, textAlign: 'center', fontWeight: 600 }}>{avg}</span>, u, <Pill T={T} tone="muted" small>{p}</Pill>, <Meta T={T}>move {p === 'Embroidery' ? 2 : 3} · S-0412</Meta>]; })} />
      </PCard>
      <PCard T={T} style={{ marginTop: 10 }} alt><StepHead T={T} n={4} title="BOM · Blush · pre-ticked from the moves" sub="review the ticks · Stitching is Final" right={<Pill T={T} tone="blue" small>review</Pill>} />
        <div style={{ display: 'flex', gap: 10 }}>{[['1 · Embroidery', 'wip_emb_4566_blush', ['Mono net · C22 · 2.9 m', 'Zari thread · 0.05 kg']], ['2 · Stitching · finished good', '4566_blush', ['wip_emb_4566_blush · 1 pc', 'Santoon · Peach · 8 m', 'Cancan · 8 m']]].map(([t, w, ls]) => <div key={t} style={{ flex: 1, padding: 10, borderRadius: 14, background: T.surface, border: `1px solid ${T.line}` }}><div style={{ display: 'flex', alignItems: 'baseline' }}><span style={{ fontFamily: T.fontUI, fontSize: 10.5, letterSpacing: '.06em', textTransform: 'uppercase', color: T.ink3 }}>{t}</span><span style={{ flex: 1 }} /><Mono T={T} size={10.5}>{w}</Mono></div>{ls.map(l => <Meta T={T} key={l} style={{ display: 'block', marginTop: 4, color: T.ink }}>{l}</Meta>)}</div>)}</div></PCard>
      <RecipeFoot T={T} note="1 colour × 2 processes = 2 WIP BOMs + 1 dye cut order · S-0412 keeps its number as the reference" primary="Save recipe · 4566" />
    </PMain>
  </PShell>;
}

Object.assign(window, { PROD_SEG, PR_TABS, PANE_W, PShell, PMain, PPane, PBar, PCard, PTabs, PaneTabs, Caret, AllFilters, Lock, WebPOverview, PO_ROWS, POCalendar, POPane, POBar, PO_TABS, WebPPurchaseOrders, POList, WebPPOList, NewPOPane, WebPPONew, SupplierPane, WebPInward, GRN_ROWS, WebPInwardPast, WebPReturn, MatPane, MAT_TABS, MatBar, WebPMaterials, NewMaterialPane, WebPMaterialNew, DyerRail, CutRows, CutOrderForm, DYE_VIEWS, DyeBar, WebPDye, WebPDyeBulk, WebPDyeReceived, WebPDyeReceive, StepHead, RecipeFlagRow, ProdHeadRow, SeqChips, MaterialsPaneTab, BomCards, SearchRecipesTab, PSPane, RecipeFoot, WebPSetting1, WebPSetting2, BomGrid, ColourTabsRow, BomChips, WebPSetting3, WebPSetting4, WebPSetting5 });
