/* Two aesthetic directions. Each theme = tokens + its own chrome (top bar, category nav, chips, grid card, cart tray, bottom bar, controls). */
const base = { ok: '#3F8A5E', warn: '#C0862B', danger: '#C24545', blue: '#4C7FB5' };

/* ───────────── A · GALLERY — ivory editorial, hairlines, Marcellus ───────────── */
const GALLERY = { ...base, name: 'Gallery', dark: false,
  bg: '#F7F2EB', bg2: '#EFE8DF', surface: '#FCF9F4', line: 'rgba(31,22,19,.10)', line2: 'rgba(31,22,19,.22)',
  ink: '#1F1613', ink2: '#5E4F47', ink3: '#9A8A80', accent: '#5A1F27', accentSoft: 'rgba(90,31,39,.08)', gold: '#B98E4A', onAccent: '#F7F2EB',
  fontDisplay: '"Marcellus", "Cormorant Garamond", serif', fontSerif: '"Cormorant Garamond", serif', fontUI: '"Jost", sans-serif', fontMono: '"IBM Plex Mono", monospace',
  rPhoto: 8, rCard: 14, rPill: 999, glass: 'rgba(247,242,235,.78)', shadow: '0 10px 30px -14px rgba(31,22,19,.35)', photoBg: 'linear-gradient(180deg,#EAE1D6,#DDD1C3)', barH: 66,
};
GALLERY.Btn = ({ kind = 'primary', children, icon, small, style, onClick }) => { const P = kind === 'primary', G = kind === 'ghost'; return <button onClick={onClick} style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8, height: small ? 34 : 48, padding: small ? '0 14px' : '0 22px', borderRadius: 999, border: P || G ? '1px solid transparent' : `1px solid ${GALLERY.line2}`, background: P ? GALLERY.accent : 'transparent', color: P ? GALLERY.onAccent : G ? GALLERY.ink2 : GALLERY.ink, fontFamily: GALLERY.fontUI, fontSize: small ? 12.5 : 14, fontWeight: 500, letterSpacing: '.02em', cursor: 'pointer', whiteSpace: 'nowrap', ...style }}>{icon && <Ic name={icon} size={small ? 14 : 16} />}{children}</button>; };
GALLERY.Chip = ({ children, on, x, icon, style }) => <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, height: 28, padding: '0 11px', borderRadius: 999, border: `1px solid ${on ? GALLERY.accent : GALLERY.line2}`, background: on ? GALLERY.accent : 'transparent', color: on ? GALLERY.onAccent : GALLERY.ink2, fontFamily: GALLERY.fontUI, fontSize: 12, whiteSpace: 'nowrap', flex: 'none', ...style }}>{icon && <Ic name={icon} size={12} />}{children}{x && <Ic name="x" size={11} style={{ opacity: .6 }} />}</span>;
GALLERY.Tag = ({ tone = 'accent', children }) => { const c = tone === 'danger' ? GALLERY.danger : tone === 'ok' ? GALLERY.ok : tone === 'gold' ? GALLERY.gold : tone === 'muted' ? GALLERY.ink3 : GALLERY.accent; return <span style={{ fontFamily: GALLERY.fontUI, fontSize: 10.5, letterSpacing: '.12em', textTransform: 'uppercase', color: c, whiteSpace: 'nowrap' }}>{children}</span>; };
GALLERY.Step = ({ v, big }) => { const s = big ? 40 : 28; const b = { width: s, height: s, borderRadius: '50%', border: `1px solid ${GALLERY.line2}`, display: 'grid', placeItems: 'center', color: GALLERY.ink }; return <span style={{ display: 'inline-flex', alignItems: 'center', gap: big ? 14 : 10 }}><span style={b}><Ic name="minus" size={big ? 16 : 12} /></span><span style={{ fontFamily: GALLERY.fontUI, fontSize: big ? 20 : 14, fontWeight: 500, minWidth: 16, textAlign: 'center' }}>{v}</span><span style={{ ...b, background: GALLERY.ink, color: GALLERY.bg, border: 0 }}><Ic name="plus" size={big ? 16 : 12} /></span></span>; };
GALLERY.Bars = ({ names, active, size = 'sm', light }) => <span style={{ display: 'inline-flex', gap: 3, alignItems: 'flex-end' }}>{names.map(n => <span key={n} title={n} style={{ width: size === 'sm' ? 5 : 8, height: n === active ? (size === 'sm' ? 16 : 26) : (size === 'sm' ? 12 : 20), borderRadius: 2, background: XD.cols[n], boxShadow: n === active ? `0 0 0 1.5px ${light ? '#fff' : GALLERY.ink}` : 'inset 0 0 0 1px rgba(0,0,0,.12)' }} />)}</span>;
GALLERY.TopBar = ({ scanOn, role }) => <div style={{ display: 'flex', alignItems: 'center', padding: '0 18px', height: 44 }}>
  <img src={XD.A + 'logo/sutra-mark-gold.png'} style={{ height: 26 }} />
  <span style={{ width: 1, height: 18, background: GALLERY.line2, margin: '0 12px' }} /><img src={XD.A + 'clients/srs-logo.png'} style={{ height: 22 }} />
  <span style={{ flex: 1 }} />
  <span style={{ fontFamily: GALLERY.fontUI, fontSize: 10.5, letterSpacing: '.14em', textTransform: 'uppercase', color: GALLERY.ink3, marginRight: 14 }}>{role}</span>
  <span style={{ width: 36, height: 36, borderRadius: '50%', display: 'grid', placeItems: 'center', color: GALLERY.ink }}><Ic name="search" size={19} /></span>
  <span style={{ width: 36, height: 36, borderRadius: '50%', display: 'grid', placeItems: 'center', color: GALLERY.ink, border: scanOn ? `1.5px solid ${GALLERY.ok}` : '1px solid transparent', marginLeft: 2 }}><Ic name="scan-line" size={19} /></span>
  <span style={{ width: 36, height: 36, borderRadius: '50%', display: 'grid', placeItems: 'center', color: GALLERY.ink, marginLeft: 2 }}><Ic name="ellipsis-vertical" size={19} /></span>
</div>;
GALLERY.Cats = ({ items, active }) => <div style={{ display: 'flex', gap: 22, padding: '6px 20px 0', borderBottom: `1px solid ${GALLERY.line}` }}>{items.map(c => <span key={c} style={{ position: 'relative', padding: '8px 0 12px', fontFamily: GALLERY.fontDisplay, fontSize: 15, letterSpacing: '.02em', color: c === active ? GALLERY.ink : GALLERY.ink3, whiteSpace: 'nowrap' }}>{c}{c === active && <span style={{ position: 'absolute', left: 0, right: 0, bottom: -1, height: 1.5, background: GALLERY.accent }} />}</span>)}</div>;
GALLERY.GridCard = ({ d, inCart }) => <div>
  <div style={{ position: 'relative', aspectRatio: '4/5', borderRadius: GALLERY.rPhoto, overflow: 'hidden', background: GALLERY.photoBg }}>
    {d.src ? <img src={d.src} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} /> : <div style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', fontFamily: GALLERY.fontDisplay, fontSize: 30, color: GALLERY.ink3 }}>{d.code}</div>}
    {d.tag && <span style={{ position: 'absolute', top: 0, left: 0, padding: '6px 10px', background: GALLERY.glass, backdropFilter: 'blur(10px)', borderRadius: `0 0 ${GALLERY.rPhoto}px 0` }}><GALLERY.Tag tone={d.tagTone === 'gold' ? 'gold' : 'accent'}>{d.tag}</GALLERY.Tag></span>}
    <span style={{ position: 'absolute', left: 10, bottom: 10, padding: '6px 8px', borderRadius: 6, background: 'rgba(31,22,19,.55)', backdropFilter: 'blur(8px)', display: 'flex' }}><GALLERY.Bars names={d.colours} light /></span>
    <span style={{ position: 'absolute', right: 10, bottom: 10, width: 34, height: 34, borderRadius: '50%', background: inCart ? GALLERY.accent : GALLERY.glass, backdropFilter: 'blur(10px)', color: inCart ? GALLERY.onAccent : GALLERY.ink, display: 'grid', placeItems: 'center', fontFamily: GALLERY.fontUI, fontSize: 13, fontWeight: 500 }}>{inCart ? inCart : <Ic name="plus" size={16} />}</span>
  </div>
  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginTop: 10 }}>
    <span style={{ fontFamily: GALLERY.fontMono, fontSize: 11.5, color: GALLERY.ink3 }}>{d.code}</span>
    <span style={{ fontFamily: GALLERY.fontDisplay, fontSize: 15.5, color: GALLERY.ink, flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{d.name}</span>
    <Price v={d.price} size={16} font={GALLERY.fontSerif} color={GALLERY.ink} dim={GALLERY.ink3} />
  </div>
  {d.note && <div style={{ marginTop: 4 }}><GALLERY.Tag tone="danger">{d.note}</GALLERY.Tag></div>}
</div>;
GALLERY.CartTray = ({ active }) => <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '0 16px', overflow: 'hidden' }}>
  {CARTS.map(c => { const on = c.k === active; return <span key={c.k} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, height: 40, padding: on ? '0 14px 0 4px' : '0 4px', borderRadius: 999, background: 'rgba(252,249,244,.92)', border: `1px solid ${on ? GALLERY.accent : 'rgba(255,255,255,.6)'}`, boxShadow: GALLERY.shadow, flex: 'none' }}>
    <span style={{ width: 32, height: 32, borderRadius: '50%', background: on ? GALLERY.accent : GALLERY.bg2, color: on ? GALLERY.onAccent : GALLERY.ink, display: 'grid', placeItems: 'center', fontFamily: GALLERY.fontDisplay, fontSize: 15 }}>{c.k}</span>
    {on && <span style={{ fontFamily: GALLERY.fontUI, fontSize: 12.5, color: GALLERY.ink, whiteSpace: 'nowrap' }}>{c.name} <b style={{ fontWeight: 500, color: GALLERY.ink3 }}>· {c.n}</b></span>}
    {!on && c.n > 0 && <span style={{ position: 'relative', marginLeft: -10, top: -12, width: 16, height: 16, borderRadius: 8, background: GALLERY.gold, color: '#fff', fontFamily: GALLERY.fontUI, fontSize: 9.5, display: 'grid', placeItems: 'center' }}>{c.n}</span>}
  </span>; })}
  <span style={{ width: 40, height: 40, borderRadius: '50%', border: `1px dashed ${GALLERY.line2}`, display: 'grid', placeItems: 'center', color: GALLERY.ink2, flex: 'none' }}><Ic name="plus" size={16} /></span>
</div>;
GALLERY.BottomBar = ({ active }) => <div style={{ margin: '0 14px', height: 62, borderRadius: 999, background: 'rgba(252,249,244,.94)', border: '1px solid rgba(255,255,255,.6)', boxShadow: GALLERY.shadow, display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 10px' }}>
  {NAV.map(([i, l]) => { const on = l === active; return <span key={l} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, height: 44, padding: on ? '0 16px 0 12px' : '0 10px', borderRadius: 999, background: on ? GALLERY.accent : 'transparent', color: on ? GALLERY.onAccent : GALLERY.ink2 }}><Ic name={i} size={20} sw={on ? 1.8 : 1.5} />{on && <span style={{ fontFamily: GALLERY.fontUI, fontSize: 12.5, letterSpacing: '.04em' }}>{l}</span>}</span>; })}
</div>;

/* ───────────── B · ATELIER — espresso dark, tactile pills, Bodoni Moda ───────────── */
const ATELIER = { ...base, name: 'Atelier', dark: true, ok: '#5FB57F', warn: '#D9A33B', danger: '#E06060', blue: '#6FA3DC',
  bg: '#17110E', bg2: '#211915', surface: '#2A2019', surface2: '#342922', line: 'rgba(241,232,220,.09)', line2: 'rgba(241,232,220,.2)',
  ink: '#F3EADF', ink2: '#B9A898', ink3: '#7E6D62', accent: '#A8404F', accentSoft: 'rgba(168,64,79,.22)', gold: '#D8B36A', onAccent: '#FBF4EC',
  fontDisplay: '"Bodoni Moda", "Cormorant Garamond", serif', fontSerif: '"Bodoni Moda", serif', fontUI: '"Outfit", sans-serif', fontMono: '"DM Mono", monospace',
  rPhoto: 22, rCard: 24, rPill: 999, glass: 'rgba(23,17,14,.62)', shadow: '0 24px 50px -20px rgba(0,0,0,.7)', photoBg: 'linear-gradient(180deg,#3A2D26,#261D18)', barH: 74,
};
ATELIER.Btn = ({ kind = 'primary', children, icon, small, style, onClick }) => { const P = kind === 'primary', G = kind === 'ghost'; return <button onClick={onClick} style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8, height: small ? 36 : 52, padding: small ? '0 16px' : '0 24px', borderRadius: 999, border: 0, background: P ? ATELIER.ink : G ? 'transparent' : ATELIER.surface2, color: P ? ATELIER.bg : G ? ATELIER.ink2 : ATELIER.ink, fontFamily: ATELIER.fontUI, fontSize: small ? 13 : 15, fontWeight: 500, cursor: 'pointer', whiteSpace: 'nowrap', boxShadow: P ? '0 10px 24px -10px rgba(243,234,223,.35)' : 'none', ...style }}>{icon && <Ic name={icon} size={small ? 14 : 17} />}{children}</button>; };
ATELIER.Chip = ({ children, on, x, icon, style }) => <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, height: 34, padding: '0 14px', borderRadius: 999, background: on ? ATELIER.ink : ATELIER.surface, color: on ? ATELIER.bg : ATELIER.ink2, fontFamily: ATELIER.fontUI, fontSize: 13, fontWeight: 500, whiteSpace: 'nowrap', flex: 'none', ...style }}>{icon && <Ic name={icon} size={13} />}{children}{x && <Ic name="x" size={12} style={{ opacity: .6 }} />}</span>;
ATELIER.Tag = ({ tone = 'accent', children }) => { const bg = tone === 'danger' ? ATELIER.danger : tone === 'ok' ? ATELIER.ok : tone === 'gold' ? ATELIER.gold : tone === 'muted' ? ATELIER.surface2 : ATELIER.ink; const fg = tone === 'muted' ? ATELIER.ink2 : ATELIER.bg; return <span style={{ display: 'inline-flex', alignItems: 'center', height: 24, padding: '0 10px', borderRadius: 999, background: bg, color: fg, fontFamily: ATELIER.fontUI, fontSize: 11, fontWeight: 600, letterSpacing: '.04em', whiteSpace: 'nowrap' }}>{children}</span>; };
ATELIER.Step = ({ v, big }) => { const s = big ? 44 : 30; const b = { width: s, height: s, borderRadius: big ? 14 : 10, background: ATELIER.surface2, display: 'grid', placeItems: 'center', color: ATELIER.ink }; return <span style={{ display: 'inline-flex', alignItems: 'center', gap: big ? 14 : 10 }}><span style={b}><Ic name="minus" size={big ? 18 : 13} /></span><span style={{ fontFamily: ATELIER.fontUI, fontSize: big ? 22 : 15, fontWeight: 500, minWidth: 18, textAlign: 'center' }}>{v}</span><span style={{ ...b, background: ATELIER.ink, color: ATELIER.bg }}><Ic name="plus" size={big ? 18 : 13} /></span></span>; };
ATELIER.Bars = ({ names, active, size = 'sm' }) => <span style={{ display: 'inline-flex', gap: size === 'sm' ? 5 : 8 }}>{names.map(n => <span key={n} style={{ width: size === 'sm' ? 12 : 22, height: size === 'sm' ? 12 : 22, borderRadius: '50%', background: XD.cols[n], boxShadow: n === active ? `0 0 0 2px ${ATELIER.bg}, 0 0 0 3.5px ${ATELIER.ink}` : 'inset 0 0 0 1px rgba(0,0,0,.2)' }} />)}</span>;
ATELIER.TopBar = ({ scanOn, role }) => <div style={{ padding: '0 20px' }}>
  <div style={{ display: 'flex', alignItems: 'center', height: 44 }}>
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 10, height: 34, padding: '0 12px 0 6px', borderRadius: 999, background: ATELIER.surface }}><img src={XD.A + 'logo/sutra-mark-gold.png'} style={{ height: 22 }} /><span style={{ width: 1, height: 14, background: ATELIER.line2 }} /><img src={XD.A + 'clients/srs-dress-only.png'} style={{ height: 18 }} /><span style={{ fontFamily: ATELIER.fontUI, fontSize: 11, letterSpacing: '.12em', color: ATELIER.ink2 }}>{role.toUpperCase()}</span></span>
    <span style={{ flex: 1 }} />
    <span style={{ width: 40, height: 40, borderRadius: 14, background: ATELIER.surface, display: 'grid', placeItems: 'center', color: ATELIER.ink }}><Ic name="search" size={18} /></span>
    <span style={{ width: 40, height: 40, borderRadius: 14, background: ATELIER.surface, display: 'grid', placeItems: 'center', color: ATELIER.ink, marginLeft: 8, boxShadow: scanOn ? `0 0 0 1.5px ${ATELIER.ok}` : 'none' }}><Ic name="scan-line" size={18} /></span>
    <span style={{ width: 40, height: 40, borderRadius: 14, background: ATELIER.surface, display: 'grid', placeItems: 'center', color: ATELIER.ink, marginLeft: 8 }}><Ic name="ellipsis" size={18} /></span>
  </div>
</div>;
ATELIER.Cats = ({ items, active, title }) => <div>
  {title && <div style={{ padding: '10px 20px 0', fontFamily: ATELIER.fontDisplay, fontSize: 34, color: ATELIER.ink, letterSpacing: '-.01em' }}>{title}</div>}
  <div style={{ display: 'flex', gap: 6, padding: '12px 20px 0', overflow: 'hidden' }}>{items.map(c => <ATELIER.Chip key={c} on={c === active}>{c}</ATELIER.Chip>)}</div>
</div>;
ATELIER.GridCard = ({ d, inCart, tall }) => <div style={{ position: 'relative', borderRadius: ATELIER.rPhoto, overflow: 'hidden', background: ATELIER.photoBg, aspectRatio: tall ? '3/4.4' : '3/3.6' }}>
  {d.src ? <img src={d.src} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} /> : <div style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', fontFamily: ATELIER.fontDisplay, fontSize: 34, color: ATELIER.ink3 }}>{d.code}</div>}
  <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg,rgba(23,17,14,0) 50%,rgba(23,17,14,.78) 100%)' }} />
  <div style={{ position: 'absolute', top: 10, left: 10, right: 10, display: 'flex', alignItems: 'center', gap: 6 }}>{d.tag && <ATELIER.Tag tone={d.tagTone === 'gold' ? 'gold' : 'accent'}>{d.tag}</ATELIER.Tag>}{d.note && <ATELIER.Tag tone="danger">{d.note}</ATELIER.Tag>}<span style={{ flex: 1 }} /><span style={{ width: 32, height: 32, borderRadius: '50%', background: inCart ? ATELIER.gold : 'rgba(243,234,223,.92)', color: ATELIER.bg, display: 'grid', placeItems: 'center', fontFamily: ATELIER.fontUI, fontSize: 13, fontWeight: 600 }}>{inCart ? inCart : <Ic name="plus" size={16} sw={2} />}</span></div>
  <div style={{ position: 'absolute', left: 12, right: 12, bottom: 12 }}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ fontFamily: ATELIER.fontMono, fontSize: 11, color: ATELIER.ink2 }}>{d.code}</span><ATELIER.Bars names={d.colours} /></div>
    <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginTop: 4 }}><span style={{ fontFamily: ATELIER.fontDisplay, fontSize: 16, color: ATELIER.ink, flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{d.name}</span><Price v={d.price} size={17} font={ATELIER.fontUI} color={ATELIER.ink} dim={ATELIER.ink2} weight={500} /></div>
  </div>
</div>;
ATELIER.CartTray = ({ active }) => <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '0 16px', overflow: 'hidden' }}>
  {CARTS.map(c => { const on = c.k === active; return <span key={c.k} style={{ display: 'inline-flex', alignItems: 'center', gap: 10, height: 46, padding: '0 14px 0 6px', borderRadius: 999, background: on ? ATELIER.gold : '#2A2019', border: `1px solid ${on ? 'transparent' : ATELIER.line2}`, color: on ? ATELIER.bg : ATELIER.ink, boxShadow: ATELIER.shadow, flex: 'none' }}><span style={{ width: 34, height: 34, borderRadius: '50%', background: on ? 'rgba(23,17,14,.18)' : ATELIER.surface2, display: 'grid', placeItems: 'center', fontFamily: ATELIER.fontDisplay, fontSize: 16 }}>{c.k}</span><span style={{ fontFamily: ATELIER.fontUI, fontSize: 13, fontWeight: 500, whiteSpace: 'nowrap' }}>{c.name.split(' ')[0]} <span style={{ opacity: .6 }}>{c.n}</span></span></span>; })}
  <span style={{ width: 46, height: 46, borderRadius: '50%', background: ATELIER.surface, display: 'grid', placeItems: 'center', color: ATELIER.ink, flex: 'none' }}><Ic name="plus" size={18} /></span>
</div>;
ATELIER.BottomBar = ({ active }) => <div style={{ margin: '0 16px', height: 70, borderRadius: 30, background: '#241B17', border: `1px solid ${ATELIER.line}`, boxShadow: ATELIER.shadow, display: 'flex', alignItems: 'center', justifyContent: 'space-around', padding: '0 8px' }}>
  {NAV.slice(0, 5).map(([i, l]) => { const on = l === active; return <span key={l} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, width: 56 }}><span style={{ width: 44, height: 36, borderRadius: 14, background: on ? ATELIER.ink : 'transparent', color: on ? ATELIER.bg : ATELIER.ink3, display: 'grid', placeItems: 'center' }}><Ic name={i} size={20} sw={on ? 2 : 1.6} /></span><span style={{ fontFamily: ATELIER.fontUI, fontSize: 10, letterSpacing: '.04em', color: on ? ATELIER.ink : ATELIER.ink3 }}>{l}</span></span>; })}
</div>;
Object.assign(window, { GALLERY, ATELIER });
