#!/usr/bin/env bash
# Rebuild explorations/catalogue-v2/COMPONENTS.md: every name each board file exports, plus the file's first comment line.
# Read that file instead of the 600 KB of JSX when looking for a component to reuse.
#   bash .claude/skills/sutra-mockups/scripts/components-index.sh
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
V2="$ROOT/explorations/catalogue-v2"; OUT="$V2/COMPONENTS.md"
{
  echo "# Board components · what each file exports"
  echo
  echo "Generated by \`.claude/skills/sutra-mockups/scripts/components-index.sh\` on $(date +%d\ %b\ %Y). Names are globals (one shared script scope);"
  echo "a file may use anything exported by a file that loads before it (order: \`base\` in modules.js, then the module's files)."
  echo
  for f in "$ROOT/design-system/ui_kits/sutra-mobile/ios-frame.jsx" "$ROOT"/design-system/ui_kits/catalogue-explorations/{common,themes,screens}.jsx \
           "$V2"/themes2.jsx "$V2"/screens2.jsx "$V2"/final.jsx "$V2"/web.jsx "$V2"/mod-*.jsx; do
    [[ -f "$f" ]] || continue
    rel="${f#$ROOT/}"
    first="$(grep -m1 -o '/\*.*' "$f" | sed 's#^/\* *##; s# *\*/.*##' | cut -c1-160)"
    names="$(grep -o 'Object\.assign(window, *{[^}]*}' "$f" | sed 's/Object\.assign(window, *{//; s/}//' | tr ',' '\n' | sed 's/^ *//; s/ *$//' | grep -v '^$' | sort -u | tr '\n' ' ')"
    [[ -z "$names" ]] && names="$(grep -o '^\(const\|function\) [A-Z][A-Za-z0-9_]*' "$f" | awk '{print $2}' | sort -u | tr '\n' ' ') (top-level, not exported explicitly)"
    echo "## \`$rel\`"
    [[ -n "$first" ]] && echo "$first"
    echo
    echo "$names" | fold -s -w 118 | sed 's/^/    /'
    echo
  done
} > "$OUT"
echo "wrote ${OUT#$ROOT/} ($(wc -l < "$OUT") lines)"
